#!/usr/bin/env python3
"""
Extract the real vehicle roster from the Burnout 3 game data.

Reads pveh/vlist.bin and every pveh/<CLASS>/Car*.bgv|btv header, and emits a C
header the game can compile against. Only fields verified against the files are
emitted -- see docs/RE_NOTES.md section 5. Mesh data is NOT extracted; .bgv
geometry is stored as NV2A push-buffers and is still undecoded.
"""
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from b3_paths import game_path, game_root  # noqa: E402
import struct, os, sys, glob, json

CLASS_NAMES = {
    'COMP': 'Compact', 'CUPE': 'Coupe', 'HEVY': 'Heavy', 'HSPC': 'HSpec',
    'MSCL': 'Muscle', 'SPRT': 'Sports', 'SUPR': 'Super', 'TSPC': 'TSpec',
}

BGV_MAGIC = 0x17

# +0x0C is a per-file variant/feature word, not a fixed version. Observed values
# across the 107 shipped vehicles: 0x0406, 0x0405, 0x0403, and 0 (traffic-only
# models, which also zero the +0x18 dimension). Validation therefore keys on the
# magic plus the self-describing size field at +0x08, both of which hold for
# every file on disc.
BGV_VARIANTS = (0x0406, 0x0405, 0x0403, 0x0000)


def read_header(path):
    """Parse the verified .bgv/.btv header. Returns None if it doesn't match."""
    with open(path, 'rb') as fh:
        d = fh.read(0x80)
    if len(d) < 0x80:
        return None
    magic, zero, size, ver, count = struct.unpack_from('<5I', d, 0)
    if magic != BGV_MAGIC or size != os.path.getsize(path):
        return None
    dim_a, dim_b = struct.unpack_from('<2f', d, 0x14)
    scale = struct.unpack_from('<4f', d, 0x1C)
    offsets = struct.unpack_from('<8I', d, 0x4C)
    actual = os.path.getsize(path)
    return {
        'file': os.path.basename(path),
        'size_field': size,
        'size_actual': actual,
        'size_ok': size == actual,
        'variant': ver,
        'variant_known': ver in BGV_VARIANTS,
        'sections': count,
        'dim_a': round(dim_a, 5),
        'dim_b': round(dim_b, 5),
        'scale': [round(s, 4) for s in scale],
        'offsets': [o for o in offsets if o],
    }


def car_sort_key(name):
    stem = os.path.splitext(name)[0]
    digits = ''.join(c for c in stem if c.isdigit())
    return (int(digits) if digits else 0, stem)


def collect(pveh_dir):
    vlist = os.path.join(pveh_dir, 'vlist.bin')
    declared = None
    if os.path.exists(vlist):
        with open(vlist, 'rb') as fh:
            head = struct.unpack('<2I', fh.read(8))
        declared = {'version': head[0], 'count': head[1]}

    classes = []
    for cls in sorted(CLASS_NAMES):
        cdir = os.path.join(pveh_dir, cls)
        if not os.path.isdir(cdir):
            continue
        entries = []
        for ext, kind in (('bgv', 'player'), ('btv', 'traffic')):
            for p in sorted(glob.glob(os.path.join(cdir, '*.%s' % ext)),
                            key=lambda q: car_sort_key(os.path.basename(q))):
                h = read_header(p)
                if h is None:
                    print('  ! unrecognised header: %s' % p, file=sys.stderr)
                    continue
                h['kind'] = kind
                entries.append(h)
        if entries:
            classes.append({'code': cls, 'name': CLASS_NAMES[cls], 'vehicles': entries})
    return declared, classes


def emit_header(declared, classes, out_path):
    total = sum(len(c['vehicles']) for c in classes)
    lines = [
        '// Generated by tools/extract_vehicles.py -- do not edit by hand.',
        '// Real vehicle roster extracted from Burnout 3 game data.',
        '// Geometry is NOT included: .bgv meshes are NV2A push-buffers, undecoded.',
        '#ifndef BURNOUT3_VEHICLE_DATA_H',
        '#define BURNOUT3_VEHICLE_DATA_H',
        '',
        'typedef enum { VEH_PLAYER = 0, VEH_TRAFFIC = 1 } VehicleKind;',
        '',
        'typedef struct {',
        '    const char*  file;      // source filename in pveh/<class>/',
        '    const char*  class_code;',
        '    const char*  class_name;',
        '    VehicleKind  kind;',
        '    unsigned     data_size; // bytes of model data on disk',
        '    unsigned     variant;   // header +0x0C feature word',
        '    unsigned     sections;  // header +0x10',
        '    float        dim_a;     // header +0x14',
        '    float        dim_b;     // header +0x18',
        '} VehicleInfo;',
        '',
    ]
    if declared:
        lines += ['#define VLIST_VERSION %du' % declared['version'],
                  '#define VLIST_DECLARED_COUNT %du' % declared['count'], '']
    lines += ['#define VEHICLE_COUNT %d' % total, '',
              'static const VehicleInfo VEHICLES[VEHICLE_COUNT] = {']
    for c in classes:
        lines.append('    /* --- %s (%s) --- */' % (c['name'], c['code']))
        for v in c['vehicles']:
            lines.append(
                '    { "%s", "%s", "%s", %s, %uu, 0x%04Xu, %uu, %.5ff, %.5ff },' % (
                    v['file'], c['code'], c['name'],
                    'VEH_PLAYER' if v['kind'] == 'player' else 'VEH_TRAFFIC',
                    v['size_actual'], v['variant'], v['sections'],
                    v['dim_a'], v['dim_b']))
    lines += ['};', '', '#endif // BURNOUT3_VEHICLE_DATA_H', '']
    with open(out_path, 'w') as fh:
        fh.write('\n'.join(lines))
    return total


def main():
    pveh = sys.argv[1] if len(sys.argv) > 1 else \
        game_path('pveh')
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/burnout3_vehicle_data.h'

    declared, classes = collect(pveh)
    total = emit_header(declared, classes, out)

    print('vlist.bin  : version=%s declared_count=%s' % (
        declared['version'] if declared else '?',
        declared['count'] if declared else '?'))
    bad = [v['file'] for c in classes for v in c['vehicles'] if not v['size_ok']]
    for c in classes:
        p = sum(1 for v in c['vehicles'] if v['kind'] == 'player')
        t = len(c['vehicles']) - p
        print('  %-5s %-8s player=%-3d traffic=%-3d' % (c['code'], c['name'], p, t))
    print('found      : %d vehicles' % total)
    if declared:
        print('cross-check: %s (vlist says %d, found %d)' % (
            'MATCH' if declared['count'] == total else 'MISMATCH',
            declared['count'], total))
    print('size field : %s' % ('all %d headers match file size' % total if not bad
                               else 'MISMATCH in %r' % bad))
    print('wrote      : %s' % out)


if __name__ == '__main__':
    main()
