#!/usr/bin/env python3
"""Extract a track's real race start grid -> src/burnout3_start_grid.h + grid.bin.

Track-agnostic: `--track US_C3_V1` / `B3_TRACK=...` (ids from
tools/extract_tlist.py); the .bgd walk lives in tools/extract_bgd_paths.py.

Provenance [C]: the grid is the first six 0x50-byte slots of the EVENT
SPATIAL RECORD, and that record is located the way the game's own .bgd
parser locates it -- `FUN_0018B250` reads the event's 0x800-byte param
record (offset from the u32 table at file 0x198, event count at file 0x260)
and then seeks to `{size = param+0x3BC, offset = param+0x3C0}`
(`mov eax,[eax+0x3c0]` @0x0018B4A1, `+0x3bc` @0x0018B4D6).  Spatial records
are SHARED between events and are NOT at 0xC000 + slot*0x800: on AS/C1_V1
the single-race event's record is at 0xC800 and NO event uses 0xC000, so the
previous extraction read a stale record whose grid sits ~90 m away facing
roughly the opposite direction.

Slot layout (0x50 bytes, rows are unit vectors -- asserted here):
  +0x00 f32[4] right   +0x10 f32[4] up   +0x20 f32[4] at (forward)
  +0x30 f32[4] position                  +0x40 u32 road-network node index

Emitted in the harness's GL space (z negated, RE_NOTES 12).

grid.bin (little-endian):
  +0x00 char[4] 'B3GR'   +0x04 u32 version = 1   +0x08 u32 slot_count
  +0x0C u32 node_index_present (1)
  +0x10 per slot: f32 pos[3], f32 fwd[3], f32 right[3], f32 up[3], u32 node
"""
import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_tlist as tl                                   # noqa: E402
import extract_bgd_paths as bp                               # noqa: E402


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    tl.add_track_arg(ap)
    ap.add_argument("--event", default=bp.DEFAULT_EVENT)
    ap.add_argument("--header", default=None)
    args = ap.parse_args()

    track = tl.resolve(args.track)
    bgd = bp.BGD(os.path.join(track['dir'], "Gamedata.bgd"))
    ev = bgd.event(args.event)
    d = bgd.d
    so = ev['spatial'][1]
    slots = []
    for k in range(6):
        o = so + k * 0x50
        right = bp.f3(d, o)
        up = bp.f3(d, o + 0x10)
        at = bp.f3(d, o + 0x20)
        pos = bp.f3(d, o + 0x30)
        node = bp.u32(d, o + 0x40)
        for nm, v in (("right", right), ("up", up), ("at", at)):
            n2 = v[0] ** 2 + v[1] ** 2 + v[2] ** 2
            assert 0.98 < n2 < 1.02, \
                "slot %d %s is not a unit vector (%.4f)" % (k, nm, n2)
        slots.append((pos, at, right, up, node))

    span = max(bp.dist(a[0], b[0]) for a in slots for b in slots)
    print("%s (%s): event %s spatial record @%#x, %d grid slots, "
          "formation span %.1f m, nodes %s"
          % (track['id'], track['name'], ev['id'], so, len(slots), span,
             sorted({s[4] for s in slots})))

    hdr = args.header or os.path.join(os.path.dirname(__file__), "..", "src",
                                      "burnout3_start_grid.h")
    with open(hdr, 'w') as f:
        w = f.write
        w("// GENERATED by tools/extract_start_grid.py -- DO NOT EDIT\n")
        w("// %s = %s, event %s: the six start-grid slots of the event\n"
          % (track['id'], track['name'], ev['id']))
        w("// SPATIAL record @%#x, located through the game's own .bgd\n" % so)
        w("// parser (param record +0x3BC/+0x3C0, FUN_0018B250 @0x0018B4A1)\n")
        w("// [C].  GL space: z negated per RE_NOTES 12.\n\n")
        w("#ifndef BURNOUT3_START_GRID_H\n#define BURNOUT3_START_GRID_H\n\n")
        w("typedef struct { float pos[3]; float fwd[3]; } B3GridSlot;\n")
        w("static const B3GridSlot B3_START_GRID[%d] = {\n" % len(slots))
        for pos, at, _r, _u, _n in slots:
            w("    {{%.4ff, %.4ff, %.4ff}, {%.5ff, %.5ff, %.5ff}},\n"
              % (pos[0], pos[1], -pos[2], at[0], at[1], -at[2]))
        w("};\nenum { B3_START_GRID_COUNT = %d };\n\n" % len(slots))
        w("#endif\n")
    print("wrote", os.path.normpath(hdr))

    out = os.path.join(tl.out_root(track), "grid.bin")
    with open(out, 'wb') as f:
        f.write(b'B3GR')
        f.write(struct.pack('<III', 1, len(slots), 1))
        for pos, at, r, u, node in slots:
            for v in (pos, at, r, u):
                f.write(struct.pack('<3f', v[0], v[1], -v[2]))
            f.write(struct.pack('<I', node))
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
