#!/usr/bin/env python3
"""
Differential test for src/burnout3_takedown.c: the ported takedown-FX code
versus the REAL x86 executing under Unicorn.

Same contract as tools/validate_port.py and tools/validate_gameplay.py --
every case either runs the actual game function and asserts the C port
reproduces its post-state, or asserts a value read straight out of the
retail image / retail data file.  Nothing is compared against a
transcription.

Sections
  1  time dilation      FUN_001B5AC0 / FUN_001B5B60 executed, C mirrored
  2  cinematic gate     FUN_00027A60 executed over 7 seedings
  3  cinematic entry    FUN_00027920 executed, incl. the HUD event ids
  4  cinematic update   FUN_00027AD0 executed frame-by-frame for 4.8 s
  5  cinematic exit     FUN_000279C0 executed
  6  image constants    every timeline constant read from the mapped ELF
  7  callout art        the 17-entry sign table read from the image
  8  camera parameters  Camera.cfg keys resolved in the retail Data/vdb.xml
 10  camera law         FUN_0015E550's smoothing core executed under Unicorn,
                        the director/mode tables + geometry read from the image
 11  crash director     the WHOLE FUN_0015E550 executed over seeded wreck
                        transforms, plus the player-crash dilation window

Usage: python3 tools/validate_takedown.py [-v]
"""
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from b3_paths import game_path, game_root  # noqa: E402
import importlib.util
import json
import os
import struct
import subprocess
import sys

_here = os.path.dirname(os.path.abspath(__file__))
_root = os.path.dirname(_here)
sys.path.insert(0, _here)

_spec = importlib.util.spec_from_file_location(
    "tdfx", os.path.join(_here, "emulate_tdfx.py"))
tdfx = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(tdfx)

VERBOSE = '-v' in sys.argv
PASS = 0
FAIL = 0
FAILURES = []


def check(name, got, want, tol=0.0):
    global PASS, FAIL
    if isinstance(want, float) or isinstance(got, float):
        ok = abs(float(got) - float(want)) <= tol
    elif (isinstance(want, list) and isinstance(got, list)
          and len(want) == len(got)
          and all(isinstance(x, float) for x in want)):
        # float32 round-trip: 0.1 is not exactly representable
        ok = all(abs(a - b) <= 1e-6 * max(1.0, abs(b))
                 for a, b in zip(got, want))
    else:
        ok = got == want
    if ok:
        PASS += 1
        if VERBOSE:
            print("  ok   %-58s %s" % (name, got))
    else:
        FAIL += 1
        FAILURES.append("%s: got %r want %r" % (name, got, want))
        print("  FAIL %-58s got %r want %r" % (name, got, want))


# --------------------------------------------------------------------------
# the C driver: generated here so the repo Makefile stays untouched
# --------------------------------------------------------------------------
DRIVER_C = r'''
/* GENERATED by tools/validate_takedown.py -- do not edit, do not commit. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "burnout3_takedown.h"

static B3TdfxPost posts[64];
static B3TdfxPostSink sink = { posts, 0, 64 };

static void print_posts(void)
{
    int i;
    printf("posts=");
    for (i = 0; i < sink.count; i++)
        printf("%s%d:%d:%d", i ? "," : "",
               posts[i].hud_event, posts[i].hud_arg, posts[i].state);
    printf("\n");
}

int main(int argc, char **argv)
{
    const char *mode = argc > 1 ? argv[1] : "";

    if (!strcmp(mode, "timer")) {
        /* argv[2] = period, argv[3..] = the divisor requested per frame */
        B3TdfxTimer t;
        int i;
        b3_tdfx_timer_init(&t, (float)atof(argv[2]));
        for (i = 3; i < argc; i++) {
            t.requested = atoi(argv[i]);
            b3_tdfx_timer_tick(&t, i - 2);
            printf("%d %d %.9f %.9f\n", i - 2, t.divisor, t.dt, t.clock);
        }
        return 0;
    }
    if (!strcmp(mode, "rescale")) {
        /* period cur req whole rem */
        B3TdfxTimer t;
        b3_tdfx_timer_init(&t, (float)atof(argv[2]));
        t.divisor   = atoi(argv[3]);
        t.requested = atoi(argv[4]);
        t.whole     = atoi(argv[5]);
        t.rem       = atoi(argv[6]);
        b3_tdfx_timer_rescale(&t);
        printf("%d %.9f %d %d\n", t.divisor, t.dt, t.whole, t.rem);
        return 0;
    }
    if (!strcmp(mode, "gate")) {
        /* victim_present victim_crashed me_crashed cam_active same_victim
           victim_clock victim_stamp */
        B3TdCamRecord r;
        B3TdRacecar me, v;
        memset(&r, 0, sizeof(r));
        memset(&me, 0, sizeof(me));
        memset(&v, 0, sizeof(v));
        v.crashed     = (unsigned char)atoi(argv[3]);
        v.clock       = (float)atof(argv[7]);
        v.crash_stamp = (float)atof(argv[8]);
        me.victim  = atoi(argv[2]) ? &v : 0;
        me.crashed = (unsigned char)atoi(argv[4]);
        r.active   = (unsigned char)atoi(argv[5]);
        r.victim   = atoi(argv[6]) ? (void *)&v : 0;
        printf("%d\n", b3_td_cam_gate(&r, &me));
        return 0;
    }
    if (!strcmp(mode, "enter")) {
        /* signature already_active chain */
        B3TdfxTimer t;
        B3TdCamRecord r;
        B3TdRacecar me, v;
        B3TdVehicle pv;
        b3_tdfx_timer_init(&t, B3_TDFX_PERIOD_NTSC);
        memset(&r, 0, sizeof(r));
        memset(&me, 0, sizeof(me));
        memset(&v, 0, sizeof(v));
        memset(&pv, 0, sizeof(pv));
        r.elapsed   = -1.0f;
        r.active    = (unsigned char)atoi(argv[3]);
        v.grid_slot = 1;
        me.victim     = &v;
        me.signature  = atoi(argv[2]);
        me.chain_flag = (unsigned char)atoi(argv[4]);
        me.pv         = &pv;
        sink.count = 0;
        b3_td_cam_enter(&r, &me, &t, &sink);
        printf("victim=%d elapsed=%.6f active=%d flag_c=%d done=%d chain=%d "
               "div=%d\n",
               r.victim ? 1 : 0, r.elapsed, r.active, r.flag_c,
               r.callout_done, r.chain, t.requested);
        print_posts();
        return 0;
    }
    if (!strcmp(mode, "update")) {
        /* nframes real_dt crash_at finish_at chain ramp_done */
        B3TdfxTimer t;
        B3TdCamRecord r;
        B3TdRacecar me, v;
        B3TdVehicle pv;
        int n = atoi(argv[2]), i;
        float dt = (float)atof(argv[3]);
        int crash_at = atoi(argv[4]), finish_at = atoi(argv[5]);
        b3_tdfx_timer_init(&t, B3_TDFX_PERIOD_NTSC);
        memset(&r, 0, sizeof(r));
        memset(&me, 0, sizeof(me));
        memset(&v, 0, sizeof(v));
        memset(&pv, 0, sizeof(pv));
        v.crashed   = 1;
        v.grid_slot = 1;
        me.victim = &v;
        me.pv = &pv;
        me.boost_ramp_done = (unsigned char)atoi(argv[7]);
        pv.authority = 0.25f;
        pv.drift_state = 4;
        r.victim = &v;
        r.elapsed = 0.0f;
        r.active = 1;
        r.flag_c = 1;
        r.chain = (unsigned char)atoi(argv[6]);
        t.requested = 5;
        for (i = 0; i < n; i++) {
            if (crash_at >= 0 && i == crash_at) me.crashed = 1;
            if (finish_at >= 0 && i == finish_at) me.race_state = 3;
            sink.count = 0;
            b3_td_cam_update(&r, &me, &t, &sink, dt);
            printf("%d %.6f %d %d %d %d %d %d %d %.6f %d ", i, r.elapsed,
                   r.active, r.callout_done, r.flag_c, t.requested,
                   me.cam_active, me.hud_flag, me.burnout_grant,
                   pv.authority, pv.drift_state);
            printf("%d ", pv.flags1353);
            print_posts();
            if (!r.active) break;
        }
        return 0;
    }
    if (!strcmp(mode, "exit")) {
        /* cam_on drift_state */
        B3TdfxTimer t;
        B3TdCamRecord r;
        B3TdRacecar me;
        B3TdVehicle pv;
        b3_tdfx_timer_init(&t, B3_TDFX_PERIOD_NTSC);
        memset(&r, 0, sizeof(r));
        memset(&me, 0, sizeof(me));
        memset(&pv, 0, sizeof(pv));
        me.cam_active = (unsigned char)atoi(argv[2]);
        me.hud_flag = 1;
        me.pv = &pv;
        pv.drift_state = atoi(argv[3]);
        pv.authority = 0.1f;
        r.victim = (void *)&me;
        r.elapsed = 3.0f;
        r.active = 1;
        r.flag_c = 1;
        t.requested = 5;
        b3_td_cam_exit(&r, &me, &t);
        printf("victim=%d elapsed=%.6f active=%d flag_c=%d div=%d cam=%d "
               "hud=%d auth=%.6f drift=%d\n",
               r.victim ? 1 : 0, r.elapsed, r.active, r.flag_c, t.requested,
               me.cam_active, me.hud_flag, pv.authority, pv.drift_state);
        return 0;
    }
    if (!strcmp(mode, "callout")) {
        const B3TdfxCallout *c;
        b3_tdfx_init();
        b3_tdfx_post_callout(atoi(argv[2]), 0, 0);
        c = b3_tdfx_callout();
        printf("%d %d %d %d %d %.6f %.6f %.6f\n", c->msg_id, c->string_index,
               c->sign_index, c->anim_style, c->flags,
               c->t_in, c->t_hold_end, c->t_total);
        return 0;
    }
    if (!strcmp(mode, "priority")) {
        int a, b, up, d, e2;
        b3_tdfx_init();
        b3_tdfx_post_callout(0x93, 0, 0);
        a = b3_tdfx_post_callout(0xA7, 0, 0);
        b = b3_tdfx_post_callout(0x93, 0, 0);
        up = b3_tdfx_callout()->msg_id;
        b3_tdfx_init();
        d = b3_tdfx_post_callout(0x80, 0, 0);
        b3_tdfx_init();
        e2 = b3_tdfx_post_callout(0x80, 1, 0);
        printf("%d %d %d %d %d\n", a, b, up, d, e2);
        return 0;
    }
    if (!strcmp(mode, "api")) {
        /* end-to-end through the singleton API */
        B3TdfxStatus st;
        int i;
        b3_tdfx_init();
        printf("armed=%d\n",
               b3_tdfx_on_takedown(0, 0, 1, 1, 1.0f, 0.5f, -1, 0));
        for (i = 0; i < 320; i++) {
            float sim_dt = b3_tdfx_update(1.0f / 60.0f);
            b3_tdfx_status(&st);
            printf("%d %.6f %d %d %.9f %d %d\n", i, st.t, st.active,
                   st.divisor, sim_dt, st.callout_visible, st.callout_sign);
            if (!st.active) break;
        }
        return 0;
    }
    if (!strcmp(mode, "camlaw")) {
        float sms = (float)atof(argv[2]);
        float dt  = (float)atof(argv[3]);
        float sx  = (float)atof(argv[4]);
        float sy  = (float)atof(argv[5]);
        int   n   = b3_cam_substeps(dt);
        float g   = b3_cam_speed_gate(sms);
        printf("%d %.9f %.9f %.9f\n", n, g,
               b3_cam_follow_blend(sx, g,    n),
               b3_cam_follow_blend(sy, 1.0f, n));
        return 0;
    }
    if (!strcmp(mode, "camstep")) {
        B3TdfxCamera tc;
        float vp[3] = { 10.0f, 1.0f, 20.0f };
        float vv[3] = { 12.0f, 0.0f, 5.0f };
        float ap[3] = { 4.0f, 1.0f, 18.0f };
        int i, nf = atoi(argv[2]);
        b3_tdfx_init();
        b3_tdfx_on_takedown(0, 0, 1, 1, 1.0f, 0.5f, -1, 0);
        for (i = 0; i < nf; i++) {
            b3_tdfx_update(1.0f / 60.0f);
            if (!b3_tdfx_camera(vp, vv, ap, 1.0f / 60.0f, &tc))
                break;
            printf("%d %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.4f %.6f %.6f\n",
                   i, tc.eye[0], tc.eye[1], tc.eye[2],
                   tc.look[0], tc.look[1], tc.look[2],
                   tc.weight, tc.fov, tc.pitch_deg, tc.yaw_deg);
        }
        return 0;
    }
    if (!strcmp(mode, "crashcam")) {
        B3TdfxCamera tc;
        float wp[3] = { 3.0f, 1.0f, -7.0f };
        float wv[3] = { 0.0f, 0.0f, -18.0f };
        int i, nf = atoi(argv[2]);
        b3_tdfx_init();
        b3_tdfx_crash_camera_reset();
        for (i = 0; i < nf; i++) {
            if (!b3_tdfx_crash_camera(wp, wv, 18.0f, 1.0f / 60.0f, &tc))
                break;
            printf("%d %.6f %.6f %.6f %.4f %.6f\n", i,
                   tc.eye[0], tc.eye[1], tc.eye[2], tc.fov, tc.pitch_deg);
        }
        return 0;
    }
    if (!strcmp(mode, "followcam")) {
        /* followcam <frames> <dt> <speed> <boost> <lookback>
         *           <12 matrix floats> <yaw0> <pitch0>
         * runs the recovered FUN_0015E550 law frame-by-frame; the car
         * transform is held fixed so the state's convergence is visible. */
        B3CamFollow st;
        B3TdfxCamera tc;
        float rows[12];
        int i, nf = atoi(argv[2]);
        float dt = (float)atof(argv[3]);
        float sms = (float)atof(argv[4]);
        float boost = (float)atof(argv[5]);
        int lb = atoi(argv[6]);
        for (i = 0; i < 12; i++) rows[i] = (float)atof(argv[7 + i]);
        b3_cam_follow_init(&st);
        st.look_back = lb;
        st.yaw_deg   = (float)atof(argv[19]);
        st.pitch_deg = (float)atof(argv[20]);
        for (i = 0; i < nf; i++) {
            b3_cam_follow_update(&st, rows, sms, boost, dt, &tc);
            printf("%d %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f "
                   "%.6f %.6f\n", i,
                   tc.eye[0], tc.eye[1], tc.eye[2],
                   tc.quat[0], tc.quat[1], tc.quat[2], tc.quat[3],
                   tc.fov, tc.pitch_deg, tc.yaw_deg,
                   tc.focus[0], tc.focus[2]);
        }
        return 0;
    }
    if (!strcmp(mode, "crashtl")) {
        /* crashtl <frames> <impact_armed> <boost_frame_lo> <boost_frame_hi>
         *         <end_frame> -- the recovered player-crash dilation
         * window: one divisor-5 request at the wreck, the impact machine
         * on the dilated clock, aftertouch, and the crash-mode exit. */
        B3TdfxStatus s;
        int i, nf = atoi(argv[2]);
        int armed = atoi(argv[3]);
        int blo = atoi(argv[4]), bhi = atoi(argv[5]);
        int endf = atoi(argv[6]);
        b3_tdfx_init();
        b3_tdfx_event_reset();
        printf("req=%d\n", b3_tdfx_crash_begin());
        /* the ARM now carries FUN_00026A70's gate: only a car-vs-OBJECT
         * contact whose record has +0x174 & 8 set and +0x174 & 2 clear
         * opens the window.  `armed` supplies that qualification. */
        if (armed) b3_tdfx_impact_hit_object(8);
        for (i = 0; i < nf; i++) {
            b3_tdfx_set_aftertouch(1, (i >= blo && i < bhi));
            if (i == endf) b3_tdfx_crash_end();
            b3_tdfx_update(1.0f / 60.0f);
            b3_tdfx_status(&s);
            printf("%d %d %.6f %.6f\n", i, s.divisor, s.clock, s.pitch);
        }
        return 0;
    }
    if (!strcmp(mode, "substeps")) {
        /* FUN_0015E550 @0x0015E5DC: n = (int)(60*dt + 0.5).  At the
         * dilated dt this is 0, which zeroes every blend. */
        printf("%d\n", b3_cam_substeps(1.0f / (float)atoi(argv[2])));
        return 0;
    }
    if (!strcmp(mode, "crasharm")) {
        /* FUN_00026A70's gate on the touched object's record +0x174 */
        B3TdfxStatus s;
        int r[4], i;
        int flags[4] = { -1, 8, 8 | 2, 4 };
        for (i = 0; i < 4; i++) {
            b3_tdfx_init();
            b3_tdfx_event_reset();
            if (flags[i] < 0) b3_tdfx_impact_hit();      /* bare wreck */
            else              b3_tdfx_impact_hit_object(flags[i]);
            /* run past the 0.05 s delay at divisor 1 and see if 6 appears */
            r[i] = 0;
            for (int f = 0; f < 60; f++) {
                b3_tdfx_update(1.0f / 60.0f);
                b3_tdfx_status(&s);
                if (s.divisor == 6) { r[i] = 1; break; }
            }
        }
        printf("%d %d %d %d\n", r[0], r[1], r[2], r[3]);
        return 0;
    }
    if (!strcmp(mode, "crashcredit")) {
        int a, b, c;
        b3_tdfx_init();
        b3_tdfx_event_reset();
        a = b3_tdfx_crash_begin();
        b = b3_tdfx_crash_begin();
        b3_tdfx_event_reset();
        c = b3_tdfx_crash_begin();
        printf("%d %d %d\n", a, b, c);
        return 0;
    }
    fprintf(stderr, "unknown mode\n");
    return 2;
}
'''

DRIVER_SRC = os.path.join(_root, "build", "tdfx_driver.c")
DRIVER_BIN = os.path.join(_root, "build", "tdfx_driver")


def build_driver():
    os.makedirs(os.path.join(_root, "build"), exist_ok=True)
    with open(DRIVER_SRC, 'w') as f:
        f.write(DRIVER_C)
    cmd = ["gcc", "-Wall", "-Wextra", "-std=c11", "-O2",
           "-I" + os.path.join(_root, "src"), "-o", DRIVER_BIN, DRIVER_SRC,
           os.path.join(_root, "src", "burnout3_takedown.c"), "-lm"]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout)
        print(r.stderr)
        raise SystemExit("driver build failed")
    if r.stderr.strip():
        print("  (driver build warnings)\n" + r.stderr)


def drive(*args):
    r = subprocess.run([DRIVER_BIN] + [str(a) for a in args],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("driver failed: %s\n%s" % (args, r.stderr))
    return [ln for ln in r.stdout.splitlines() if ln.strip()]


# --------------------------------------------------------------------------
# section 1: time dilation
# --------------------------------------------------------------------------
def section_timer():
    print("\n[1] time dilation -- FUN_001B5AC0 / FUN_001B5B60 executed")
    sched = [1, 1, 1, 5, 5, 5, 5, 5, 1, 1, 1, 6, 6, 3, 3, 4, 4, 1]
    real = tdfx.run_timer(sched)
    c = drive("timer", 1.0 / 60.0, *sched)
    check("timer: frame count", len(c), len(real))
    for i, ln in enumerate(c):
        f, div, dt, clock = ln.split()
        check("timer f%02d divisor" % i, int(div), real[i]['div'])
        check("timer f%02d dt" % i, float(dt), real[i]['dt'], 1e-9)
        check("timer f%02d clock" % i, float(clock), real[i]['clock'], 1e-6)

    # the divisor really is a 1/N timescale: 5 frames at divisor 5 advance
    # the clock by exactly one normal frame
    dilated = real[7]['clock'] - real[2]['clock']
    check("5 dilated frames == 1 normal frame", round(dilated, 7),
          round(real[2]['clock'] - real[1]['clock'], 7), 1e-6)

    for cur, req, whole, rem in ((1, 5, 10, 0), (5, 1, 10, 3), (5, 1, 10, 2),
                                 (5, 3, 7, 4), (3, 6, 100, 2), (6, 1, 4, 4)):
        r = tdfx.run_rescale(cur, req, whole, rem)
        out = drive("rescale", 1.0 / 60.0, cur, req, whole, rem)[0].split()
        tag = "rescale %d->%d rem%d" % (cur, req, rem)
        check(tag + " divisor", int(out[0]), r['div'])
        check(tag + " dt", float(out[1]), r['dt'], 1e-9)
        check(tag + " whole", int(out[2]), r['whole'])
        check(tag + " rem", int(out[3]), r['rem'])


# --------------------------------------------------------------------------
# section 2: the trigger gate
# --------------------------------------------------------------------------
def section_gate():
    print("\n[2] cinematic gate -- FUN_00027A60 executed")
    cases = [
        ("nominal",            dict(), (1, 1, 0, 0, 0, 1.0, 0.5)),
        ("victim not crashed", dict(victim_crashed=0), (1, 0, 0, 0, 0, 1.0, 0.5)),
        ("attacker crashed",   dict(attacker_crashed=1), (1, 1, 1, 0, 0, 1.0, 0.5)),
        ("camera already up",  dict(cam_active=1), (1, 1, 0, 1, 0, 1.0, 0.5)),
        ("crash 1.4 s ago",    dict(victim_clock=1.9), (1, 1, 0, 0, 0, 1.9, 0.5)),
        ("crash 1.6 s ago",    dict(victim_clock=2.1), (1, 1, 0, 0, 0, 2.1, 0.5)),
        ("crash in the future", dict(victim_clock=0.4), (1, 1, 0, 0, 0, 0.4, 0.5)),
        ("no victim",          dict(victim_ptr=0), (0, 1, 0, 0, 0, 1.0, 0.5)),
    ]
    for name, kw, cargs in cases:
        real = tdfx.run_gate(**kw)
        got = int(drive("gate", *cargs)[0])
        check("gate: " + name, got, real)


def section_gate_dedup():
    # run the real function with record+0x00 already == the victim
    e = tdfx.Emu()
    tdfx.seed_common(e)
    a = tdfx.seed_racecar(e, 0, cls=0)
    v = tdfx.seed_racecar(e, 1, cls=1, crashed=1)
    e.wf(v + 0x10DC, 1.0)
    e.wf(v + 0x140C, 0.5)
    e.wi(a + 0x15A4, v)
    tdfx.seed_record(e, slot=0, victim=v, active=0)
    from unicorn.x86_const import UC_X86_REG_EDX
    real = e.call(tdfx.F_GATE, regs={UC_X86_REG_EDX: tdfx.CAMREC}) & 0xFF
    got = int(drive("gate", 1, 1, 0, 0, 1, 1.0, 0.5)[0])
    check("gate: same victim as last time", got, real)


# --------------------------------------------------------------------------
# section 3: entry
# --------------------------------------------------------------------------
def section_enter():
    print("\n[3] cinematic entry -- FUN_00027920 executed")
    for name, sig, active, chain in (("plain takedown", -1, 0, 0),
                                     ("signature takedown", 7, 0, 0),
                                     ("burnout chain flag", -1, 0, 1),
                                     ("re-entry blocked", -1, 1, 0)):
        real = tdfx.run_enter(signature=sig, already_active=active,
                              chain_flag=chain)
        out = drive("enter", sig, active, chain)
        kv = dict(p.split('=') for p in out[0].split())
        check("enter[%s] active" % name, int(kv['active']), real['active'])
        check("enter[%s] flag_c" % name, int(kv['flag_c']), real['flag_c'])
        check("enter[%s] callout_done" % name, int(kv['done']),
              real['callout_done'])
        check("enter[%s] chain" % name, int(kv['chain']), real['chain'])
        check("enter[%s] elapsed" % name, float(kv['elapsed']),
              real['elapsed'], 1e-6)
        check("enter[%s] divisor request" % name, int(kv['div']),
              real['div_req'])
        cposts = out[1][len("posts="):]
        cevents = [tuple(int(x) for x in p.split(':')[:2])
                   for p in cposts.split(',') if p and p.split(':')[0] != '-1']
        cstates = [int(p.split(':')[2]) for p in cposts.split(',')
                   if p and p.split(':')[2] != '-1']
        check("enter[%s] HUD events" % name, cevents, real['hud_events'])
        check("enter[%s] presentation states" % name, cstates, real['states'])


# --------------------------------------------------------------------------
# section 4: the per-frame update
# --------------------------------------------------------------------------
def parse_update(lines):
    out = []
    for ln in lines:
        head, _, p = ln.partition("posts=")
        f = head.split()
        ev = [tuple(int(x) for x in q.split(':')[:2])
              for q in p.split(',') if q and q.split(':')[0] != '-1']
        st = [int(q.split(':')[2]) for q in p.split(',')
              if q and q.split(':')[2] != '-1']
        out.append(dict(i=int(f[0]), t=float(f[1]), active=int(f[2]),
                        callout_done=int(f[3]), flag_c=int(f[4]),
                        div_req=int(f[5]), cam_on=int(f[6]),
                        hud_flag=int(f[7]), burnout_grant=int(f[8]),
                        pv_auth=float(f[9]), pv_drift=int(f[10]),
                        pv_flags=int(f[11]), hud_events=ev, states=st))
    return out


def section_update():
    print("\n[4] cinematic update -- FUN_00027AD0 executed frame-by-frame")
    scenarios = [
        ("full 4.8 s run", dict(), (320, 1.0 / 60.0, -1, -1, 0, 0)),
        ("attacker crashes at f30",
         dict(attacker_crashes_at=30), (320, 1.0 / 60.0, 30, -1, 0, 0)),
        ("race finishes at f100",
         dict(race_state_3_at=100), (320, 1.0 / 60.0, -1, 100, 0, 0)),
        ("burnout chain, ramp not done",
         dict(chain_flag=1), (320, 1.0 / 60.0, -1, -1, 1, 0)),
        ("burnout chain, ramp done",
         dict(chain_flag=1, ramp_done=1), (320, 1.0 / 60.0, -1, -1, 1, 1)),
    ]
    for name, kw, cargs in scenarios:
        real = tdfx.run_update_series(**kw)
        cfr = parse_update(drive("update", *cargs))
        check("update[%s] frame count" % name, len(cfr), len(real))
        n = min(len(cfr), len(real))
        bad = 0
        for i in range(n):
            for key in ('active', 'callout_done', 'flag_c', 'div_req',
                        'cam_on', 'hud_flag', 'burnout_grant', 'pv_drift',
                        'pv_flags', 'hud_events', 'states'):
                if cfr[i][key] != real[i][key]:
                    bad += 1
                    if bad < 6:
                        print("     f%-4d %-14s C=%r real=%r"
                              % (i, key, cfr[i][key], real[i][key]))
            if abs(cfr[i]['t'] - real[i]['t']) > 1e-4:
                bad += 1
            if abs(cfr[i]['pv_auth'] - real[i]['pv_auth']) > 1e-5:
                bad += 1
        check("update[%s] all fields, all frames" % name, bad, 0)

    # explicit timeline assertions on the executed run
    real = tdfx.run_update_series()
    slow = [f for f in real if f['div_req'] == 5]
    check("slow-mo phase ends at 2.8 s", slow[-1]['t'] < 2.8, True)
    check("first normal frame is past 2.8 s",
          [f for f in real if f['div_req'] == 1][0]['t'] >= 2.8, True)
    co = [f for f in real if f['hud_events']]
    check("exactly one callout post", len(co), 1)
    check("callout event id", co[0]['hud_events'][0][0], 10)
    check("callout fires at >= 2.5 s", co[0]['t'] >= 2.5, True)
    check("callout fires within one frame of 2.5 s",
          co[0]['t'] - 2.5 < 1.0 / 60.0, True)
    check("cinematic length in frames at 60 Hz", len(real), 288)


# --------------------------------------------------------------------------
# section 5: exit
# --------------------------------------------------------------------------
def section_exit():
    print("\n[5] cinematic exit -- FUN_000279C0 executed")
    for name, cam_on, drift in (("camera up, drift 4", 1, 4),
                                ("camera up, drift 0", 1, 0),
                                ("camera down, drift 4", 0, 4)):
        real = tdfx.run_exit(cam_on=cam_on, drift_state=drift)
        kv = dict(p.split('=') for p in drive("exit", cam_on, drift)[0].split())
        check("exit[%s] active" % name, int(kv['active']), real['active'])
        check("exit[%s] flag_c" % name, int(kv['flag_c']), real['flag_c'])
        check("exit[%s] elapsed" % name, float(kv['elapsed']),
              real['elapsed'], 1e-6)
        check("exit[%s] victim cleared" % name, int(kv['victim']),
              1 if real['victim'] else 0)
        check("exit[%s] divisor request" % name, int(kv['div']),
              real['div_req'])
        check("exit[%s] camera flag" % name, int(kv['cam']), real['cam_on'])
        check("exit[%s] hud flag" % name, int(kv['hud']), real['hud_flag'])
        check("exit[%s] steering authority" % name, float(kv['auth']),
              real['pv_auth'], 1e-6)
        check("exit[%s] drift state" % name, int(kv['drift']),
              real['pv_drift'])


# --------------------------------------------------------------------------
# section 6: image constants
# --------------------------------------------------------------------------
def section_constants():
    print("\n[6] timeline constants read from the mapped image")
    got = tdfx.read_constants()
    for a, want in tdfx.CONST.items():
        check("0x%08X" % a, got[a], want, 1e-6)
    # the header must carry the same numbers
    hdr = open(os.path.join(_root, "src", "burnout3_takedown.h")).read()
    for macro, want in (("B3_TDFX_CINE_TOTAL", "4.8f"),
                        ("B3_TDFX_CINE_SLOWMO", "2.8f"),
                        ("B3_TDFX_CINE_CALLOUT", "2.5f"),
                        ("B3_TDFX_TRIGGER_AGE", "1.5f"),
                        ("B3_TDFX_IMPACT_DELAY", "0.05f"),
                        ("B3_TDFX_IMPACT_LEN", "0.35f"),
                        ("B3_TDFX_PITCH_DILATED", "0.75f")):
        check("header %s" % macro, ("#define %s %s" % (macro, want)) in
              " ".join(hdr.split()), True)


# --------------------------------------------------------------------------
# section 7: the callout art table
# --------------------------------------------------------------------------
SIGN_NAMES = ['hud_sign_flame', 'hud_sign_skull', 'hud_award_star',
              'hud_signs_td', 'MedalGold', 'MedalSilver', 'MedalBronze',
              'HUD_crash_boost', 'HUD_crash_score01', 'HUD_crash_score02',
              'HUD_crash_score03', 'HUD_crash_x2', 'HUD_crash_x4',
              'HUD_crash_breaker', 'HUD_crash_skull', 'HUD_crash_stealer',
              'Bad']


def section_signs():
    print("\n[7] callout art -- sign table at 0x00388560 read from the image")
    e = tdfx.Emu()
    for i, want in enumerate(SIGN_NAMES):
        p = e.ru(0x00388560 + i * 4)
        s = e.r(p, 64).split(b'\0')[0].decode('ascii', 'replace')
        check("sign[%d]" % i, s, want)
    check("takedown sign index is 3", SIGN_NAMES.index('hud_signs_td'), 3)
    hdr = open(os.path.join(_root, "src", "burnout3_takedown.h")).read()
    check("header B3_TDFX_SIGN_TAKEDOWN == 3",
          "#define B3_TDFX_SIGN_TAKEDOWN       3" in hdr, True)


# --------------------------------------------------------------------------
# section 8: camera parameters resolved in the retail VDB
# --------------------------------------------------------------------------
CAM_EXPECT = {
    ("Crash/HandyCam", "Spring Coeff"): [15.0, 15.0, 15.0],
    ("Crash/HandyCam", "Damping"): [10.0, 10.0, 10.0],
    ("Crash/HandyCam", "Safe FOV Horiz"): [0.1],
    ("Crash/HandyCam", "Safe FOV Vert"): [0.5],
    ("InGame/Effect/Slam/Position", "Spring Coeff"): [15.0, 15.0, 15.0],
    ("InGame/Effect/Slam/Angular", "Spring Coeff"): [15.0, 15.0, 200.0],
    ("InGame/Effect/Slam/Angular", "Force"): [0.0, 0.0, 10000.0],
    ("InGame/Effect/Shake/Position", "Spring Coeff"): [300.0, 30.0, 50.0],
}


def section_camera_params():
    print("\n[8] Camera.cfg parameters resolved in the retail Data/vdb.xml")
    _s = importlib.util.spec_from_file_location(
        "camx", os.path.join(_here, "emulate_tdfx_camera.py"))
    camx = importlib.util.module_from_spec(_s)
    try:
        _s.loader.exec_module(camx)
    except Exception as exc:                    # pragma: no cover
        print("  SKIP (%s)" % exc)
        return
    cache = os.path.join(_root, "build", "tdfx_camparams.json")
    if os.path.exists(cache):
        rows = json.load(open(cache))
    else:
        rows = []
        vdb, _ = camx.cvdb.read_vdb()
        blob = open(camx.cvdb.VDB_FILE, 'rb').read()
        _t, dvc, _u, _f, fdo = struct.unpack_from('<IIIII', blob, 0)
        for addr in camx.REGISTRARS:
            events, _defaults, _err = camx.run(addr)
            for ev in events:
                g, p = camx.split_key(ev['string'])
                h = ev['hash']
                raw = vdb.get(h)
                if raw is None:
                    continue
                n1 = camx.vdb_value(raw, 1, blob, 20 + dvc * 8, fdo)
                n3 = camx.vdb_value(raw, 3, blob, 20 + dvc * 8, fdo)
                vals = n1 if (n1 and abs(n1[0]) > 1e-30) else n3
                rows.append(dict(group=g, param=(p or '').strip(), vdb=vals))
        os.makedirs(os.path.dirname(cache), exist_ok=True)
        json.dump(rows, open(cache, 'w'))
    index = {(r['group'], r['param']): r['vdb'] for r in rows}
    for key, want in CAM_EXPECT.items():
        got = index.get(key)
        check("vdb %s / %s" % key, got, want)
    check("all 34 shake/handycam keys resolve in the retail VDB",
          len([r for r in rows if r['vdb'] is not None]) >= 34, True)


# --------------------------------------------------------------------------
# section 9: the callout message table + Globalus.bin strings + descriptors
# --------------------------------------------------------------------------
MSG_TABLE = 0x00389160          # 206 x {u8 id, u8 kind, u16 stringIndex}
MSG_TABLE_N = 206
DESC_TABLE = 0x003895E8         # 17 x 16 bytes
KIND_JUMP = 0x00054ACC          # FUN_00054700's kind-3 dispatch
GLOBALUS = (game_path('Data/Globalus.bin'))

# what the C module carries, mirrored here; every row is checked against
# the image and against the retail string table
EXPECT_MSGS = [
    (0x35, 1, 2100, "TAKEDOWN DENIED!"), (0x36, 1, 2101, "LUCKY ESCAPE!"),
    (0x7F, 3, 2103, "CRASHED!"), (0x80, 3, 2104, "TAKEN OUT!"),
    (0x81, 3, 2105, "TAKEDOWN AVENGED!"),
    (0x93, 4, 2074, "TAKEDOWN!"),
    (0x94, 4, 2079, "CAR TAKEDOWN!"), (0x95, 4, 2080, "VAN TAKEDOWN!"),
    (0x96, 4, 2081, "TRUCK TAKEDOWN!"), (0x97, 4, 2082, "BIG RIG TAKEDOWN!"),
    (0x98, 4, 2083, "BUS TAKEDOWN!"), (0x99, 4, 2084, "L-TRAIN TAKEDOWN!"),
    (0x9A, 4, 2086, "TRAM TAKEDOWN!"), (0x9B, 4, 2085, "MONORAIL TAKEDOWN!"),
    (0x9C, 4, 2087, "TRAILER TAKEDOWN!"), (0x9D, 4, 2089, "WALL TAKEDOWN!"),
    (0x9E, 4, 2088, "BONUS TAKEDOWN!"),
    (0x9F, 4, 2096, "TAKEDOWN 2-IN-A-ROW"),
    (0xA0, 4, 2097, "TAKEDOWN 3-IN-A-ROW"),
    (0xA1, 4, 2098, "TAKEDOWN HOT STREAK"),
    (0xA2, 4, 2099, "TAKEDOWN RAMPAGE!"),
    (0xA3, 4, 2075, "DOUBLE TAKEDOWN!"), (0xA4, 4, 2076, "TRIPLE TAKEDOWN!"),
    (0xA5, 4, 2077, "4-WAY TAKEDOWN!"), (0xA6, 4, 2078, "TOTAL TAKEDOWN!"),
    (0xA7, 4, 2094, "REVENGE!"), (0xA8, 4, 2095, "GRUDGE!"),
    (0xA9, 4, 2093, "PSYCHE OUT!"), (0xAA, 4, 2102, "AFTERTOUCH TAKEDOWN!"),
    (0xAF, 4, 2090, "SIGNATURE TAKEDOWN"),
    (0xC2, 4, 2090, "SIGNATURE TAKEDOWN"),
]

KIND_TO_DESC = {3: 7, 4: 6, 5: 0, 6: 0, 7: 0, 8: 0, 9: 1, 10: 5, 11: 4,
                12: 3, 13: 2, 14: 0, 15: 9, 16: 10, 17: 11, 18: 12, 19: 13,
                20: 8, 21: 14, 22: 15, 23: 16}


def globalus_string(blob, idx):
    off = struct.unpack_from('<I', blob, 0x10 + idx * 4)[0]
    end = off
    while end + 1 < len(blob) and blob[end:end + 2] != b'\0\0':
        end += 2
    return blob[off:end].decode('utf-16-le', 'replace')


def section_callout():
    print("\n[9] callout: message table + descriptors + Globalus strings")
    e = tdfx.Emu()
    raw = e.r(MSG_TABLE, MSG_TABLE_N * 4)
    table = {}
    for i in range(MSG_TABLE_N):
        mid, kind = raw[i * 4], raw[i * 4 + 1]
        sidx = struct.unpack_from('<H', raw, i * 4 + 2)[0]
        table[mid] = (kind, sidx)
    check("message table has 206 distinct ids", len(table), MSG_TABLE_N)

    blob = open(GLOBALUS, 'rb').read()
    cnt = struct.unpack_from('<I', blob, 8)[0]
    first = struct.unpack_from('<I', blob, 0x10)[0]
    check("Globalus.bin TOC self-consistent (first offset == TOC end)",
          first, 0x10 + cnt * 4)

    for mid, kind, sidx, text in EXPECT_MSGS:
        got = table.get(mid)
        check("msg 0x%02X kind" % mid, got[0] if got else None, kind)
        check("msg 0x%02X string index" % mid, got[1] if got else None, sidx)
        check("msg 0x%02X text" % mid, globalus_string(blob, sidx), text)

    # descriptors
    draw = e.r(DESC_TABLE, 17 * 16)
    for i, want in enumerate([(1, 1, 0, 0x00), (4, 2, 1, 0x02),
                              (1, 1, 2, 0x06), (1, 1, 4, 0x00),
                              (2, 1, 5, 0x00), (3, 1, 6, 0x00),
                              (1, 1, 3, 0x0D), (4, 2, 1, 0x0D)]):
        got = struct.unpack_from('<4I', draw, i * 16)
        check("descriptor %d" % i, list(got), list(want))
    check("takedown descriptor (6) sign index is hud_signs_td",
          struct.unpack_from('<4I', draw, 6 * 16)[2], 3)

    # kind -> descriptor dispatch, read out of the jump table
    jt = e.r(KIND_JUMP, 21 * 4)
    handlers = [struct.unpack_from('<I', jt, i * 4)[0] for i in range(21)]
    # each handler is `mov esi, <imm32>` (BE xx xx xx xx) except kind 13
    for kind in (3, 4, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23):
        h = handlers[kind - 3]
        op = e.r(h, 5)
        check("kind %d handler is MOV ESI,imm" % kind, op[0], 0xBE)
        check("kind %d -> descriptor" % kind,
              struct.unpack_from('<I', op, 1)[0], KIND_TO_DESC[kind])
    for kind in (5, 6, 7, 8, 14):
        check("kind %d falls through to descriptor 0" % kind,
              handlers[kind - 3], handlers[5 - 3])

    # the animation constants that set the on-screen lifetime
    for name, va, want in (("DAT_0054FB90 src 0x003B1870 (anim1 in)",
                            0x003B1870, 1.5),
                           ("DAT_0054FB50 src 0x003A55F8 (anim2 in)",
                            0x003A55F8, 0.75),
                           ("hold long, anim1 (0x003B1688)", 0x003B1688, 2.0),
                           ("hold short, anim1 (0x003B1728)",
                            0x003B1728, 0.125),
                           ("hold long, anim2 (0x003B1F34)", 0x003B1F34, 2.25),
                           ("out base (0x003B1684)", 0x003B1684, 0.5),
                           ("out extra (0x003B1730)", 0x003B1730, 0.25)):
        check(name, e.rf(va), want, 1e-6)

    # ... and the resulting takedown-callout schedule, computed by the C port
    out = drive("callout", 0x93)[0].split()
    check("callout msg", int(out[0]), 0x93)
    check("callout string index", int(out[1]), 2074)
    check("callout sign index", int(out[2]), 3)
    check("callout anim style", int(out[3]), 1)
    check("callout flags", int(out[4]), 0x0D)
    check("callout IN ends at", float(out[5]), 1.5, 1e-6)
    check("callout HOLD ends at (element +0x154)", float(out[6]), 3.5, 1e-6)
    check("callout total on-screen", float(out[7]), 4.25, 1e-6)

    # FUN_00199350's priority rule: a lower id cannot replace a higher one
    pr = drive("priority")[0].split()
    check("priority: REVENGE(0xA7) replaces TAKEDOWN(0x93)", int(pr[0]), 1)
    check("priority: TAKEDOWN(0x93) refused while REVENGE up", int(pr[1]), 0)
    check("priority: still showing REVENGE", int(pr[2]), 0xA7)
    check("victim-side 0x80 refused when not crashed", int(pr[3]), 0)
    check("victim-side 0x80 accepted when crashed", int(pr[4]), 1)



# ----------------------------------------------------------------------
# 10. The camera (RE_TAKEDOWN_FX section 8)
#
# The director's 20-mode table, each mode's vtable and its enter/update
# virtuals, the two ValueDB config blocks and the follow camera's smoothing
# core.  The smoothing core is EXECUTED (emulate_tdfx_camera.follow_blend
# runs the real span 0x0015E5B6..0x0015E734) and diffed against the C.
# ----------------------------------------------------------------------

# mode index -> (sub-object offset in the director, vtable VA)
# read out of the director constructor at 0x00015900
CAM_MODE_TABLE = [
    (0x070, 0x003A9514), (0x2F0, 0x003A94FC), (0x370, 0x003A9C28),
    (0x398, 0x003A9C28), (0x4C0, 0x003A975C), (0x3C0, 0x003A975C),
    (0x540, 0x003A93D0), (0x730, 0x003A93D0), (0xB60, 0x003A9AB8),
    (0xB90, 0x003A975C), (0x920, 0x003AA0C4), (0xAB0, 0x003A9384),
    (0xABC, 0x003A9384), (0xBD0, 0x003A93BC), (0xAD0, 0x003A9514),
    (0x500, 0x003AA118), (0x520, 0x003AA118), (0x400, 0x003A975C),
    (0x440, 0x003A975C), (0x480, 0x003A975C),
]

# the camera-controller message dispatcher's two jump tables
CAM_MSG_CASES = [0, 12, 12, 12, 12, 12, 12, 1, 2, 3, 4, 5, 12, 12,
                 6, 7, 12, 12, 8, 12, 9, 10, 11]
CAM_MSG_HANDLERS = [0x001688BD, 0x00168516, 0x00168591, 0x001685B5,
                    0x001686CE, 0x00168788, 0x0016898B, 0x0016892E,
                    0x0016894D, 0x001684CA, 0x001684E9, 0x0016896C,
                    0x001689CC]


def section_camera_law():
    print("\n[10] the camera: director tables, geometry, and the follow law")
    e = tdfx.Emu()

    # -- 10a. the 20-mode table and the per-mode virtuals ----------------
    # the director constructor is a straight run of vtable stores; assert
    # every vtable VA the table claims really is an operand inside it, and
    # that every one carries an enter (+0x08) and an update (+0x10) virtual
    ctor = e.r(0x00015900, 0x00015A55 - 0x00015900)
    for i, (off, vt) in enumerate(CAM_MODE_TABLE):
        check("mode %2d vtable 0x%08X stored by the ctor" % (i, vt),
              struct.pack('<I', vt) in ctor, True)
        check("mode %2d sub-object offset 0x%03X in the ctor" % (i, off),
              struct.pack('<I', off) in ctor or off < 0x100, True)
        check("mode %2d enter  != 0" % i, e.ru(vt + 0x08) != 0, True)
        check("mode %2d update != 0" % i, e.ru(vt + 0x10) != 0, True)

    # the chase camera: modes 2 and 3 share one class, and it is the class
    # whose update is FUN_0015E550
    check("mode 2 and 3 share a class", CAM_MODE_TABLE[2][1],
          CAM_MODE_TABLE[3][1])
    check("chase class vtable", CAM_MODE_TABLE[2][1], 0x003A9C28)
    check("chase enter  = FUN_0015E060", e.ru(0x003A9C28 + 0x08), 0x0015E060)
    check("chase update = FUN_0015E550", e.ru(0x003A9C28 + 0x10), 0x0015E550)
    # modes 0 and 14 are the two the director ticks with the REAL dt
    check("mode 0 and 14 share a class", CAM_MODE_TABLE[0][1],
          CAM_MODE_TABLE[14][1])
    check("real-dt class update = 0x0015C130",
          e.ru(0x003A9514 + 0x10), 0x0015C130)

    # -- 10b. the message dispatcher's jump tables -----------------------
    got = list(e.r(0x00168A20, len(CAM_MSG_CASES)))
    check("camera message -> case table @0x00168A20", got, CAM_MSG_CASES)
    for i, want in enumerate(CAM_MSG_HANDLERS):
        check("camera handler case %2d" % i,
              e.ru(0x001689EC + i * 4), want)

    # -- 10c. Camera/Follow geometry, straight out of FUN_00160840 -------
    for name, va, want in (("Camera Offset .y (0x003A69B8)", 0x003A69B8, 0.95),
                           ("Camera Offset .z (0x003B1B80)", 0x003B1B80, -6.8),
                           ("Focus  Offset .y (0x0039B2B0)", 0x0039B2B0, 0.35),
                           ("Focus  Offset .z (0x003B1688)", 0x003B1688, 2.0),
                           ("Spring Coeff  .x (0x00387C04)", 0x00387C04, 0.06),
                           ("Spring Coeff  .y (0x003A69C4)", 0x003A69C4, 0.1),
                           ("Spring Coeff  .z (0x003B1694)", 0x003B1694, 5.0),
                           ("Down Angle       (0x003B03EC)", 0x003B03EC, 1.8),
                           ("FOV degrees      (0x003B1850)", 0x003B1850, 90.0),
                           ("substep rate     (0x003F720C)", 0x003F720C, 60.0),
                           ("substep round    (0x003B1684)", 0x003B1684, 0.5),
                           ("speed gate mph   (0x0038994C)",
                            0x0038994C, 2.236936330795288),
                           ("speed gate scale (0x003B1A08)", 0x003B1A08, 0.02),
                           ("clamp one        (0x003B168C)", 0x003B168C, 1.0)):
        check(name, e.rf(va), want, 1e-6)
    # the two rotation axes the update composes with
    check("pitch axis (0x00414AD0)",
          [e.rf(0x00414AD0 + k * 4) for k in range(3)], [1.0, 0.0, 0.0])
    check("yaw   axis (0x00414AE0)",
          [e.rf(0x00414AE0 + k * 4) for k in range(3)], [0.0, 1.0, 0.0])
    # and that the header macros carry them
    hdr = open(os.path.join(_root, "src", "burnout3_takedown.h")).read()
    for macro, want in (("B3_CAM_FOLLOW_OFF_Y", "0.95f"),
                        ("B3_CAM_FOLLOW_OFF_Z", "(-6.8f)"),
                        ("B3_CAM_FOCUS_OFF_Y", "0.35f"),
                        ("B3_CAM_FOCUS_OFF_Z", "2.0f"),
                        ("B3_CAM_SPRING_X", "0.06f"),
                        ("B3_CAM_SPRING_Y", "0.1f"),
                        ("B3_CAM_SPRING_Z", "5.0f"),
                        ("B3_CAM_DOWN_ANGLE", "1.8f"),
                        ("B3_CAM_FOV", "90.0f")):
        line = [l for l in hdr.splitlines()
                if l.startswith("#define " + macro + " ")
                or l.startswith("#define " + macro + "\t")
                or (l.startswith("#define " + macro) and
                    l[8 + len(macro)] in " \t")]
        check("header %s carries %s" % (macro, want),
              bool(line) and want in line[0], True)

    # -- 10d. the Crash/HandyCam block is registered but never read ------
    # (retraction: the port used to drive the camera with it)
    txt = _text_bytes()
    hits = _count_refs_to_shake_cfg(txt)
    addrs = sorted(h[0] for h in hits)
    # the only two instructions that hand the block to anybody
    check("shake cfg ctor LEA @0x00167273 present", 0x00167273 in addrs, True)
    check("shake cfg dtor ADD @0x001AAA64 present", 0x001AAA64 in addrs, True)
    # ...and no instruction in the camera module (every mode's enter/update
    # and the whole director live in 0x0015B000..0x0017B000) addresses into
    # the block at all, which is why the springs are dead config here.
    incam = [a for a in addrs if 0x0015B000 <= a < 0x0017B000]
    check("no camera-module instruction addresses the shake cfg block",
          incam, [0x00167273])

    # -- 10e. THE LAW, executed --------------------------------------
    _s = importlib.util.spec_from_file_location(
        "camx2", os.path.join(_here, "emulate_tdfx_camera.py"))
    camx = importlib.util.module_from_spec(_s)
    try:
        _s.loader.exec_module(camx)
    except Exception as exc:                    # pragma: no cover
        print("  SKIP follow_blend (%s)" % exc)
        return
    MPH = 2.236936330795288
    cases = []
    for dt in (1.0 / 60.0, 1.0 / 30.0, 0.05, 1.0 / 120.0, 0.1):
        for mph in (0.0, 12.5, 25.0, 50.0, 100.0, 200.0):
            cases.append((dt, mph))
    for dt, mph in cases:
        sms = mph / MPH
        bx, by = camx.follow_blend(sms, dt, 0.06, 0.1)
        # the real code leaves the RETAIN factors at [esp+0x24]/[esp+0x28]
        # at 0x0015E734; the blends are 1 - them (0x0015E73C / 0x0015E745)
        want_bx, want_by = 1.0 - bx, 1.0 - by
        out = drive("camlaw", "%.9f" % sms, "%.9f" % dt, 0.06, 0.1)[0].split()
        n, gate = int(out[0]), float(out[1])
        got_bx, got_by = float(out[2]), float(out[3])
        tag = "dt=%.5f mph=%.1f" % (dt, mph)
        check("%s  substeps" % tag, n, int(60.0 * dt + 0.5))
        check("%s  speed gate" % tag, gate, min(1.0, mph * 0.02), 1e-6)
        check("%s  blend pitch (executed)" % tag, got_bx, want_bx, 1e-6)
        check("%s  blend yaw   (executed)" % tag, got_by, want_by, 1e-6)

    # -- 10f. the ported cameras run and stay finite ---------------------
    rows = drive("camstep", 300)
    check("cinematic camera produced frames", len(rows) > 250, True)
    first = rows[0].split()
    check("cinematic camera FOV = 90", float(first[8]), 90.0, 1e-6)
    check("cinematic camera primes at Down Angle",
          float(first[9]), 1.8, 1e-4)
    for r in rows:
        f = [float(x) for x in r.split()[1:8]]
        if any(x != x or abs(x) > 1e6 for x in f):
            check("cinematic camera stays finite", False, True)
            break
    else:
        check("cinematic camera stays finite", True, True)
    rows = drive("crashcam", 120)
    check("crash camera produced frames", len(rows), 120)
    check("crash camera FOV = 90", float(rows[0].split()[4]), 90.0, 1e-6)


def _text_bytes():
    """(vaddr, bytes) of the .text-bearing load segments of the ELF."""
    path = os.path.join(_root, "build", "burnout3.elf")
    b = open(path, 'rb').read()
    phoff, = struct.unpack_from('<I', b, 0x1C)
    phentsize, phnum = struct.unpack_from('<HH', b, 0x2A)
    segs = []
    for i in range(phnum):
        o = phoff + i * phentsize
        t, off, va, _pa, fsz, _msz = struct.unpack_from('<6I', b, o)
        if t == 1 and 0x00011000 <= va < 0x00360000:
            segs.append((va, b[off:off + fsz]))
    return segs


def _count_refs_to_shake_cfg(segs):
    """Every instruction in .text that can produce DAT_0047A134 + 0x2C30.

    The camera-shake ValueDB block (11 groups x 0x30, group 0 =
    Crash/HandyCam) lives at manager+0x2C30.  If the springs were consumed
    anywhere, some instruction would have to address into the block off a
    base register -- a `[reg + disp]` memory operand, an `lea reg,[reg+disp]`
    or an `add reg, imm` -- with disp/imm inside it.  This counts exactly
    those three forms (bare immediates that merely happen to fall in the
    range, e.g. `push 0x2d80`, are not addressings and are excluded).

    Retail has exactly two hits: the constructor LEA at 0x00167273 that
    hands the block to the registrar FUN_00160B90, and the destructor ADD
    at 0x001AAA64 that hands it to the unregistrar FUN_00161990.  Nothing
    in between ever reads a spring, a damping or a Safe FOV out of it.
    """
    import re
    from capstone import Cs, CS_ARCH_X86, CS_MODE_32
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    lo, hi = 0x2C30, 0x2C30 + 11 * 0x30
    mem = re.compile(r'\[e[a-z]{2}(?:\s*\+\s*e[a-z]{2}(?:\*\d+)?)?'
                     r'\s*\+\s*(0x[0-9a-f]+)\]')
    addi = re.compile(r'^e[a-z]{2},\s*(0x[0-9a-f]+)$')
    hits = []
    for va, code in segs:
        pos = 0
        while pos < len(code):
            n = 0
            for ins in md.disasm(code[pos:], va + pos):
                n = ins.address - (va + pos) + ins.size
                cand = list(mem.findall(ins.op_str))
                if ins.mnemonic == 'add':
                    cand += addi.findall(ins.op_str)
                for tok in cand:
                    if lo <= int(tok, 16) < hi:
                        hits.append((ins.address, ins.mnemonic, ins.op_str))
                        break
            if n == 0:
                pos += 1
            else:
                pos += n
    return hits



# ----------------------------------------------------------------------
# 11. THE CRASH DIRECTOR (RE_TAKEDOWN_FX section 9)
#
# 11a. the negative that closes the "which camera does a crash select?"
#      question: the two ids FUN_00025CC0 hands to FUN_0018E050 land on
#      the camera dispatcher's DEFAULT handler, and FUN_0018E050 is not a
#      camera call at all.
# 11b. the whole chase-camera update FUN_0015E550 EXECUTED end to end over
#      seeded car transforms, diffed frame-by-frame against the C port.
# 11c. the player-crash dilation window: every writer read out of the
#      image at its literal address, and the ported machine's timeline.
# ----------------------------------------------------------------------
def section_crash_director():
    print("\n[11] the crash director: camera law executed + dilation window")
    e = tdfx.Emu()

    # -- 11a. messages 4 and 5 are NOT camera messages -------------------
    # the dispatcher at 0x001684AF: cmp eax,0x16 / movzx eax,[eax+0x168A20]
    # / jmp [eax*4+0x1689EC].  Index table entry 4 and 5 both select
    # handler 12, which is 0x001689CC -- the default (no-op) arm.
    for msg in (4, 5):
        check("camera message %d -> handler slot 12" % msg,
              e.rb(0x00168A20 + msg), 12)
    check("handler slot 12 is the default arm 0x001689CC",
          e.ru(0x001689EC + 12 * 4), 0x001689CC)
    # every message id that IS posted anywhere in the image goes through
    # FUN_00018B90 (push 5 = the "message" verb) or an inlined copy; none
    # of them is 4 or 5.  Assert the poster's shape instead.
    check("FUN_00018B90 loads the current state listener DAT_00567174",
          e.r(0x00018B90, 6), bytes.fromhex("8b0d74715600"))
    check("FUN_00018B90 posts verb 5 (message) to it",
          e.r(0x00018BA9, 4), bytes.fromhex("6a05ff10"))
    # FUN_0018E050 is the race-RESULT recorder: it calls the game mode's
    # vtable+0x7C and then snapshots racecar+0x10D0 into +0x16D0
    check("FUN_0018E050 calls the game mode's vtbl+0x7C",
          e.r(0x0018E068, 3), bytes.fromhex("ff527c"))
    check("FUN_0018E050 copies 0x32 dwords of the score block",
          e.r(0x0018E0B5, 2) + e.r(0x0018E0BC, 2),
          bytes.fromhex("b932") + bytes.fromhex("f3a5"))

    # -- 11b. FUN_0015E550 executed end-to-end ---------------------------
    _s = importlib.util.spec_from_file_location(
        "camx3", os.path.join(_here, "emulate_tdfx_camera.py"))
    camx = importlib.util.module_from_spec(_s)
    _s.loader.exec_module(camx)

    import math

    def car_rows(pitch, yaw, roll, pos):
        p, y, r = (math.radians(v) for v in (pitch, yaw, roll))
        rx = [[1, 0, 0], [0, math.cos(p), math.sin(p)],
              [0, -math.sin(p), math.cos(p)]]
        ry = [[math.cos(y), 0, -math.sin(y)], [0, 1, 0],
              [math.sin(y), 0, math.cos(y)]]
        rz = [[math.cos(r), math.sin(r), 0], [-math.sin(r), math.cos(r), 0],
              [0, 0, 1]]
        def mul(a, b):
            return [[sum(a[i][k] * b[k][j] for k in range(3))
                     for j in range(3)] for i in range(3)]
        m = mul(mul(rz, rx), ry)
        return [m[0], m[1], m[2], list(pos)]

    # a seeded tumbling wreck: launch, spin, land.  Each scenario is run
    # for N frames with the transform frozen, so the exponential state
    # convergence is what is being diffed (the retail law is a pure
    # function of (state, transform, speed, dt)).
    SCEN = [
        # (pitch, yaw, roll, pos, speed m/s, boost ramp, look-back, frames)
        (0.0,   0.0,   0.0,  (0.0, 0.0, 0.0),     30.0, 0.0, 0, 8),
        (35.0,  0.0,   0.0,  (10.0, 2.0, 30.0),   28.0, 0.0, 0, 8),
        (-70.0, 140.0, 25.0, (-4.0, 6.5, 12.0),   22.0, 0.0, 0, 12),
        (88.0,  10.0, -170.0, (3.0, 4.0, -7.0),    9.0, 0.0, 0, 12),
        (0.0,   90.0,  0.0,  (0.0, 1.0, 0.0),      0.0, 0.0, 0, 6),
        (12.0,  -60.0, 0.0,  (1.0, 0.5, 2.0),     45.0, 1.0, 0, 6),
        (0.0,   30.0,  0.0,  (0.0, 1.0, 0.0),     30.0, 0.0, 1, 6),
    ]
    for si, (pi, yw, rl, pos, sms, boost, lb, nf) in enumerate(SCEN):
        rows = car_rows(pi, yw, rl, pos)
        flat = [c for r in rows for c in r]
        got = drive("followcam", nf, "%.9f" % (1.0 / 60.0), "%.6f" % sms,
                    "%.6f" % boost, lb, *["%.9f" % v for v in flat],
                    "0.0", "0.0")
        yaw, pitch = 0.0, 0.0
        for i in range(nf):
            want = camx.follow_update(rows, sms, 1.0 / 60.0, yaw, pitch,
                                      boost_ramp=boost, look_back=lb)
            yaw, pitch = want['yaw'], want['pitch']
            f = [float(x) for x in got[i].split()]
            tag = "scen%d f%d" % (si, i)
            check("%s eye (executed)" % tag, f[1:4], want['eye'], 2e-4)
            check("%s quat (executed)" % tag, f[4:8], want['quat'], 2e-4)
            check("%s fov (executed)" % tag, f[8], want['fov'], 1e-4)
            check("%s pitch state (executed)" % tag, f[9], want['pitch'], 2e-4)
            check("%s yaw state (executed)" % tag, f[10], want['yaw'], 2e-4)

    # the law's two structural facts, asserted at their literal addresses:
    # the pitch target comes from the car's forward .y (fpatan at
    # 0x0015E871) and the focus anchor is built from cfg+0x10 after the
    # `add edi,0x10` at 0x0015E7A5
    check("pitch target uses fpatan at 0x0015E871", e.r(0x0015E871, 2),
          bytes.fromhex("d9f3"))
    check("focus offset selected by ADD EDI,0x10 at 0x0015E7A5",
          e.r(0x0015E7A5, 3), bytes.fromhex("83c710"))
    check("Down Angle read from cfg+0x30 at 0x0015EC88",
          e.r(0x0015EC88, 5), bytes.fromhex("f30f104130"))
    check("FOV lerp endpoints 110 / 90", [e.rf(0x003F7210), e.rf(0x003F7214)],
          [110.0, 90.0])
    check("FOV dolly constant 2.3", e.rf(0x003F7218), 2.3, 1e-6)
    check("camera-collision speed gate 50 mph", e.rf(0x003F721C), 50.0, 1e-6)
    check("FUN_00011900 takes DEGREES (deg2rad at 0x0001190C)",
          e.rf(0x003A1248), 0.01745329238474369, 1e-9)

    # -- 11c. the dilation window ---------------------------------------
    # every writer, at its literal address
    check("0x00025D5C requests divisor 5 (the wreck instant)",
          e.r(0x00025D5C, 10),
          bytes.fromhex("c70524ea600005000000"))
    check("0x00025D66 latches DAT_00649B9E", e.r(0x00025D66, 7),
          bytes.fromhex("c6059e9b640001"))
    check("0x00025D33 gates it on the rules object's +0x4C",
          e.r(0x00025D33, 3), bytes.fromhex("8a4e4c"))
    check("0x00025CD6 decrements the credit racecar+0x16C8",
          e.r(0x00025CD5, 7), bytes.fromhex("498988c8160000"))
    check("0x00025AE5 arms the credit to 1 at the event reset",
          e.r(0x00025AE5, 10), bytes.fromhex("c786c816000001000000"))
    check("0x00025890 gates FUN_00025CC0 on a non-zero credit",
          e.r(0x00025890, 8), bytes.fromhex("8b86c816000085c0"))
    check("0x00119C24 restores divisor 1 on crash-mode exit",
          e.r(0x00119C24, 10), bytes.fromhex("c70524ea600001000000"))
    check("0x000269FD restores divisor 1 on recovery",
          e.r(0x000269FD, 10), bytes.fromhex("c70524ea600001000000"))
    check("0x00026525 restores divisor 1 when the impact window expires",
          e.r(0x00026525, 10), bytes.fromhex("c70524ea600001000000"))
    check("the impact window is measured on the DILATED clock 0x0060EA20",
          e.r(0x00026507, 8), bytes.fromhex("f30f100520ea6000"))
    check("impact delay 0.05", e.rf(0x003A69BC), 0.05, 1e-7)
    check("impact length 0.35", e.rf(0x0039B2B0), 0.35, 1e-7)

    # ---- 11c: the camera's dt is the DILATED one (RE_TAKEDOWN_FX 9.7) ----
    # FUN_000170B0 composes the camera delta as ticks * DAT_0060EA1C and
    # hands it to FUN_00167940, whose 20-mode dispatch gives that value to
    # every mode except 0 and 14.  The chase camera is mode 2.
    check("0x00017147 loads the sim-tick count [EDI+0x2E20C]",
          e.r(0x00017147, 8), bytes.fromhex("f30f2a870ce20200"))
    check("0x0001714F multiplies it by the DILATED dt DAT_0060EA1C",
          e.r(0x0001714F, 8), bytes.fromhex("f30f59051cea6000"))
    # FUN_00167940's per-mode dispatch: only modes 0 and 0xE take the real
    # DAT_004AE1FC; everything else -- the chase camera is mode 2 -- gets
    # the dilated product pushed from EBP.
    #   CMP EDI,0xE ; JZ +7 ; TEST EDI,EDI ; JZ +3 ; PUSH EBP ; JMP +7
    #   MOV EDX,[0x004AE1FC] ; PUSH EDX
    check("0x0016797E: only camera modes 0 and 14 take the UNDILATED dt",
          e.r(0x0016797E, 19),
          bytes.fromhex("83ff0e740785ff740355eb078b15fce14a0052"))
    # the port's consequence: at divisor 5 the blend exponent is zero
    check("port: b3_cam_substeps(1/300) == 0 (the camera angles HOLD)",
          drive("substeps", 300)[0], "0")
    check("port: b3_cam_substeps(1/360) == 0 (divisor 6 likewise)",
          drive("substeps", 360)[0], "0")
    check("port: b3_cam_substeps(1/60) == 1 (full speed)",
          drive("substeps", 60)[0], "1")

    # ---- 11d: the impact window's ARM is gated (FUN_00026A70) -----------
    # the arm itself: +0x44 = DILATED clock + 0.05, +0x52 = 1
    check("0x00026B18 stamps the window on the dilated clock + 0.05",
          e.r(0x00026B18, 25),
          bytes.fromhex("f30f100520ea6000f30f5805bc693a00"
                        "f30f114744c6475201"))
    # the same block is the "big hit" launch: a 0.5 world-up LINEAR kick
    # and a 1.6 forward kick (RE_NOTES 16.1's table) -- i.e. a scripted
    # launch by something big, not an ordinary wall crash
    check("0x00026AEE pushes the 0.5 world-up kick magnitude",
          e.r(0x00026AEE, 5), bytes.fromhex("680000003f"))
    check("0x00026B09 pushes the 1.6 forward kick magnitude",
          e.r(0x00026B09, 5), bytes.fromhex("68cdcccc3f"))
    a, b, c, d = drive("crasharm")[0].split()
    check("a bare wreck does NOT arm the impact window", int(a), 0)
    check("+0x174 & 8 set, & 2 clear -> arms", int(b), 1)
    check("+0x174 & 2 also set -> refused (0x00026B2D)", int(c), 0)
    check("+0x174 & 8 clear -> refused (0x00026B18)", int(d), 0)

    # the ported machine: one crash-presentation credit per event
    a, b, c = drive("crashcredit")[0].split()
    check("first crash takes the credit", int(a), 1)
    check("second crash does not", int(b), 0)
    check("the event reset re-arms it", int(c), 1)

    # timeline A: a wreck that also armed the impact hit (the common case)
    rows = drive("crashtl", 400, 1, -1, -1, -1)
    check("crashtl A: the request was made", rows[0], "req=1")
    div = [int(r.split()[1]) for r in rows[1:]]
    clk = [float(r.split()[2]) for r in rows[1:]]
    check("A: divisor 5 on the wreck frame", div[0], 5)
    # the impact window opens once the dilated clock passes start+0.05 and
    # closes at +0.35; both are measured on the dilated clock, so at 1/5
    # and 1/6 they take 5x / 6x as long in wall-clock frames
    six = [i for i, d in enumerate(div) if d == 6]
    check("A: the impact window engages divisor 6", len(six) > 0, True)
    check("A: it opens after ~0.05 dilated s",
          abs(clk[six[0]] - (clk[0] + 0.05)) < 0.02, True)
    check("A: it closes after ~0.35 dilated s more",
          abs(clk[six[-1]] - (clk[0] + 0.40)) < 0.02, True)
    check("A: 0.05 s at 1/5 = 15 wall frames", six[0], 15)
    check("A: 0.35 s at 1/6 = 126 wall frames", len(six), 126)
    check("A: full speed afterwards", div[six[-1] + 1], 1)
    check("A: and it stays there", set(div[six[-1] + 1:]), {1})

    # timeline B: no impact hit armed.  The crash's own divisor-5 request
    # is BOUNDED by B3_TDFX_IMPACT_LEN (0.35 s of dilated clock) and then
    # releases, instead of running to crash-mode exit.
    #
    # This assertion changed (2026-08-16) and the reason matters: retail
    # does NOT hold divisor 5 for a whole wreck.  DAT_0060EA24 has twelve
    # writers with a graduated profile -- 5 @0x0002795F/@0x00025D5C,
    # 4 @0x00118986, 3 @0x0011888E, 1 @0x00026695/@0x0002678D -- and the
    # restore @0x00026695 fires off a presentation state byte [ebp+0x52]
    # whose setter is in unmapped code, so the exact end condition is [?].
    # The old "runs until crash-mode exit" was OUR assumption, never a
    # recovered fact, and it made a crash last 5 GAME seconds at divisor 5
    # = 24.93 s of WALL clock (measured; an undilated crash is 4.98 s),
    # which the user reported as being stuck in crash mode.  Bounding it by
    # the one dilation window that IS recovered restores ~6.4 s.  GLUE
    # until the @0x00026xxx machine is recovered.
    rows = drive("crashtl", 400, 0, -1, -1, 200)
    div = [int(r.split()[1]) for r in rows[1:]]
    check("B: the wreck requests divisor 5", div[0], 5)
    check("B: released after the 0.35 s dilated window", div[199], 1)
    check("B: crash-mode exit keeps it at 1", div[200], 1)
    check("B: and it stays there", set(div[200:]), {1})

    # timeline C: aftertouch -- boost held over frames 250..300 re-engages
    # divisor 5 after the impact window has released, and the RELEASE only
    # fires because the engaged flag veh+0x4AC7 was set (0x001188CC)
    rows = drive("crashtl", 400, 1, 250, 300, -1)
    div = [int(r.split()[1]) for r in rows[1:]]
    check("C: full speed before boost", div[249], 1)
    check("C: boost held -> divisor 5", set(div[250:300]), {5})
    check("C: boost released -> divisor 1", div[300], 1)

    # the audio companion follows the divisor (0.75 while dilated)
    pit = [float(r.split()[3]) for r in rows[1:]]
    check("C: audio pitch 0.75 while dilated", pit[260], 0.75, 1e-6)
    check("C: audio pitch 1.0 at full speed", pit[320], 1.0, 1e-6)


def main():
    print("=" * 72)
    print("validate_takedown.py -- ported takedown FX vs the real x86")
    print("=" * 72)
    build_driver()
    section_timer()
    section_gate()
    section_gate_dedup()
    section_enter()
    section_update()
    section_exit()
    section_constants()
    section_signs()
    section_callout()
    section_camera_params()
    section_camera_law()
    section_crash_director()
    print("\n" + "=" * 72)
    print("%d/%d checks passed" % (PASS, PASS + FAIL))
    if FAIL:
        print("\nFailures:")
        for f in FAILURES:
            print("  " + f)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
