#!/usr/bin/env python3
"""
Acceptance test for the CRASH TRAJECTORY: the ported crash-entry kick and
crashed-path solver in src/burnout3_crash.c must reproduce the REAL retail
code running under Unicorn (tools/emulate_crash_traj.py).

Sections
  1. crash-entry kick        FUN_00125100 / FUN_00125380 whole-function
                             differential over a flag/pose/magnitude matrix
  2. crashed-path trajectory multi-frame 6DOF differential: seed the C port
                             from the real machine's state at the first fully
                             airborne frame and step it for the rest of the
                             wreck's flight; position, orientation rows,
                             velocity, omega and angular momentum must track
  3. flight assertions       the real wreck must LEAVE THE GROUND and rotate
                             through more than one axis (the behaviour the
                             module exists to reproduce)
  4. launch ablation         a torque-only entry does NOT launch; the pure
                             linear up-axis kick is what does.  This is the
                             regression guard on the actual bug.
  5. settle predicate        FUN_00125CF0 whole-function differential
  6. sleep gate              driven through the REAL FUN_00123000: every
                             condition of the 0x00123412..0x001235ED block,
                             one violated at a time
  7. scrape                  FUN_00123FD0 @0x001248EA composed from the REAL
                             callees (FUN_001066A0 / FUN_00011640 /
                             FUN_00013C60 / FUN_001115C0 / FUN_001064B0) vs
                             b3_crash_scrape
  8. AT REST                 the retail wreck comes to a dead stop and stays
                             there; the harness wreck must do the same --
                             land, settle, sleep, and not drift or climb,
                             with aftertouch held as well.  This is the
                             regression guard on "the wreck bobbles into
                             space".

Usage: python3 tools/validate_crash_traj.py [--quick]
"""
import importlib.util
import math
import os
import struct
import subprocess
import sys

_here = os.path.dirname(os.path.abspath(__file__))
_root = os.path.dirname(_here)
sys.path.insert(0, _here)

_spec = importlib.util.spec_from_file_location(
    "ect", os.path.join(_here, "emulate_crash_traj.py"))
ect = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ect)

from unicorn.x86_const import (UC_X86_REG_EAX, UC_X86_REG_ECX,
                               UC_X86_REG_ESI)

VEHICLE = ect.VEHICLE
CTX0 = ect.CTX0
CTX1 = ect.CTX1
f2u = ect.f2u

DT = 1.0 / 60.0

PASS = 0
FAIL = 0


def check(name, ok, detail=""):
    global PASS, FAIL
    if ok:
        PASS += 1
        print("  ok   %s" % name)
    else:
        FAIL += 1
        print("  FAIL %s   %s" % (name, detail))


# ---------------------------------------------------------------------------
# the C side: a driver compiled straight against src/burnout3_crash.c
# ---------------------------------------------------------------------------
DRIVER_C = r'''
/* generated by tools/validate_crash_traj.py -- differential driver for the
   crash-entry kick and the crashed-path solver in src/burnout3_crash.c */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "burnout3_crash.h"
#include "burnout3_vehicle_sim.h"

/* the pipeline's ground hook: unused here, the wreck is in free flight */
int b3_ground_probe(float x, float y, float z, float* h, float n[3]) {
    (void)x; (void)y; (void)z;
    if (h) *h = 0.0f;
    if (n) { n[0] = 0.0f; n[1] = 1.0f; n[2] = 0.0f; }
    return -1;
}

static float g_num[256];
static char  g_key[256][40];
static int   g_n;

static float get(const char* k) {
    for (int i = 0; i < g_n; i++)
        if (!strcmp(g_key[i], k)) return g_num[i];
    fprintf(stderr, "missing key %s\n", k); exit(2);
}

static void load(const char* path) {
    FILE* f = fopen(path, "r");
    if (!f) { perror(path); exit(2); }
    char k[64]; double v;
    while (fscanf(f, "%39s %lf", k, &v) == 2) {
        strcpy(g_key[g_n], k); g_num[g_n] = (float)v; g_n++;
    }
    fclose(f);
}

static void read_frame(float m[4][4]) {
    char k[40];
    for (int r = 0; r < 4; r++)
        for (int c = 0; c < 4; c++) {
            sprintf(k, "frame_%d_%d", r, c);
            m[r][c] = get(k);
        }
}

int main(int argc, char** argv) {
    if (argc < 3) { fprintf(stderr, "usage: drv kick|traj state [n]\n");
                    return 2; }
    load(argv[2]);

    if (!strcmp(argv[1], "latch")) {
        /* the per-slot crash latch, FUN_0010DD20's LAB_0010E431 table */
        printf("%.9g %.9g %.9g %.9g\n",
               b3_crash_latch_duration(1, 0), b3_crash_latch_duration(1, 1),
               b3_crash_latch_duration(0, 0), b3_crash_latch_duration(0, 1));
        return 0;
    }

    if (!strcmp(argv[1], "kick")) {
        B3CrashVehicle v; memset(&v, 0, sizeof v);
        read_frame(v.frame);
        for (int i = 0; i < 4; i++) {
            char k[40];
            sprintf(k, "bbmax_%d", i); v.bbmax[i] = get(k);
            sprintf(k, "bbmin_%d", i); v.bbmin[i] = get(k);
        }
        v.mass = get("mass");
        v.asleep = 1;
        unsigned flags = (unsigned)get("flags");
        float mag = get("mag");
        if ((int)get("via_axis"))
            b3_crash_kick_axis(&v, flags, mag);
        else {
            int row = (int)get("axis_row");
            b3_crash_kick(&v, flags, mag, v.frame[row]);
        }
        printf("%.9g %.9g %.9g %.9g %.9g %.9g %d\n",
               v.imp[0], v.imp[1], v.imp[2],
               v.ang_imp[0], v.ang_imp[1], v.ang_imp[2], (int)v.asleep);
        return 0;
    }

    if (!strcmp(argv[1], "traj")) {
        int n = atoi(argv[3]);
        B3RigidBody rb; memset(&rb, 0, sizeof rb);
        read_frame(rb.frame);
        char k[40];
        for (int i = 0; i < 4; i++) {
            sprintf(k, "vel_%d", i);    rb.vel[i] = get(k);
            sprintf(k, "dir_%d", i);    rb.dir[i] = get(k);
            sprintf(k, "omega_%d", i);  rb.omega[i] = get(k);
            sprintf(k, "angmom_%d", i); rb.angmom[i] = get(k);
        }
        for (int i = 0; i < 3; i++) {
            sprintf(k, "iinv_%d", i);
            rb.inv_inertia_body[i][i] = get(k);
            for (int j = 0; j < 4; j++) {
                sprintf(k, "iw_%d_%d", i, j);
                rb.inv_inertia_world[i][j] = get(k);
            }
        }
        float mass = get("mass"), com = get("com_height");
        float dt = get("dt");
        B3CrashModeState s;
        memset(&s, 0, sizeof s);
        s.all_grounded = 0;
        s.all_airborne = 1;
        s.state211 = 0;
        s.settle_test = 0;
        s.asleep = 0;
        s.settle = 0;
        for (int f = 0; f < n; f++) {
            b3_crash_mode_frame(&rb, &s, mass, com, 1, dt);
            printf("%.9g %.9g %.9g  %.9g %.9g %.9g  %.9g %.9g %.9g  "
                   "%.9g %.9g %.9g  %.9g %.9g %.9g  %.9g %.9g %.9g  "
                   "%.9g %.9g %.9g\n",
                   rb.frame[3][0], rb.frame[3][1], rb.frame[3][2],
                   rb.frame[0][0], rb.frame[0][1], rb.frame[0][2],
                   rb.frame[1][0], rb.frame[1][1], rb.frame[1][2],
                   rb.frame[2][0], rb.frame[2][1], rb.frame[2][2],
                   rb.vel[0], rb.vel[1], rb.vel[2],
                   rb.omega[0], rb.omega[1], rb.omega[2],
                   rb.angmom[0], rb.angmom[1], rb.angmom[2]);
        }
        return 0;
    }

    /* THE WHOLE-SEQUENCE differential: the same crashed-path step, but
       driven one step per RENDERED frame with the dt series the real frame
       timer produced (period/divisor, evolving as the dilation writers
       fire).  Reports the APPARENT rotation -- the angle the shell turned
       between two rendered frames, which is the thing the eye sees. */
    if (!strcmp(argv[1], "seq")) {
        int n = atoi(argv[3]);
        B3RigidBody rb; memset(&rb, 0, sizeof rb);
        read_frame(rb.frame);
        char k[40];
        for (int i = 0; i < 4; i++) {
            sprintf(k, "vel_%d", i);    rb.vel[i] = get(k);
            sprintf(k, "dir_%d", i);    rb.dir[i] = get(k);
            sprintf(k, "omega_%d", i);  rb.omega[i] = get(k);
            sprintf(k, "angmom_%d", i); rb.angmom[i] = get(k);
        }
        for (int i = 0; i < 3; i++) {
            sprintf(k, "iinv_%d", i);
            rb.inv_inertia_body[i][i] = get(k);
            for (int j = 0; j < 4; j++) {
                sprintf(k, "iw_%d_%d", i, j);
                rb.inv_inertia_world[i][j] = get(k);
            }
        }
        float mass = get("mass"), com = get("com_height");
        B3CrashModeState s;
        memset(&s, 0, sizeof s);
        s.all_grounded = 0;
        s.all_airborne = 1;
        s.state211 = 0;
        s.settle_test = 0;
        s.asleep = 0;
        s.settle = 0;
        for (int f = 0; f < n; f++) {
            float prev[3][3];
            for (int r = 0; r < 3; r++)
                for (int c = 0; c < 3; c++) prev[r][c] = rb.frame[r][c];
            sprintf(k, "dt_%d", f);
            b3_crash_mode_frame(&rb, &s, mass, com, 1, get(k));
            /* angle of the rotation taking the previous body axes to the
               current ones: trace of prev . cur^T */
            float tr = 0.0f;
            for (int r = 0; r < 3; r++)
                for (int c = 0; c < 3; c++) tr += prev[r][c] * rb.frame[r][c];
            float cs = (tr - 1.0f) * 0.5f;
            if (cs > 1.0f) cs = 1.0f;
            if (cs < -1.0f) cs = -1.0f;
            printf("%.9g  %.9g %.9g %.9g  %.9g %.9g %.9g  %.9g %.9g %.9g  "
                   "%.9g %.9g %.9g  %.9g %.9g %.9g\n",
                   (float)acos(cs),
                   rb.frame[3][0], rb.frame[3][1], rb.frame[3][2],
                   rb.frame[0][0], rb.frame[0][1], rb.frame[0][2],
                   rb.frame[1][0], rb.frame[1][1], rb.frame[1][2],
                   rb.frame[2][0], rb.frame[2][1], rb.frame[2][2],
                   rb.omega[0], rb.omega[1], rb.omega[2]);
        }
        return 0;
    }

    /* FUN_00125CF0 differential */
    if (!strcmp(argv[1], "settle")) {
        unsigned char wc[8], ws[8], wd[8];
        int n = (int)get("wheel_count");
        char k[40];
        for (int i = 0; i < n && i < 8; i++) {
            sprintf(k, "wcontact_%d", i); wc[i] = (unsigned char)get(k);
            sprintf(k, "wsurface_%d", i); ws[i] = (unsigned char)get(k);
            sprintf(k, "wdamage_%d",  i); wd[i] = (unsigned char)get(k);
        }
        printf("%d\n", b3_crash_settle_test((int)get("chassis_contact"),
                                            (int)get("chassis_surface"),
                                            (int)get("check_wheels"), n,
                                            wc, ws, wd));
        return 0;
    }

    /* FUN_00123FD0 @0x001248EA scrape differential: report the force and
       torque the scrape adds to the accumulators */
    if (!strcmp(argv[1], "scrape")) {
        B3RigidBody rb; memset(&rb, 0, sizeof rb);
        read_frame(rb.frame);
        char k[40];
        for (int i = 0; i < 4; i++) {
            sprintf(k, "vel_%d", i);   rb.vel[i] = get(k);
            sprintf(k, "omega_%d", i); rb.omega[i] = get(k);
        }
        float pt[4];
        for (int i = 0; i < 3; i++) { sprintf(k, "pt_%d", i); pt[i] = get(k); }
        pt[3] = 1.0f;
        b3_crash_scrape(&rb, pt, get("mass"), (int)get("n_points"),
                        (int)get("full_strength"));
        printf("%.9g %.9g %.9g  %.9g %.9g %.9g\n",
               rb.force_acc[0], rb.force_acc[1], rb.force_acc[2],
               rb.torque_acc[0], rb.torque_acc[1], rb.torque_acc[2]);
        return 0;
    }

    /* the whole harness wreck: begin -> N x b3_wreck_update over flat
       ground, optionally with an aftertouch direction held every frame */
    if (!strcmp(argv[1], "wreck")) {
        int n = atoi(argv[3]);
        B3WreckState w;
        float pos[3] = {get("pos_0"), get("pos_1"), get("pos_2")};
        float vel[3] = {get("vel_0"), get("vel_1"), get("vel_2")};
        float bbmin[3] = {get("bbmin_0"), get("bbmin_1"), get("bbmin_2")};
        float bbmax[3] = {get("bbmax_0"), get("bbmax_1"), get("bbmax_2")};
        float cp[3] = {get("cp_0"), get("cp_1"), get("cp_2")};
        float cn[3] = {get("cn_0"), get("cn_1"), get("cn_2")};
        float rv[3] = {get("rv_0"), get("rv_1"), get("rv_2")};
        b3_wreck_begin_kick(&w, pos, get("heading"), vel, get("mass"),
                            bbmin, bbmax, cp, cn, rv,
                            (unsigned)get("corner"), get("mag_spin"),
                            get("mag_launch"));
        float iinv[3] = {get("iinv_0"), get("iinv_1"), get("iinv_2")};
        b3_wreck_set_inertia(&w, iinv);
        float ground = get("ground"), dt = get("dt");
        float ax = get("after_x"), az = get("after_z");
        int after_frames = (int)get("after_frames");
        int kicks = 0;
        for (int f = 0; f < n; f++) {
            if ((ax != 0.0f || az != 0.0f)
                && (after_frames <= 0 || f < after_frames)) {
                float l0[3] = {w.angmom[0], w.angmom[1], w.angmom[2]};
                b3_wreck_aftertouch(&w, ax, az);
                if (w.angmom[0] != l0[0] || w.angmom[1] != l0[1]
                    || w.angmom[2] != l0[2]) kicks++;
            }
            b3_wreck_update(&w, ground, dt);
            printf("%.9g %.9g %.9g  %.9g %.9g %.9g %.9g  %.9g %.9g %.9g  "
                   "%.9g %.9g %.9g  %.9g %d %d %d\n",
                   w.frame[3][0], w.frame[3][1], w.frame[3][2],
                   w.vel[0], w.vel[1], w.vel[2], w.vel[3],
                   w.omega[0], w.omega[1], w.omega[2],
                   w.frame[1][0], w.frame[1][1], w.frame[1][2],
                   w.settle, w.asleep, w.airborne, kicks);
        }
        return 0;
    }
    return 2;
}
'''


def build_driver(defines=(), tag=''):
    src = os.path.join(_root, 'build', 'crash_traj_drv.c')
    exe = os.path.join(_root, 'build', 'crash_traj_drv' + tag)
    os.makedirs(os.path.join(_root, 'build'), exist_ok=True)
    with open(src, 'w') as f:
        f.write(DRIVER_C)
    r = subprocess.run(['cc', '-O2', '-Isrc'] + list(defines)
                       + ['-o', exe, src,
                          'src/burnout3_crash.c', 'src/burnout3_vehicle_sim.c',
                          '-lm'], cwd=_root, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        return None
    return exe


def run_driver(exe, mode, state, extra=()):
    path = os.path.join(_root, 'build', 'crash_traj_state.txt')
    with open(path, 'w') as f:
        for k, v in state.items():
            f.write('%s %.9g\n' % (k, v))
    r = subprocess.run([exe, mode, path] + [str(e) for e in extra],
                       cwd=_root, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(r.stderr)
    return [[float(x) for x in line.split()]
            for line in r.stdout.strip().splitlines()]


# ---------------------------------------------------------------------------
# 1. crash-entry kick differential
# ---------------------------------------------------------------------------
KICK_CASES = [
    # name, flags, mag, via_axis, axis row, heading rows (yaw deg, roll deg)
    ("linear up launch  (0x10, 0.65)  0x0011C421", 0x10, 0.65, 0, 1, 0, 0),
    ("left corner spin  (0x08, 0.90)  0x0011C439", 0x08, 0.90, 0, 1, 0, 0),
    ("rear-left torque  (0x0A, 0.40)  0x00024F94", 0x0A, 0.40, 0, 1, 0, 0),
    ("rear-left torque  (0x0A, 0.30)  0x00025C8D", 0x0A, 0.30, 0, 1, 0, 0),
    ("front-left after  (0x09, 0.60)  0x001181B4", 0x09, 0.60, 0, 1, 0, 0),
    ("front-right after (0x05, 0.60)  0x001181E5", 0x05, 0.60, 0, 1, 0, 0),
    ("rear-right after  (0x06, 0.60)  0x00118241", 0x06, 0.60, 0, 1, 0, 0),
    ("grind kick        (0x04, 0.25)  0x00197376", 0x04, 0.25, 0, 1, 0, 0),
    ("forward kick      (0x80, 1.60)  0x00026B09", 0x80, 1.60, 0, 2, 0, 0),
    ("front kick        (0x01, 0.50)  0x0010ECA7", 0x01, 0.50, 0, 1, 0, 0),
    ("rear kick         (0x02, 0.50)  0x0010ECFD", 0x02, 0.50, 0, 1, 0, 0),
    ("yawed 37deg, rear-left 0x0A", 0x0A, 0.40, 0, 1, 37, 0),
    ("rolled 128deg (inverted -> roof arm) 0x0A", 0x0A, 0.40, 0, 1, 0, 128),
    ("rolled 200deg (inverted -> roof arm) 0x06", 0x06, 0.60, 0, 1, 25, 200),
    ("axis wrapper right row  (0x60, 0.50)", 0x60, 0.50, 1, 0, 0, 0),
    ("axis wrapper at row     (0x80, 1.60)", 0x80, 1.60, 1, 2, 0, 0),
    ("axis wrapper up row     (0x0A, 0.40)", 0x0A, 0.40, 1, 1, 0, 0),
    ("axis wrapper up row     (0x10, 0.65)", 0x10, 0.65, 1, 1, 19, 0),
]


def pose_rows(yaw_deg, roll_deg):
    """Orthonormal frame: yaw about y then roll about the at axis."""
    cy, sy = math.cos(math.radians(yaw_deg)), math.sin(math.radians(yaw_deg))
    at = [sy, 0.0, cy]
    right0 = [cy, 0.0, -sy]
    up0 = [0.0, 1.0, 0.0]
    cr, sr = math.cos(math.radians(roll_deg)), math.sin(math.radians(roll_deg))
    right = [right0[i] * cr + up0[i] * sr for i in range(3)]
    up = [-right0[i] * sr + up0[i] * cr for i in range(3)]
    return right, up, at


def run_kick_cases():
    print("\n1. crash-entry kick (FUN_00125100 / FUN_00125380 differential):")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return
    sim = ect.CrashTraj(dt=DT)
    pos = [12.0, 3.5, -47.0]
    for (name, flags, mag, via, row, yaw, roll) in KICK_CASES:
        right, up, at = pose_rows(yaw, roll)
        rows = [right + [0.0], up + [0.0], at + [0.0], pos + [1.0]]
        for r in range(4):
            for c in range(4):
                sim.wf(CTX0 + 16 * r + 4 * c, rows[r][c])
        # clear the impulse accumulators and put the body to sleep so the
        # wake side effect (veh+0x20E := 0) is observable
        for off in range(0x110, 0x130, 4):
            sim.wf(VEHICLE + off, 0.0)
        sim.wb(VEHICLE + 0x20E, 1)
        if via:
            sim.kick_axis(flags, mag)
        else:
            sim.kick(flags, mag, CTX0 + 0x10 * row)
        real = ([sim.vf(0x110 + 4 * i) for i in range(3)]
                + [sim.vf(0x120 + 4 * i) for i in range(3)]
                + [sim.vb(0x20E)])
        st = {}
        for r in range(4):
            for c in range(4):
                st['frame_%d_%d' % (r, c)] = rows[r][c]
        for i in range(4):
            st['bbmax_%d' % i] = sim.vf(0x1D0 + 4 * i)
            st['bbmin_%d' % i] = sim.vf(0x1E0 + 4 * i)
        st['mass'] = sim.vf(0x1F0)
        st['flags'] = flags
        st['mag'] = mag
        st['via_axis'] = via
        st['axis_row'] = row
        got = run_driver(exe, 'kick', st)[0]
        bad = []
        for i, lbl in enumerate(('imp.x', 'imp.y', 'imp.z',
                                 'L.x', 'L.y', 'L.z')):
            tol = max(1e-3, abs(real[i]) * 2e-5)
            if abs(got[i] - real[i]) > tol:
                bad.append("%s %.6g != %.6g" % (lbl, got[i], real[i]))
        if int(got[6]) != int(real[6]):
            bad.append("asleep %d != %d" % (int(got[6]), int(real[6])))
        check(name, not bad, "; ".join(bad))


# ---------------------------------------------------------------------------
# 2 + 3 + 4: the trajectories
# ---------------------------------------------------------------------------
def first_airborne_run(traj):
    """Index of the first frame after which the wreck stays airborne."""
    n = len(traj)
    i = n - 1
    while i > 0 and traj[i - 1]['airborne']:
        i -= 1
    return i


def traj_case(exe, label, scen, frames, window, row_budget):
    sim, speed, pre, traj = ect.SCENARIOS[scen](dt=DT, frames=frames)
    body = sim.export_body()
    start = first_airborne_run(traj)
    if start + window >= len(traj):
        window = len(traj) - start - 1
    seed = traj[start]
    st = {}
    rows = [seed['right'], seed['up'], seed['at'], seed['pos']]
    for r in range(4):
        for c in range(3):
            st['frame_%d_%d' % (r, c)] = rows[r][c]
        st['frame_%d_3' % r] = 1.0 if r == 3 else 0.0
    for i in range(3):
        st['vel_%d' % i] = seed['vel'][i]
        st['omega_%d' % i] = seed['omega'][i]
        st['angmom_%d' % i] = seed['angmom'][i]
        st['dir_%d' % i] = seed['dir'][i]
    st['vel_3'] = seed['speed']
    st['dir_3'] = seed['dir'][3]
    st['omega_3'] = 0.0
    st['angmom_3'] = 0.0
    for i in range(3):
        st['iinv_%d' % i] = body['iinv_%d' % i]
        for j in range(4):
            st['iw_%d_%d' % (i, j)] = seed['iinv_world'][i][j]
    st['mass'] = body['mass']
    st['com_height'] = body['com_height']
    st['dt'] = DT
    got = run_driver(exe, 'traj', st, extra=[window])

    worst_p = worst_v = worst_r = 0.0
    worst_L = 0.0
    for f in range(window):
        real = traj[start + 1 + f]
        g = got[f]
        worst_p = max(worst_p,
                      max(abs(g[i] - real['pos'][i]) for i in range(3)))
        worst_v = max(worst_v,
                      max(abs(g[12 + i] - real['vel'][i]) for i in range(3)))
        worst_r = max(worst_r,
                      max(max(abs(g[3 + i] - real['right'][i])
                              for i in range(3)),
                          max(abs(g[6 + i] - real['up'][i])
                              for i in range(3)),
                          max(abs(g[9 + i] - real['at'][i])
                              for i in range(3))))
        if f < 30:
            scale = max(1.0, max(abs(x) for x in real['angmom']))
            worst_L = max(worst_L,
                          max(abs(g[18 + i] - real['angmom'][i])
                              for i in range(3)) / scale)
    # first-step exactness pins the per-frame laws; the only thing left to
    # accumulate afterwards is the shared orthonormalizer branch (16.1)
    g0 = got[0]
    r0 = traj[start + 1]
    step_w = max(abs(g0[15 + i] - r0['omega'][i]) for i in range(3))
    step_r = max(max(abs(g0[3 + i] - r0['right'][i]) for i in range(3)),
                 max(abs(g0[6 + i] - r0['up'][i]) for i in range(3)),
                 max(abs(g0[9 + i] - r0['at'][i]) for i in range(3)))

    check("%s: %d frames, position tracks to %.2e m" % (label, window,
                                                        worst_p),
          worst_p < 1e-3)
    check("%s: %d frames, velocity tracks to %.2e m/s" % (label, window,
                                                          worst_v),
          worst_v < 1e-3)
    scale0 = max(1.0, max(abs(x) for x in r0['angmom']))
    step_L = max(abs(g0[18 + i] - r0['angmom'][i]) for i in range(3)) / scale0
    check("%s: angular momentum exact on the first crashed frame (%.2e)"
          % (label, step_L), step_L < 1e-5)
    # L is damped per world axis, so once the frames diverge L follows the
    # orientation residual; bound it by that budget rather than pretending
    check("%s: angular momentum tracks to %.2e (30 frames, relative)"
          % (label, worst_L), worst_L < max(1e-5, row_budget * 0.05))
    check("%s: omega exact on the first crashed frame (%.2e)"
          % (label, step_w), step_w < 1e-4)
    check("%s: per-step orientation residual %.2e (FUN_000FF270 branch)"
          % (label, step_r), step_r < 4e-3)
    check("%s: %d frames, orientation rows within %.3f" % (label, window,
                                                           worst_r),
          worst_r < row_budget,
          "budget %.3f -- accumulated orthonormalizer residual" % row_budget)
    return sim, speed, pre, traj


def seq_case(exe, label, seqfn, arm_impact, window=180, frames=300):
    """THE WHOLE-SEQUENCE DIFFERENTIAL.

    The three pieces (frame timer, crashed vehicle step, chase camera) are
    each verified in isolation elsewhere.  This asserts their COMPOSITION:
    the oracle runs one continuous session that, per RENDERED frame, ticks
    the real timer, steps the real crashed path at the dt that tick
    produced, and runs the real mode-2 camera on it.  The port is then
    driven with the SAME per-rendered-frame dt series and its
    apparent-rotation curve is diffed against the oracle's.
    """
    # the series is always long enough to contain the whole presentation
    # (the impact window alone is 15 + 126 rendered frames), so the branch
    # analysis below sees its real shape even under --quick, which only
    # shortens the frame-by-frame DIFF window.
    r = seqfn(frames=frames, arm_impact=arm_impact, camera=True)
    s = r['series']
    body = r['body']
    start = next((i for i, f in enumerate(s) if f['airborne']), 0)
    n = min(window, len(s) - start - 1)
    seed = s[start]
    st = {}
    rows = [seed['right'], seed['up'], seed['at'], seed['pos']]
    for row in range(4):
        for c in range(3):
            st['frame_%d_%d' % (row, c)] = rows[row][c]
        st['frame_%d_3' % row] = 1.0 if row == 3 else 0.0
    for i in range(3):
        st['vel_%d' % i] = seed['vel'][i]
        st['omega_%d' % i] = seed['omega'][i]
        st['angmom_%d' % i] = seed['angmom'][i]
        st['dir_%d' % i] = seed['dir'][i]
    st['vel_3'] = seed['speed']
    st['dir_3'] = seed['dir'][3]
    st['omega_3'] = st['angmom_3'] = 0.0
    for i in range(3):
        st['iinv_%d' % i] = body['iinv_%d' % i]
        for j in range(4):
            st['iw_%d_%d' % (i, j)] = seed['iinv_world'][i][j]
    st['mass'] = body['mass']
    st['com_height'] = body['com_height']
    for f in range(n):
        st['dt_%d' % f] = s[start + 1 + f]['dt']
    got = run_driver(exe, 'seq', st, extra=[n])

    worst_app = worst_pos = 0.0
    tot_real = tot_port = 0.0
    for f in range(n):
        real = s[start + 1 + f]
        g = got[f]
        worst_app = max(worst_app, abs(g[0] - real['apparent_rot']))
        worst_pos = max(worst_pos,
                        max(abs(g[1 + i] - real['pos'][i]) for i in range(3)))
        tot_real += real['apparent_rot']
        tot_port += g[0]
    check("%s: %d rendered frames, per-frame APPARENT rotation within "
          "%.2e rad (%.4f deg)" % (label, n, worst_app,
                                   math.degrees(worst_app)),
          worst_app < 2e-3)
    check("%s: total swept angle %.1f deg (port) vs %.1f deg (real)"
          % (label, math.degrees(tot_port), math.degrees(tot_real)),
          abs(tot_port - tot_real) < 0.05)
    check("%s: %d rendered frames, position tracks to %.2e m"
          % (label, n, worst_pos), worst_pos < 1e-3)
    return r


def run_sequence_cases(quick):
    """Section 8 -- the composition, and the two presentation branches."""
    print("\n8. THE WHOLE CRASH SEQUENCE, per RENDERED frame "
          "(real timer + real crashed step + real mode-2 camera):")
    exe = build_driver()
    if exe is None:
        return
    window = 60 if quick else 180
    for label, fn in (("wall 35 m/s", ect.seq_wall35),
                      ("car-vs-car fatal", ect.seq_slam)):
        plain = seq_case(exe, "%s, plain crash" % label, fn, False, window)
        # The armed branch's frame-by-frame window stops at the end of the
        # dilated phase (15 + 126 rendered frames).  Past it the shell runs
        # at dt = 1/60 with a fast multi-axis tumble, where the SHARED
        # b3_mat_orthonormalize takes the wrong FUN_000FF270 branch
        # (RE_NOTES 16.1, a src/burnout3_vehicle_sim.c hand-off item) and
        # the per-step orientation residual compounds.  That residual is
        # bounded by its own case in section 2; asserting it again here at
        # 180 frames would only re-measure someone else's open item.
        armed = seq_case(exe, "%s, big-hit armed" % label, fn, True,
                         min(window, 120))

        # --- the presentation branch, measured on the oracle --------------
        def stats(r):
            s = r['series']
            return (max(f['apparent_rot'] for f in s),
                    [f['divisor'] for f in s],
                    [f.get('cam_yaw', 0.0) for f in s],
                    [f.get('cam_pitch', 0.0) for f in s])
        p_peak, p_div, p_yaw, p_pitch = stats(plain)
        a_peak, a_div, a_yaw, a_pitch = stats(armed)

        check("%s: a plain crash holds divisor 5 for the whole flight"
              % label, set(p_div[1:]) == {5},
              "divisors seen: %s" % sorted(set(p_div[1:])))
        check("%s: the big-hit branch truncates to full speed" % label,
              a_div.count(6) == 126 and a_div[-1] == 1,
              "div6 frames %d, last %d" % (a_div.count(6), a_div[-1]))
        # THE HEADLINE: what the eye sees per rendered frame
        check("%s: plain crash tumbles at %.2f deg/frame peak (stately)"
              % (label, math.degrees(p_peak)), math.degrees(p_peak) < 3.0)
        # measured: 4.9x for the 35 m/s wall (14.5 rad/s of entry spin),
        # 2.0x for the car-vs-car fatal (8.2 rad/s)
        check("%s: the truncated branch peaks at %.2f deg/frame -- %.1fx "
              "faster" % (label, math.degrees(a_peak), a_peak / p_peak),
              a_peak > p_peak * 1.8)
        # THE CAMERA: n = floor(60*dt + 0.5) is 0 at divisor 5 and 6, so
        # every blend is 1 - x^0 = 0 and the angles HOLD (FUN_0015E550
        # @0x0015E5DC).  This is the recovered crash-camera behaviour.
        dil = [i for i, d in enumerate(p_div) if d != 1]
        yaw_sw = max(abs(p_yaw[i] - p_yaw[dil[0]]) for i in dil)
        pit_sw = max(abs(p_pitch[i] - p_pitch[dil[0]]) for i in dil)
        check("%s: the crash camera HOLDS its yaw through the dilated "
              "window (%.4f deg of drift)" % (label, yaw_sw), yaw_sw < 1e-3)
        check("%s: ... and its pitch (%.4f deg of drift)"
              % (label, pit_sw), pit_sw < 1e-3)
        # and the truncated branch is exactly where the camera starts to
        # swing -- the regression guard on the old always-armed harness
        a_dil = [i for i, d in enumerate(a_div) if d != 1]
        a_full = [i for i, d in enumerate(a_div) if d == 1 and i > a_dil[-1]]
        if a_full:
            sw = max(abs(a_yaw[i] - a_yaw[a_dil[-1]]) for i in a_full)
            check("%s: once truncated, the camera swings %.1f deg of yaw"
                  % (label, sw), sw > 20.0)


def run_traj_cases(quick):
    print("\n2. crashed-path 6DOF trajectory "
          "(FUN_0011BE50 crashed branch -> FUN_00123000, real vs port):")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return None
    frames = 150 if quick else 300
    window = 120 if quick else 260
    out = {}
    # the slam tumbles on three axes, so the shared orthonormalizer's
    # data-dependent branch (RE_NOTES 16.1) accumulates ~2.6e-3 per frame;
    # the wall is a single-axis somersault where it agrees exactly.
    out['slam'] = traj_case(exe, "car-vs-car fatal slam", 'slam',
                            frames, window, 0.30)
    out['wall'] = traj_case(exe, "40 m/s head-on wall", 'wall',
                            frames, window, 0.01)
    return out


def run_flight_cases(runs, quick):
    print("\n3. the wreck must LEAVE THE GROUND and tumble:")
    # min axes: the head-on wall entry uses corner flags 0x02 (rear only, the
    # FUN_0010DD20 0x0010E40F shape), so its torque is a pure end-over-end
    # pitch -- one axis is CORRECT there.  The car-vs-car entry uses a real
    # corner (0x0A rear-left, 0x00024F94) and must tumble on two.
    for label, key, min_axes in (("car-vs-car fatal slam", 'slam', 2),
                                 ("40 m/s head-on wall", 'wall', 1)):
        sim, speed, pre, traj = runs[key]
        y0 = pre['pos'][1]
        rise = max(t['pos'][1] for t in traj) - y0
        vy0 = traj[0]['vel'][1]
        air = sum(1 for t in traj if t['airborne'])
        # rotation accumulated about each world axis
        rot = [0.0, 0.0, 0.0]
        for t in traj[:120]:
            for i in range(3):
                rot[i] += abs(t['omega'][i]) * DT
        axes = sum(1 for r in rot if r > 1.0)
        turns = math.sqrt(sum(r * r for r in rot)) / (2 * math.pi)
        check("%s: launch velocity %.2f m/s upward" % (label, vy0),
              vy0 > 4.0, "expected the pure-linear up kick (10 * mag)")
        check("%s: rises %.2f m off the ground" % (label, rise),
              rise > 1.0, "the wreck never leaves the ground")
        check("%s: %d/%d frames with no wheel on the ground"
              % (label, air, len(traj)), air > len(traj) // 4)
        check("%s: rotates through %d axes (%.1f, %.1f, %.1f rad)"
              % (label, axes, rot[0], rot[1], rot[2]), axes >= min_axes,
              "expected at least %d rotating axes" % min_axes)
        check("%s: turns over %.2f times in 2 s" % (label, turns),
              turns > 1.0, "a wreck that does not rotate is a slide")

    print("\n4. launch ablation (the regression guard on the actual bug):")
    sim, speed, pre, traj = ect.SCENARIOS['spin_only'](
        dt=DT, frames=90 if quick else 150)
    y0 = pre['pos'][1]
    vy0 = traj[0]['vel'][1]
    rise_spin = max(t['pos'][1] for t in traj) - y0
    check("torque-only entry: no launch velocity (%.2f m/s)" % vy0,
          vy0 < 1.0,
          "the corner torque alone must not produce upward velocity")
    _, _, pre2, traj2 = runs['slam']
    rise_full = max(t['pos'][1] for t in traj2) - pre2['pos'][1]
    check("linear kick adds %.2f m of height (%.2f -> %.2f)"
          % (rise_full - rise_spin, rise_spin, rise_full),
          rise_full > rise_spin + 0.4,
          "the pure-linear up-axis kick is the launch")


# ---------------------------------------------------------------------------
# 5. FUN_00125CF0 -- the settle predicate, whole-function differential
# ---------------------------------------------------------------------------
F_25CF0 = 0x00125CF0
F_23000 = 0x00123000
F_1066A0 = 0x001066A0
F_11640 = 0x00011640
F_13C60 = 0x00013C60
F_115C0 = 0x000115C0
F_1064B0 = 0x001064B0

# vehicle byte offsets FUN_00125CF0 reads
OFF_CHASSIS_CONTACT = 0x212        # a contact was recorded this frame
OFF_CHASSIS_SURFACE = 0x190        # its surface byte
OFF_WHEEL_SURFACE = 0x8D0          # + i * 0xC0
OFF_WHEEL_CONTACT = 0x8D3          # + i * 0xC0
OFF_WHEEL_DAMAGE = 0x4AC           # ctx1 + i

SETTLE_CASES = [
    # name, arg, chassis contact, chassis surface, per-wheel (contact, surf,
    # damage) for 4 wheels
    ("chassis contact on road (0x212=1, 0x190=0x01)",
     1, 1, 0x01, [(0, 0, 0)] * 4),
    ("chassis contact on a surface > 0x20 (0x190=0x40)",
     1, 1, 0x40, [(0, 0, 0)] * 4),
    ("chassis contact at the limit (0x190=0x20)",
     1, 1, 0x20, [(0, 0, 0)] * 4),
    ("no contact, no wheels down",
     1, 0, 0x01, [(0, 0, 0)] * 4),
    ("wheel 2 down on road, arg = 1",
     1, 0, 0x40, [(0, 0, 0), (0, 0, 0), (1, 0x02, 0), (0, 0, 0)]),
    ("wheel 2 down on road, arg = 0 (the wheel arm is gated off)",
     0, 0, 0x40, [(0, 0, 0), (0, 0, 0), (1, 0x02, 0), (0, 0, 0)]),
    ("wheel 2 down but DETACHED (damage state 3)",
     1, 0, 0x40, [(0, 0, 0), (0, 0, 0), (1, 0x02, 3), (0, 0, 0)]),
    ("wheel 3 down on a surface > 0x20",
     1, 0, 0x40, [(0, 0, 0)] * 3 + [(1, 0x77, 0)]),
    ("all four wheels down on road",
     1, 0, 0x40, [(1, 0x01, 0)] * 4),
]


def run_settle_cases():
    print("\n5. settle predicate (FUN_00125CF0 differential):")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return
    sim = ect.CrashTraj(dt=DT)
    for (name, arg, cc, cs, wheels) in SETTLE_CASES:
        sim.wb(VEHICLE + OFF_CHASSIS_CONTACT, cc)
        sim.wb(VEHICLE + OFF_CHASSIS_SURFACE, cs)
        sim.wb(VEHICLE + 0x1169, len(wheels))
        for i, (wc, ws, wd) in enumerate(wheels):
            sim.wb(VEHICLE + OFF_WHEEL_CONTACT + i * 0xC0, wc)
            sim.wb(VEHICLE + OFF_WHEEL_SURFACE + i * 0xC0, ws)
            sim.wb(CTX1 + OFF_WHEEL_DAMAGE + i, wd)
        sim.call(F_25CF0, stack_args=[arg],
                 regs={UC_X86_REG_ESI: VEHICLE})
        real = sim.uc.reg_read(UC_X86_REG_EAX) & 0xFF
        st = {'chassis_contact': cc, 'chassis_surface': cs,
              'check_wheels': arg, 'wheel_count': len(wheels)}
        for i, (wc, ws, wd) in enumerate(wheels):
            st['wcontact_%d' % i] = wc
            st['wsurface_%d' % i] = ws
            st['wdamage_%d' % i] = wd
        got = int(run_driver(exe, 'settle', st)[0][0])
        check("%s -> %d" % (name, real), got == real,
              "port says %d, FUN_00125CF0 says %d" % (got, real))
    # leave the struct clean for the sections after this one
    sim.wb(VEHICLE + OFF_CHASSIS_CONTACT, 0)


# ---------------------------------------------------------------------------
# 6. the sleep gate, driven through the REAL FUN_00123000
# ---------------------------------------------------------------------------
def _sleep_setup(sim, **over):
    """Put the real vehicle in the state the sleep block wants, then let the
    caller violate one condition at a time."""
    sim.wb(VEHICLE + 0x210, 1)            # crash mode
    # veh+0x211 must be 0: FUN_00109560 @0x00109592 clears the sleep byte
    # every step while it is set, so a body in that state never stays asleep
    sim.wb(VEHICLE + 0x211, over.get('state211', 0))
    sim.wb(VEHICLE + 0x20E, 0)            # awake
    sim.wb(VEHICLE + 0x116B, 0)
    sim.wb(VEHICLE + 0x1354, over.get('settle', 20))
    sim.wb(VEHICLE + 0x212, over.get('state212', 1))
    sim.wb(VEHICLE + OFF_CHASSIS_SURFACE, 0x01)
    # velocity / speed: the settle branch tests +0xBC
    speed = over.get('speed', 0.2)
    for i in range(3):
        sim.wf(VEHICLE + 0xB0 + 4 * i, 0.0)
    sim.wf(VEHICLE + 0xB0, speed)
    sim.wf(VEHICLE + 0xBC, speed)
    # angular momentum / omega
    w = over.get('omega', 0.1)
    for i in range(3):
        sim.wf(VEHICLE + 0xD0 + 4 * i, 0.0)
        sim.wf(VEHICLE + 0xE0 + 4 * i, 0.0)
    sim.wf(VEHICLE + 0xD0, w)
    # veh+0x170: the recorded contact axis, along the body up row
    for i in range(4):
        sim.wf(VEHICLE + 0x170 + 4 * i, 0.0)
    sim.wf(VEHICLE + 0x170 + 4, over.get('axis', 1.0))
    # the kick stamp the clock has to be past (0x00123564 compares the
    # global clock DAT_0060EA20 with ctx1+0xFFC)
    sim.wf(ect.ep.G_CLOCK, 10.0)
    sim.wf(CTX1 + 0xFFC, over.get('stamp', 0.0))
    # wheels: grounded on road so FUN_00125CF0's wheel arm is happy too
    ny = over.get('wheel_normal_y', 1.0)
    up_index = over.get('wheel_up_index', -1)
    for i in range(4):
        wc = 0 if i == up_index else over.get('wheel_contact', 1)
        sim.wb(VEHICLE + OFF_WHEEL_CONTACT + i * 0xC0, wc)
        sim.wb(VEHICLE + OFF_WHEEL_SURFACE + i * 0xC0, 0x01)
        sim.wb(CTX1 + OFF_WHEEL_DAMAGE + i, 0)
        # wheel+0x20 contact normal / wheel+0xB3 contact flag: the arm the
        # sleep gate uses when there is no chassis contact
        for j in range(4):
            sim.wf(VEHICLE + 0x840 + i * 0xC0 + 4 * j, 0.0)
        sim.wf(VEHICLE + 0x840 + i * 0xC0 + 4, ny)   # wheel+0x20 normal.y
        # (wheel+0x20 + 0x93 IS veh+0x8D3 + i*0xC0, already written above)


SLEEP_CASES = [
    ("every gate satisfied -> sleeps", {}, 1),
    ("speed 0.6 (>= 0.5, 0x00123518)", {'speed': 0.6}, 0),
    ("|omega| 0.6 -> |omega|^2 0.36 (>= 0.25, DAT_005A80B8)",
     {'omega': 0.6}, 0),
    ("|omega| 0.49 -> |omega|^2 0.24 (< 0.25)", {'omega': 0.49}, 1),
    ("settle counter 4 (5 after the increment, not > 5 [byte 0x003EBF88])",
     {'settle': 4}, 0),
    ("settle counter 5 (6 after the increment, > 5)", {'settle': 5}, 1),
    ("no chassis contact, wheels level (the 0x00123662 arm)",
     {'state212': 0}, 1),
    ("no chassis contact, a contacting wheel's normal off the up row by "
     "more than 0.98 (and one wheel up, so all_grounded cannot carry it)",
     {'state212': 0, 'wheel_normal_y': 0.90, 'wheel_up_index': 3}, 0),
    ("clock behind the kick stamp (0x00123564)", {'stamp': 1e6}, 0),
    ("contact axis off every body axis and a wheel up (0x0012357F)",
     {'axis': 0.5, 'wheel_contact': 0}, 0),
    ("veh+0x211 set -> FUN_00109560 @0x00109592 wakes it again",
     {'state211': 1}, 0),
]


def run_sleep_cases():
    print("\n6. sleep gate (through the REAL FUN_00123000 crash solver):")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return
    sim = ect.CrashTraj(dt=DT)
    # DAT_005A80B8 is BSS: the CRT static-initialiser thunk at 0x002BA7A0
    # (entry 0x003BDE84 of the init table) copies [0x003B1730] into it at
    # startup, which the emulator never runs -- so run the REAL thunk and
    # check what it installs.  This closes RE_NOTES 16.1's "[?] BSS, no
    # static writer" on the sleep limit.
    sim.wf(0x005A80B8, 0.0)
    sim.call(0x002BA7A0)
    limit = sim.rf(0x005A80B8)
    check("DAT_005A80B8 = %.6g after the real static initialiser 0x002BA7A0"
          % limit, abs(limit - 0.25) < 1e-9,
          "expected 0.25 = [0x003B1730]")
    check("the port's B3_SLEEP_OMEGA2_LIMIT matches it",
          abs(limit - _c_omega2_limit()) < 1e-9)
    for (name, over, want) in SLEEP_CASES:
        _sleep_setup(sim, **over)
        sim.call(F_23000, stack_args=[f2u(DT)],
                 regs={UC_X86_REG_ECX: VEHICLE})
        real = sim.vb(0x20E)
        check("%s (real veh+0x20E = %d)" % (name, real), real == want,
              "expected %d" % want)
        # and the C mirror of the same gate, through b3_crash_mode_frame
        st = dict(over)
        got = _c_sleep(exe, over)
        check("   port agrees (%d)" % got, got == real,
              "port %d != real %d" % (got, real))
        del st


def _c_omega2_limit():
    """B3_SLEEP_OMEGA2_LIMIT as the compiler sees it."""
    src = os.path.join(_root, 'build', 'crash_limit_drv.c')
    exe = os.path.join(_root, 'build', 'crash_limit_drv')
    with open(src, 'w') as f:
        f.write('#include <stdio.h>\n#include "burnout3_crash.h"\n'
                'int b3_ground_probe(float x, float y, float z, float* h,'
                ' float n[3]) { (void)x;(void)y;(void)z;(void)h;(void)n;'
                ' return -1; }\n'
                'int main(void){printf("%.9g\\n", B3_SLEEP_OMEGA2_LIMIT);'
                'return 0;}\n')
    r = subprocess.run(['cc', '-O2', '-Isrc', '-o', exe, src, '-lm'],
                       cwd=_root, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(r.stderr)
    return float(subprocess.run([exe], cwd=_root, capture_output=True,
                                text=True).stdout.strip())


def _c_sleep(exe, over):
    """b3_crash_mode_frame's own gate under the same inputs."""
    src = os.path.join(_root, 'build', 'crash_sleep_drv.c')
    exe2 = os.path.join(_root, 'build', 'crash_sleep_drv')
    if not os.path.exists(exe2) or (os.path.getmtime(exe2)
                                    < os.path.getmtime(os.path.join(
                                        _root, 'src', 'burnout3_crash.c'))):
        with open(src, 'w') as f:
            f.write(SLEEP_DRIVER_C)
        r = subprocess.run(['cc', '-O2', '-Isrc', '-o', exe2, src,
                            'src/burnout3_crash.c',
                            'src/burnout3_vehicle_sim.c', '-lm'],
                           cwd=_root, capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(r.stderr)
    args = [exe2,
            '%g' % over.get('speed', 0.2),
            '%g' % over.get('omega', 0.1),
            '%d' % over.get('settle', 20),
            '%d' % over.get('state212', 1),
            '%g' % over.get('axis', 1.0),
            '%d' % (0 if over.get('stamp', 0.0) > 1.0 else 1),
            '%d' % (0 if over.get('wheel_up_index', -1) >= 0
                    else over.get('wheel_contact', 1)),
            '%d' % over.get('state211', 0),
            '%g' % over.get('wheel_normal_y', 1.0),
            '%d' % over.get('wheel_up_index', -1)]
    r = subprocess.run(args, cwd=_root, capture_output=True, text=True)
    return int(r.stdout.strip())


SLEEP_DRIVER_C = r'''
/* generated by tools/validate_crash_traj.py -- the C side of the sleep gate */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "burnout3_crash.h"
int b3_ground_probe(float x, float y, float z, float* h, float n[3]) {
    (void)x; (void)y; (void)z; if (h) *h = 0.0f;
    if (n) { n[0] = 0; n[1] = 1; n[2] = 0; } return -1;
}
int main(int argc, char** argv) {
    if (argc < 11) return 2;
    B3RigidBody rb; memset(&rb, 0, sizeof rb);
    rb.frame[0][0] = rb.frame[1][1] = rb.frame[2][2] = rb.frame[3][3] = 1.0f;
    for (int i = 0; i < 3; i++) rb.inv_inertia_body[i][i] =
        rb.inv_inertia_world[i][i] = 0.001f;
    rb.vel[0] = (float)atof(argv[1]);
    rb.vel[3] = (float)atof(argv[1]);
    rb.omega[0] = (float)atof(argv[2]);
    B3CrashModeState s; memset(&s, 0, sizeof s);
    s.settle = (unsigned char)atoi(argv[3]);
    s.state212 = atoi(argv[4]);
    s.contact_normal[1] = (float)atof(argv[5]);
    s.clock_after_stamp = atoi(argv[6]);
    s.all_grounded = atoi(argv[7]);
    s.settle_test = 1;
    s.state211 = atoi(argv[8]);
    static float wn[4][4];
    static unsigned char wc[4];
    int up_index = atoi(argv[10]);
    for (int i = 0; i < 4; i++) {
        wn[i][1] = (float)atof(argv[9]);
        wc[i] = (unsigned char)(i == up_index ? 0 : 1);
    }
    s.wheel_count = 4;
    s.wheel_normal = (const float (*)[4])wn;
    s.wheel_contact = wc;
    b3_crash_mode_frame(&rb, &s, 1500.0f, 0.0f, 1, 1.0f / 60.0f);
    printf("%d\n", (int)s.asleep);
    return 0;
}
'''


# ---------------------------------------------------------------------------
# 7. the scrape -- FUN_00123FD0 @0x001248EA composed from the REAL callees
# ---------------------------------------------------------------------------
SCRAPE_CASES = [
    # name, contact point offset from the body origin, velocity, omega
    ("sliding forward, contact under the nose",
     (0.9, -0.6, 1.8), (12.0, 0.0, 3.0), (0.0, 0.0, 0.0)),
    ("sliding sideways, contact under the tail",
     (-0.9, -0.6, -1.8), (1.0, -0.5, 9.0), (0.2, 0.4, -0.1)),
    ("slow crawl with spin",
     (0.4, -0.7, 0.2), (0.3, 0.0, -0.2), (0.0, 1.5, 0.0)),
]


def run_scrape_cases():
    print("\n7. crashed-path scrape (FUN_00123FD0 @0x001248EA, real callees):")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return
    sim = ect.CrashTraj(dt=DT)
    mass = sim.vf(0x1F0)
    for (name, off, vel, omega) in SCRAPE_CASES:
        rows = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0],
                [3.0, 1.0, -8.0]]
        for r in range(4):
            for c in range(4):
                sim.wf(CTX0 + 16 * r + 4 * c,
                       rows[r][c] if c < 3 else (1.0 if r == 3 else 0.0))
        for i in range(3):
            sim.wf(VEHICLE + 0xB0 + 4 * i, vel[i])
            sim.wf(VEHICLE + 0xD0 + 4 * i, omega[i])
        speed = math.sqrt(sum(v * v for v in vel))
        sim.wf(VEHICLE + 0xBC, speed)
        pt = [rows[3][i] + off[i] for i in range(3)]
        # clear the accumulators FUN_001064B0 adds into
        for i in range(4):
            sim.wf(VEHICLE + 0xF0 + 4 * i, 0.0)
            sim.wf(VEHICLE + 0x100 + 4 * i, 0.0)
        # scratch buffers inside the emulated address space
        PT = ect.ep.SOUP_REC + 0x800
        V = PT + 0x20
        OUT = PT + 0x40
        for i in range(3):
            sim.wf(PT + 4 * i, pt[i])
        sim.wf(PT + 12, 1.0)
        # The REAL call chain, in FUN_00123FD0's order.  FUN_00013C60 and
        # FUN_001115C0 pass their scalar in XMM0, which this harness cannot
        # set/read, so those two links are the arithmetic the instruction
        # stream spells out (dot with the frame's RIGHT row; multiply by
        # (|dot| + 1) * mass * wheel_count * -0.75); the vector they operate
        # on and the two ends of the chain -- the point velocity and the
        # force-at-point application -- are the real functions.
        sim.call(F_1066A0, stack_args=[PT],
                 regs={UC_X86_REG_EAX: V, UC_X86_REG_ECX: VEHICLE})
        sim.call(F_11640, regs={UC_X86_REG_EAX: V})          # normalize
        vhat = [sim.rf(V + 4 * i) for i in range(4)]
        dot = sum(vhat[i] * rows[0][i] for i in range(3))    # FUN_00013C60
        f = (abs(dot) + 1.0) * mass * 4 * -0.75              # 0x3B17EC
        for i in range(4):
            sim.wf(OUT + 4 * i, vhat[i] * f)                 # FUN_001115C0
        sim.call(F_1064B0, stack_args=[PT],
                 regs={UC_X86_REG_EAX: OUT, UC_X86_REG_ESI: VEHICLE})
        real = ([sim.vf(0xF0 + 4 * i) for i in range(3)]
                + [sim.vf(0x100 + 4 * i) for i in range(3)])
        st = {}
        for r in range(4):
            for c in range(4):
                st['frame_%d_%d' % (r, c)] = (rows[r][c] if c < 3
                                              else (1.0 if r == 3 else 0.0))
        for i in range(3):
            st['vel_%d' % i] = vel[i]
            st['omega_%d' % i] = omega[i]
            st['pt_%d' % i] = pt[i]
        st['vel_3'] = speed
        st['omega_3'] = 0.0
        st['mass'] = mass
        st['n_points'] = 4
        st['full_strength'] = 1
        got = run_driver(exe, 'scrape', st)[0]
        bad = []
        for i, lbl in enumerate(('F.x', 'F.y', 'F.z', 'T.x', 'T.y', 'T.z')):
            tol = max(1e-2, abs(real[i]) * 1e-5)
            if abs(got[i] - real[i]) > tol:
                bad.append("%s %.6g != %.6g" % (lbl, got[i], real[i]))
        check("%s" % name, not bad, "; ".join(bad))


# ---------------------------------------------------------------------------
# 8. AT REST -- the retail wreck stops dead, and so must the harness wreck
# ---------------------------------------------------------------------------
def run_rest_cases(quick):
    print("\n8. at rest -- the REAL crashed path runs to quiescence:")
    frames = 400 if quick else 900
    sim = ect.CrashTraj(dt=DT)
    for _ in range(120):
        sim.frame(0.35, 0.0, 0.0, 0)
    pre = sim.capture6()
    # a gentle corner flick with no launch: the car stays on its wheels, so
    # the real machine's own suspension can bring it to rest
    sim.enter_crash(ect.KICK_REAR | ect.KICK_LEFT, 0.10, None)
    traj = [sim.crashed_frame() for _ in range(frames)]
    tail = traj[len(traj) // 2:]
    speeds = [math.sqrt(sum(v * v for v in t['vel'])) for t in tail]
    ys = [t['pos'][1] for t in tail]
    drift = max(ys) - min(ys)
    check("real wreck stops dead: |v| <= %.2e m/s over the last %d frames"
          % (max(speeds), len(tail)), max(speeds) < 1e-3)
    check("real wreck holds its height: %.2e m of drift" % drift,
          drift < 1e-3)
    # the settle counter is a BYTE and wraps -- it is never saturated
    counts = [t['settle'] for t in traj]
    check("settle counter runs and wraps as a byte (max %d, wraps %d)"
          % (max(counts), sum(1 for a, b in zip(counts, counts[1:])
                              if b < a)),
          max(counts) == 255 and any(b < a for a, b in zip(counts,
                                                           counts[1:])))
    # and it never sleeps, because FUN_0011BE50's crashed path never records
    # a chassis contact -- the gate at 0x00123414
    check("no chassis contact on the crashed path -> veh+0x20E stays 0",
          all(t['asleep'] == 0 for t in traj)
          and all(t['crashmode'] != 0 for t in traj))

    print("\n   the HARNESS wreck: launch, tumble, land, REST:")
    exe = build_driver()
    if exe is None:
        check("build the C driver", False, "compilation failed")
        return
    base = {
        'pos_0': 0.0, 'pos_1': 10.0, 'pos_2': 0.0,
        'vel_0': 0.0, 'vel_1': 0.0, 'vel_2': -32.0,
        'bbmin_0': -0.95, 'bbmin_1': -0.35, 'bbmin_2': -2.1,
        'bbmax_0': 0.95, 'bbmax_1': 1.15, 'bbmax_2': 2.1,
        'cp_0': 0.6, 'cp_1': 9.7, 'cp_2': -2.0,
        'cn_0': 0.0, 'cn_1': 0.0, 'cn_2': 1.0,
        'rv_0': 0.0, 'rv_1': 0.0, 'rv_2': -32.0,
        'heading': 0.0, 'mass': 1500.0,
        'corner': 0x0A, 'mag_spin': 0.40, 'mag_launch': 0.65,
        'iinv_0': 0.0008, 'iinv_1': 0.0011, 'iinv_2': 0.0013,
        'ground': 10.0, 'dt': DT, 'after_x': 0.0, 'after_z': 0.0,
        'after_frames': 0,
    }
    n = 600 if quick else 1200
    rows = run_driver(exe, 'wreck', base, extra=[n])
    ys = [r[1] for r in rows]
    peak = max(ys)
    launch_vy = rows[0][4]
    # the arc
    check("harness wreck launches (%.2f m/s up, peak %+.2f m over the road)"
          % (launch_vy, peak - base['ground']), launch_vy > 1.0
          and peak - base['ground'] > 1.0)
    upy = [r[11] for r in rows]
    check("stays right way up on frame 1 (up.y %+.3f -- the mirrored basis "
          "used to be flipped by the orthonormalizer)" % upy[0], upy[0] > 0.5)
    turned = sum(1 for u in upy if u < 0.5)
    check("tumbles (%d frames with the roof off vertical)" % turned,
          turned > 5)
    # the rest
    # driver columns: 0-2 pos, 3-6 vel(+speed), 7-9 omega, 10-12 up row,
    # 13 settle, 14 asleep, 15 airborne
    tail = rows[len(rows) * 3 // 4:]
    tail_y = [r[1] for r in tail]
    tail_sp = [r[6] for r in tail]
    tail_w = [math.sqrt(r[7] ** 2 + r[8] ** 2 + r[9] ** 2) for r in tail]
    drift = max(tail_y) - min(tail_y)
    horiz = max(abs(tail[-1][0] - tail[0][0]), abs(tail[-1][2] - tail[0][2]))
    check("comes to rest: %.4f m of height jitter over the last %d frames"
          % (drift, len(tail)), drift < 0.05)
    check("stays put: %.4f m of horizontal travel over the last %d frames"
          % (horiz, len(tail)), horiz < 0.15,
          "this shell ends on its SIDE, where the box has two contact "
          "corners and rocks; the upright case below is the tight one")
    # |v| under the settle gate's 1.0 (0x00123346) and the rocking of a
    # shell lying on its edge well under a rad/s -- it passed the sleep
    # gate's |w|^2 < 0.25 when it slept, below.
    check("under the retail settle limit: |v| %.3f < 1.0 (0x00123346), "
          "|w| %.3f rad/s" % (max(tail_sp), max(tail_w)),
          max(tail_sp) < 1.0 and max(tail_w) < 1.0)
    # a wreck that lands on its wheels is the case with the tight bounds:
    # it must sleep and stop dead
    up_rest = dict(base)
    up_rest['vel_2'] = -12.0
    up_rest['rv_2'] = -12.0
    up_rest['mag_spin'] = 0.10
    up_rest['mag_launch'] = 0.0
    rows_u = run_driver(exe, 'wreck', up_rest, extra=[n])
    tu = rows_u[len(rows_u) * 3 // 4:]
    ju = max(r[1] for r in tu) - min(r[1] for r in tu)
    hu = max(abs(tu[-1][0] - tu[0][0]), abs(tu[-1][2] - tu[0][2]))
    check("landing on its wheels: %.4f m of height jitter, %.4f m of travel, "
          "upright (up.y %+.3f)" % (ju, hu, tu[-1][11]),
          ju < 0.05 and hu < 0.01 and tu[-1][11] > 0.9)
    check("landing on its wheels: ASLEEP (veh+0x20E semantics) and it stays "
          "asleep", int(tu[-1][14]) == 1
          and all(int(r[14]) == 1 for r in tu))
    # THE bug: no upward creep once it is down
    landed = None
    for i, r in enumerate(rows):
        if i > 60 and int(r[15]) == 0 and abs(r[4]) < 0.5:
            landed = i
            break
    if landed is None:
        landed = len(rows) // 2
    climb = max(ys[landed:]) - ys[landed]
    check("never climbs after landing (%+.4f m from frame %d on)"
          % (climb, landed), climb < 0.05,
          "this is the 'bobbles into space' regression guard")

    # ... and with AFTERTOUCH HELD.  How high a wreck flies under a held
    # direction is not a free parameter: the retail shaper fires one 0.6
    # corner torque kick per frame with no cooldown, so the real machine
    # itself throws the shell metres into the air.  Measure that first and
    # hold the port to the same band.
    real_sim = ect.CrashTraj(dt=DT)
    for _ in range(120):
        real_sim.frame(0.35, 0.0, 0.0, 0)
    ry0 = real_sim.capture6()['pos'][1]
    real_sim.enter_crash(ect.KICK_REAR | ect.KICK_LEFT, 0.10, None)
    rt = []
    for _ in range(300):
        # FUN_00118410 @0x001181B4: flags 9, mag 0.6, axis = the up row
        real_sim.kick(0x09, 0.60, real_sim.frame_row(1))
        rt.append(real_sim.crashed_frame())
    real_peak = max(t['pos'][1] for t in rt) - ry0
    held = dict(base)
    held['after_x'] = 1.0
    rows2 = run_driver(exe, 'wreck', held, extra=[n])
    peak2 = max(r[1] for r in rows2) - base['ground']
    check("aftertouch held: the REAL machine throws the wreck %+.2f m up "
          "(one 0.6 corner kick per frame, no cooldown)" % real_peak,
          real_peak > 3.0)
    # The port must never EXCEED the real machine here -- that is the bug
    # class the user hit (+105 m/s of vy).  It sits under it because the
    # harness's flat-box contact is zero-restitution in the linear channel
    # (an impulse has no force bound, so it cannot be allowed to convert
    # angular momentum into com lift the way retail's spring/bottom-out pass
    # legitimately does).  RE_NOTES 16.2 records the deviation.
    check("aftertouch held: the port reaches %+.2f m -- responds, and stays "
          "under the real machine's %+.2f m" % (peak2, real_peak),
          1.0 < peak2 < real_peak)
    settles = [r[13] for r in rows2]
    check("aftertouch does not reset the settle counter (max %d) -- retail "
          "only clears it at speed >= 1 (0x001236E0)" % max(settles),
          max(settles) > 5)
    # release the input: the wreck must come back down and settle
    # (the shell is metres up when the input stops, so give it the airtime
    # back before looking at the tail)
    rel = dict(base)
    rel['after_x'] = 1.0
    rel['after_frames'] = n // 4
    rows3 = run_driver(exe, 'wreck', rel, extra=[n * 2])
    tail3 = rows3[len(rows3) * 3 // 4:]
    y3 = [r[1] for r in tail3]
    sp3 = [r[6] for r in tail3]
    check("aftertouch released: back on the ground and at rest "
          "(%.3f m of jitter, |v| <= %.3f over the last %d frames)"
          % (max(y3) - min(y3), max(sp3), len(tail3)),
          max(y3) - min(y3) < 0.05 and max(sp3) < 1.0)

    # ---- the CRASH SLOW-MO (the takedown FX divisor 5: the harness steps
    # the wreck once per RENDERED frame with sim dt/5) --------------------
    print("\n   under the crash slow-mo (sim dt / 5, 300 steps a second):")
    slow = dict(base)
    slow['dt'] = DT / 5.0
    rows4 = run_driver(exe, 'wreck', slow, extra=[n * 5])
    # the free-flight arc must be EXACTLY gravity, whatever the step size
    bad = 0
    for i in range(1, len(rows4)):
        if int(rows4[i][15]) == 1 and int(rows4[i - 1][15]) == 1:
            if abs((rows4[i][4] - rows4[i - 1][4]) + 20.0 * slow['dt']) > 1e-3:
                bad += 1
    check("no input: every airborne step is exactly -20*dt of vy "
          "(%d anomalies in %d frames)" % (bad, len(rows4)), bad == 0,
          "energy must not enter the flight when the step shrinks")
    tail4 = rows4[len(rows4) * 3 // 4:]
    y4 = [r[1] for r in tail4]
    check("no input: comes to rest all the same (%.4f m of jitter, "
          "asleep %d)" % (max(y4) - min(y4), int(tail4[-1][14])),
          max(y4) - min(y4) < 0.05 and int(tail4[-1][14]) == 1)
    # held aftertouch under slow-mo: the kick is an IMPULSE, so firing it per
    # rendered frame would put five times the torque per simulated second
    # into the shell and hold it up for ever.  b3_wreck_aftertouch spends
    # banked simulated time instead (B3_AFTERTOUCH_PERIOD).
    slow_at = dict(slow)
    slow_at['after_x'] = 1.0
    rows5 = run_driver(exe, 'wreck', slow_at, extra=[n * 5])
    ys5 = [r[1] for r in rows5]
    peak5 = max(ys5)
    pk5 = ys5.index(peak5)
    check("aftertouch held in slow-mo: climbs to %+.2f m then FALLS back to "
          "%+.2f m" % (peak5 - base['ground'],
                       min(ys5[pk5:]) - base['ground']),
          min(ys5[pk5:]) - base['ground'] < 2.0,
          "the wreck must come down again, not float")
    check("aftertouch held in slow-mo: peak %+.2f m stays in the same band "
          "as the 60 Hz peak %+.2f m" % (peak5 - base['ground'], peak2),
          peak5 - base['ground'] < 2.0 * peak2)
    # ablation: the same run with the cadence match compiled out
    exe_nc = build_driver(defines=['-DB3_AFTERTOUCH_PERIOD=0.0f'],
                          tag='_nocadence')
    if exe_nc:
        rows6 = run_driver(exe_nc, 'wreck', slow_at, extra=[n * 5])
        # column 16 is the number of kicks the module actually applied
        k5, k6 = rows5[-1][16], rows6[-1][16]
        secs = len(rows5) * slow['dt']
        check("ABLATION: %d kicks in %.1f s of sim time with the cadence "
              "match (%.0f/s, the retail tick rate) vs %d without (%.0f/s)"
              % (k5, secs, k5 / secs, k6, k6 / secs),
              k6 > 4.0 * k5 and abs(k5 / secs - 60.0) < 2.0,
              "this is the regression guard on the per-frame kick rate")

    # ---- the user's second repro: a kerb clip at 130 mph under the
    # divisor-5 slow-mo with input held.  The dump had the wreck at
    # vel.y = +105.7 m/s (the vertical cap in FUN_00109560 is 120) with
    # airborne=0 -- a contact turning angular momentum into com lift, frame
    # after frame.  Nothing the contact does may raise vy above the entry
    # kick, whatever the ground height under the shell is.
    print("\n   130 mph kerb clip, slow-mo, input held (the live repro):")
    for label, gnd in (("flat road", 10.0), ("kerb +0.5 m", 10.5),
                       ("kerb +1.5 m", 11.5)):
        kerb = dict(base)
        kerb['vel_2'] = -58.0            # 130 mph
        kerb['rv_2'] = -58.0
        kerb['dt'] = DT / 5.0
        kerb['after_x'] = 1.0
        kerb['ground'] = gnd
        rowsk = run_driver(exe, 'wreck', kerb, extra=[900])
        vy_max = max(r[4] for r in rowsk)
        launch = rowsk[0][4]
        check("%s: peak vy %+.2f m/s never beats the entry kick %+.2f m/s"
              % (label, vy_max, launch), vy_max <= launch + 0.01,
              "a zero-restitution contact must not launch the shell")
        check("%s: peak height %+.2f m over the road"
              % (label, max(r[1] for r in rowsk) - gnd),
              max(r[1] for r in rowsk) - gnd < 6.0)


# ---------------------------------------------------------------------------
# 9. THE PER-SLOT CRASH LATCH -- FUN_0010DD20 (CRASH-AUDIT)
#
# The crash-ENTRY state machine refuses a second crash on two conditions and
# then stamps the cooldown that enforces the second one:
#
#   0010dd30  MOV AL,[EBX+0x210] / TEST / JNZ 0x0010e4f7   already crashed
#   0010dd40  CMP ESI,-1 / JZ 0x0010e4f7                   no slot
#   0010dd82  IMUL ECX,ECX,0x3C / LEA EAX,[ECX+EDX]        rec = mgr+slot*0x3C
#   0010dd8c  LEA EDI,[EAX+0x110]
#   0010dddf  MOVSS XMM0,[EAX+0x130] / COMISS [0x003B16E0] / JA  -> COOLDOWN
#   ...
#   0010e431  LAB: MOV ECX,[ESP+0x3C]; CMP [ECX+0x1920],2  the table below
#   0010e4a8/0010e456  MOVSS [EDI+0x20],XMM0               = rec+0x130
#
# so the value LAB_0010E431 selects IS the field the head compares against
# 0.0 -- one field, +0x130, written here and read there.  These assertions
# pin the four immediates, the two store sites, the read site, and the
# arithmetic that makes them the same address.
# ---------------------------------------------------------------------------
LATCH_BYTES = [
    ("0x0010DD30 reads veh+0x210 (already crashed)", 0x0010DD30, 6,
     b'\x8a\x83\x10\x02\x00\x00'),
    ("0x0010DD82 rec = mgr + slot*0x3C", 0x0010DD82, 3, b'\x6b\xc9\x3c'),
    ("0x0010DD8C EDI = rec + 0x110", 0x0010DD8C, 6,
     b'\x8d\xb8\x10\x01\x00\x00'),
    ("0x0010DDDF reads rec+0x130 (the cooldown)", 0x0010DDDF, 8,
     b'\xf3\x0f\x10\x80\x30\x01\x00\x00'),
    ("0x0010DDE7 compares it with 0.0 [0x003B16E0]", 0x0010DDE7, 7,
     b'\x0f\x2f\x05\xe0\x16\x3b\x00'),
    ("0x0010E435 splits on racecar+0x1920 == 2", 0x0010E435, 7,
     b'\x83\xb9\x20\x19\x00\x00\x02'),
    ("0x0010E444 truck presented -> 15.0 [0x003B16B4]", 0x0010E444, 8,
     b'\xf3\x0f\x10\x05\xb4\x16\x3b\x00'),
    ("0x0010E44E truck fresh -> 7.0 [0x003B1708]", 0x0010E44E, 8,
     b'\xf3\x0f\x10\x05\x08\x17\x3b\x00'),
    ("0x0010E456 stores it to EDI+0x20 (= rec+0x130)", 0x0010E456, 5,
     b'\xf3\x0f\x11\x47\x20'),
    ("0x0010E48C car presented + FUN_00017390 -> 17.0 [0x003B1C5C]",
     0x0010E48C, 8, b'\xf3\x0f\x10\x05\x5c\x1c\x3b\x00'),
    ("0x0010E496 car presented -> 15.0 [0x003B16B4]", 0x0010E496, 8,
     b'\xf3\x0f\x10\x05\xb4\x16\x3b\x00'),
    ("0x0010E4A0 car fresh -> 3.0 [0x003B1698]", 0x0010E4A0, 8,
     b'\xf3\x0f\x10\x05\x98\x16\x3b\x00'),
    ("0x0010E4A8 stores it to EDI+0x20 (= rec+0x130)", 0x0010E4A8, 5,
     b'\xf3\x0f\x11\x47\x20'),
    ("0x0010E4AD second timer 0.25 [0x003B1730]", 0x0010E4AD, 8,
     b'\xf3\x0f\x10\x05\x30\x17\x3b\x00'),
]


def run_latch_cases():
    print("\n-- 9. the per-slot crash latch (FUN_0010DD20 / LAB_0010E431)")
    data = open(os.path.join(_root, 'build', 'burnout3.elf'), 'rb').read()
    ph_off = struct.unpack_from('<I', data, 0x1C)[0]
    ph_num = struct.unpack_from('<H', data, 0x2C)[0]
    segs = [s for s in (struct.unpack_from('<IIIIIIII', data, ph_off + i * 32)
                        for i in range(ph_num)) if s[0] == 1]

    def rd(va, n):
        for _t, o, v, _p, f, _m, _fl, _a in segs:
            if v <= va < v + f:
                return data[o + (va - v):o + (va - v) + n]
        return b'\0' * n

    for name, va, n, want in LATCH_BYTES:
        got = rd(va, n)
        check(name, got == want, "got %s want %s" % (got.hex(), want.hex()))

    def rf(va):
        return struct.unpack('<f', rd(va, 4))[0]

    for name, va, want in (("[0x003B1708] truck fresh", 0x003B1708, 7.0),
                           ("[0x003B16B4] presented", 0x003B16B4, 15.0),
                           ("[0x003B1698] car fresh", 0x003B1698, 3.0),
                           ("[0x003B1C5C] car presented+17390", 0x003B1C5C,
                            17.0),
                           ("[0x003B1730] second timer", 0x003B1730, 0.25),
                           ("[0x003B16E0] the cooldown compare", 0x003B16E0,
                            0.0)):
        check(name + " = %g" % want, abs(rf(va) - want) < 1e-6,
              "got %g" % rf(va))

    # ...and the C port's table against those same immediates.
    exe = build_driver()
    if not exe:
        check("crash-latch driver builds", False)
        return
    got = run_driver(exe, 'latch', {})[0]
    for name, g, want in (("b3_crash_latch_duration(truck, fresh)", got[0],
                           7.0),
                          ("b3_crash_latch_duration(truck, presented)", got[1],
                           15.0),
                          ("b3_crash_latch_duration(car, fresh)", got[2], 3.0),
                          ("b3_crash_latch_duration(car, presented) [S: the "
                           "!FUN_00017390 arm]", got[3], 15.0)):
        check(name + " = %g" % want, abs(g - want) < 1e-6, "got %g" % g)


def main():
    quick = '--quick' in sys.argv
    run_kick_cases()
    runs = run_traj_cases(quick)
    if runs:
        run_flight_cases(runs, quick)
    run_settle_cases()
    run_sleep_cases()
    run_scrape_cases()
    run_rest_cases(quick)
    run_sequence_cases(quick)
    run_latch_cases()
    print("\n%d/%d" % (PASS, PASS + FAIL))
    return 1 if FAIL else 0


if __name__ == '__main__':
    sys.exit(main())
