#!/usr/bin/env python3
"""Differential validation of the recovered AI DRIVER (src/burnout3_ai.c)
against the real x86 executed under Unicorn.

Unlike the other suites here, this one does NOT compare against a Python
mirror of the rule: it compiles src/burnout3_ai.c itself into a probe
(build/ai_probe) and diffs THAT against the retail instructions.  What is
asserted is the shipped C, not a paraphrase of it.

Functions under test (analyzed burnout3.elf, .text = flat + 0x10000):
  0x0016AE20  arbitrator "target wins" leg  -> desired dir + time-to-target
  0x00171E30  target steering angle          -> racecar+0x23C0  (both paths)
  0x00172E80  corner-speed law               (returns XMM0)
  0x001724F0  target speed                   -> racecar+0x23C4
  0x00105340  the AI racer driver            -> the vehicle input block
  0x00104CA0  brake helper                   (reverse gear routing)
  0x00171078  out-of-range speed governor    (tail of FUN_00170B30)

Evidence notes: docs/RE_AI.md sections 8-13, docs/RE_CONTROL_AUDIT.md.
Run from the repo root:  python3 tools/validate_ai.py
"""
import math
import os
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import emulate_ai as ea                                       # noqa: E402
from unicorn.x86_const import (UC_X86_REG_EAX, UC_X86_REG_EBX,  # noqa: E402
                               UC_X86_REG_ECX, UC_X86_REG_EDI,
                               UC_X86_REG_ESI, UC_X86_REG_ESP)

AI = ea.AI
RC = ea.RC
VEH = ea.VEH
FRAME = ea.FRAME
TOL = 1e-5

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")
PROBE_C = os.path.join(BUILD, "ai_probe.c")
PROBE = os.path.join(BUILD, "ai_probe")

# ===========================================================================
# The probe: a key=value driver around the real module.
# ===========================================================================
PROBE_SRC = r'''
/* GENERATED by tools/validate_ai.py -- a key=value driver around the shipped
 * src/burnout3_ai.c so the differential suite tests the C, not a paraphrase. */
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "../src/burnout3_ai.c"

static B3AiCar C;
static B3AiState S;
static B3AiInputs IN;
static float TP[3];
static float g_max_speed, g_catchup, g_dt, g_revdot, g_gov_speed,
             g_gov_mph, g_gov_target;

#define AGG_NCARS 4
static B3AiAggroCar AC[AGG_NCARS];
static float AC_LAT[AGG_NCARS][AGG_NCARS];
static float AC_HIT[AGG_NCARS][AGG_NCARS];
static B3AiAggroWorld AW;
static B3AiAggro AG;
static B3AiAggroSpeed ASP;
static int g_self, g_denable, g_dmode, g_dl, g_dr, g_dc;
/* section 16: the route driver's wheel + watchdogs */
static B3AiWheel W;
static int g_wheel_on, g_wheel_edge, g_walk_ok, g_navfired, g_owfired,
           g_ow_node, g_cb_mode, g_cb_1fc, g_cb_bscale;
static float g_ow_dy, g_cb_cs, g_cb_d, g_cb_cap, g_cb_out;
static float g_aggression, g_spd_in, g_spd_out, g_dang, g_dspeed;
static float g_daim[4], g_dpos[4], g_dfwd[4];

typedef struct { const char* n; void* p; int isint; } Bind;
static const Bind NAVBINDS[] = {
    {"w.enable",&W.ai_enable,1},{"w.wheel",&W.ai_wheel,1},
    {"w.skip",&W.skip_once,1},{"w.navfail",&W.navfail_frames,1},
    {"w.below",&W.below_frames,1},{"w.lastnode",&W.last_node,1},
    {"w.alt",&W.route_alt,1},{"w.t0",&W.alt_t[0],0},{"w.t1",&W.alt_t[1],0},
    {"on",&g_wheel_on,1},{"walkok",&g_walk_ok,1},
    {"ownode",&g_ow_node,1},{"owdy",&g_ow_dy,0},
    {"cs",&g_cb_cs,0},{"cbd",&g_cb_d,0},{"cbcap",&g_cb_cap,0},
    {"cbmode",&g_cb_mode,1},{"cb1fc",&g_cb_1fc,1},{"cbbs",&g_cb_bscale,1},
    {NULL,NULL,0}
};
static const Bind BINDS[] = {
    {"pos.x",&C.pos[0],0},{"pos.y",&C.pos[1],0},{"pos.z",&C.pos[2],0},
    {"fwd.x",&C.fwd[0],0},{"fwd.y",&C.fwd[1],0},{"fwd.z",&C.fwd[2],0},
    {"right.x",&C.right[0],0},{"right.y",&C.right[1],0},{"right.z",&C.right[2],0},
    {"carat.x",&C.car_at[0],0},{"carat.y",&C.car_at[1],0},{"carat.z",&C.car_at[2],0},
    {"vfwd.x",&C.veh_fwd[0],0},{"vfwd.y",&C.veh_fwd[1],0},{"vfwd.z",&C.veh_fwd[2],0},
    {"vright.x",&C.veh_right[0],0},{"vright.y",&C.veh_right[1],0},
    {"vright.z",&C.veh_right[2],0},
    {"speed",&C.speed_ms,0},{"yaw",&C.yaw_rate,0},
    {"rpm",&C.engine_rpm,0},{"uprpm",&C.change_up_rpm,0},
    {"drift",&C.drift_state,1},{"gear",&C.gear,1},
    {"lsdm",&C.lsdm_active,1},{"lsdmlim",&C.lsdm_limit_mph,0},
    {"traffic",&C.traffic_class,1},{"mode",&C.race_mode,1},
    {"crasht",&C.crash_timer,0},{"freefloor",&C.free_speed_floor,1},
    {"boosting",&C.boosting,1},{"rampdone",&C.boost_ramp_done,1},
    {"brakesup",&C.brake_suppressed,1},
    {"atk",&C.attack_active,1},{"atkl",&C.attack_left,1},
    {"atkr",&C.attack_right,1},{"atkc",&C.attack_commit,1},
    {"wantboost",&C.wants_boost,1},
    {"oocw",&C.ooc_window,1},{"oocm",&C.ooc_mode,1},{"oocc",&C.ooc_countersteer,1},
    {"clock",&C.clock,0},
    {"dd.x",&S.des_dir[0],0},{"dd.y",&S.des_dir[1],0},
    {"dd.z",&S.des_dir[2],0},{"dd.w",&S.des_dir[3],0},
    {"ddn.x",&S.des_dir_n[0],0},{"ddn.y",&S.des_dir_n[1],0},
    {"ddn.z",&S.des_dir_n[2],0},{"ddn.w",&S.des_dir_n[3],0},
    {"t2t",&S.time_to_target,0},{"t2ts",&S.t2t_snap,0},
    {"maxspd",&S.max_speed,0},{"cap",&S.speed_cap,0},
    {"tmode",&S.target_mode,1},{"bscale",&S.boost_scale_flag,1},
    {"tang",&S.target_angle,0},{"tspd",&S.target_speed,0},
    {"prevang",&S.prev_angle,0},{"cspd",&S.corner_speed,0},
    {"serr",&S.steer_err,0},
    {"arm",&S.stuck_arm,0},{"rev",&S.reverse_timer,0},
    {"dith",&S.dither_deadline,0},{"prevthr",&S.prev_throttle,0},
    {"bhold",&S.brake_hold,0},{"auth",&S.steer_authority,0},
    {"prevsteer",&S.prev_steer,0},{"sdrift",&S.drift_state,1},
    {"tp.x",&TP[0],0},{"tp.y",&TP[1],0},{"tp.z",&TP[2],0},
    {"argmax",&g_max_speed,0},{"catchup",&g_catchup,0},{"dt",&g_dt,0},
    {"revdot",&g_revdot,0},
    {"gspeed",&g_gov_speed,0},{"gmph",&g_gov_mph,0},{"gtgt",&g_gov_target,0},
    {"p.angmin",&b3_ai_params.angle_min_speed_deg,0},
    {"p.top",&b3_ai_params.top_speed_mps,0},
    {"p.min",&b3_ai_params.min_speed_mps,0},
    {"p.carat",&b3_ai_params.car_at_weight,0},
    {"p.lock",&b3_ai_params.max_lock_deg,0},
    {"p.driftlock",&b3_ai_params.drift_max_lock_deg,0},
    {"p.oordec",&b3_ai_params.oor_speed_dec_rate,0},
    {"p.apex",&b3_ai_drift_apex_time,0},
    /* --- aggression machine (section 14) --- */
    {"selfi",&g_self,1},{"clk",&AW.clock,0},{"wdt",&AW.dt,0},
    {"ncars",&AW.ncars,1},{"loaded",&AW.track_loaded,1},
    {"a.state",&AG.state,1},{"a.aimv",&AG.aim_valid,-1},
    {"a.att",&AG.attacking,-1},{"a.ss",&AG.slam_speed,-1},
    {"a.blocked",&AG.blocked,-1},{"a.hit",&AG.hit,-1},
    {"a.timer",&AG.timer,0},{"a.entered",&AG.entered,0},
    {"a.side",&AG.side,0},{"a.lat",&AG.lateral,0},{"a.lon",&AG.longitudinal,0},
    {"a.cs",&AG.can_slam,-1},{"a.br",&AG.block_range,-1},
    {"a.wss",&AG.want_slam_speed,-1},{"a.tgt",&AG.target,1},
    {"a.blindt",&AG.blind_time,0},{"a.blindp",&AG.blind_phase,0},
    {"a.blinda",&AG.blind_arm,-1},
    {"s.mode",&ASP.mode,1},{"s.tgt",&ASP.target,1},
    {"s.last",&ASP.last_target,1},{"s.ahead",&ASP.acquired_ahead,-1},
    {"s.wb",&ASP.want_boost,-1},{"s.bn",&ASP.boost_now,-1},
    {"s.wants",&ASP.wants_boost,-1},
    {"s.buntil",&ASP.boost_until,0},{"s.brearm",&ASP.boost_rearm,0},
    {"aggro",&g_aggression,0},{"spdin",&g_spd_in,0},
    {"d.enable",&g_denable,1},{"d.mode",&g_dmode,1},{"d.ang",&g_dang,0},
    {"d.speed",&g_dspeed,0},
    {"d.l",&g_dl,1},{"d.r",&g_dr,1},{"d.c",&g_dc,1},
    {"d.aim.x",&g_daim[0],0},{"d.aim.y",&g_daim[1],0},{"d.aim.z",&g_daim[2],0},
    {"d.pos.x",&g_dpos[0],0},{"d.pos.y",&g_dpos[1],0},{"d.pos.z",&g_dpos[2],0},
    {"d.fwd.x",&g_dfwd[0],0},{"d.fwd.y",&g_dfwd[1],0},{"d.fwd.z",&g_dfwd[2],0},
    {NULL,NULL,0}
};

/* per-car fields, addressed as c<i>.<name> */
typedef struct { const char* n; size_t off; int isint; } CBind;
#define CB(f,i) {#f, offsetof(B3AiAggroCar,f), i}
static const CBind CBINDS[] = {
    {"pos.x",offsetof(B3AiAggroCar,pos[0]),0},
    {"pos.y",offsetof(B3AiAggroCar,pos[1]),0},
    {"pos.z",offsetof(B3AiAggroCar,pos[2]),0},
    {"fwd.x",offsetof(B3AiAggroCar,fwd[0]),0},
    {"fwd.y",offsetof(B3AiAggroCar,fwd[1]),0},
    {"fwd.z",offsetof(B3AiAggroCar,fwd[2]),0},
    {"right.x",offsetof(B3AiAggroCar,right[0]),0},
    {"right.y",offsetof(B3AiAggroCar,right[1]),0},
    {"right.z",offsetof(B3AiAggroCar,right[2]),0},
    {"rd.x",offsetof(B3AiAggroCar,road_dir[0]),0},
    {"rd.y",offsetof(B3AiAggroCar,road_dir[1]),0},
    {"rd.z",offsetof(B3AiAggroCar,road_dir[2]),0},
    CB(speed_ms,0), CB(track_dist,0), CB(aggression,0),
    CB(car_width,0), CB(car_length,0), CB(ooc_time,0), CB(race_time,0),
    CB(boost_start,0), CB(slammed_time,0), CB(slammed_by,1),
    CB(race_mode,1), CB(car_class,1), CB(mode2450,1), CB(rival,1),
    CB(wrecked,1), CB(in_takedown,1), CB(boosting,1), CB(race_progress_zero,1),
    CB(no_slam_speed,1), CB(drift_zone,1), CB(node_open,1), CB(steer_ok,1),
    CB(progress_gate,1),
    CB(player_slot,1),
    {NULL,0,0}
};

static void setkv(char* kv) {
    char* eq = strchr(kv, '=');
    int i;
    if (!eq) return;
    *eq = 0;
    if (kv[0] == 'c' && kv[1] >= '0' && kv[1] <= '9' && kv[2] == '.') {
        int ci = kv[1] - '0';
        char* nm = kv + 3;
        for (i = 0; CBINDS[i].n; i++) {
            if (!strcmp(CBINDS[i].n, nm)) {
                void* p = (char*)&AC[ci] + CBINDS[i].off;
                if (CBINDS[i].isint) *(int*)p = atoi(eq + 1);
                else                 *(float*)p = (float)atof(eq + 1);
                return;
            }
        }
        if (!strncmp(nm, "lat", 3))  { AC_LAT[ci][atoi(nm + 3)] = (float)atof(eq + 1); return; }
        if (!strncmp(nm, "hit", 3))  { AC_HIT[ci][atoi(nm + 3)] = (float)atof(eq + 1); return; }
        fprintf(stderr, "unknown car key %s\n", nm);
        exit(2);
    }
    for (i = 0; NAVBINDS[i].n; i++) {
        if (!strcmp(NAVBINDS[i].n, kv)) {
            if (NAVBINDS[i].isint) *(int*)NAVBINDS[i].p = atoi(eq + 1);
            else                   *(float*)NAVBINDS[i].p = (float)atof(eq + 1);
            return;
        }
    }
    for (i = 0; BINDS[i].n; i++) {
        if (!strcmp(BINDS[i].n, kv)) {
            if (BINDS[i].isint > 0)  *(int*)BINDS[i].p = atoi(eq + 1);
            else if (BINDS[i].isint) *(unsigned char*)BINDS[i].p =
                                        (unsigned char)atoi(eq + 1);
            else                     *(float*)BINDS[i].p = (float)atof(eq + 1);
            return;
        }
    }
    fprintf(stderr, "unknown key %s\n", kv);
    exit(2);
}

static void emit(void) {
    printf("tang=%.9g tspd=%.9g cspd=%.9g serr=%.9g prevang=%.9g "
           "ddn.x=%.9g ddn.y=%.9g ddn.z=%.9g t2t=%.9g "
           "thr=%.9g brk=%.9g str=%.9g raw=%.9g bits=%d gear=%d stop=%d "
           "eng=%d commit=%d arm=%.9g rev=%.9g dith=%.9g prevthr=%.9g "
           "auth=%.9g sdrift=%d gov=%.9g\n",
           S.target_angle, S.target_speed, S.corner_speed, S.steer_err,
           S.prev_angle, S.des_dir_n[0], S.des_dir_n[1], S.des_dir_n[2],
           S.time_to_target, IN.throttle, IN.brake, IN.steer,
           IN.throttle_raw, (int)IN.bits, IN.gear_request, IN.stop_flag,
           IN.engage_boost, IN.commit_boost, S.stuck_arm, S.reverse_timer,
           S.dither_deadline, S.prev_throttle, S.steer_authority,
           S.drift_state,
           b3_ai_oor_governor(g_gov_speed, g_gov_mph, g_gov_target));
    fflush(stdout);
}

static void emit_agg(void) {
    printf("state=%d aimv=%d att=%d ss=%d blocked=%d hit=%d timer=%.9g "
           "entered=%.9g side=%.9g lat=%.9g lon=%.9g cs=%d br=%d wss=%d "
           "tgt=%d aim.x=%.9g aim.y=%.9g aim.z=%.9g blindt=%.9g blindo=%d "
           "spdout=%.9g smode=%d stgt=%d slast=%d swb=%d swants=%d "
           "sbuntil=%.9g sahead=%d dl=%d dr=%d dc=%d\n",
           AG.state, AG.aim_valid, AG.attacking, AG.slam_speed, AG.blocked,
           AG.hit, AG.timer, AG.entered, AG.side, AG.lateral,
           AG.longitudinal, AG.can_slam, AG.block_range, AG.want_slam_speed,
           AG.target, AG.aim[0], AG.aim[1], AG.aim[2], AG.blind_time,
           AG.blind_out, g_spd_out, ASP.mode, ASP.target, ASP.last_target,
           ASP.want_boost, ASP.wants_boost, ASP.boost_until,
           ASP.acquired_ahead, g_dl, g_dr, g_dc);
    fflush(stdout);
}

static void emit_nav(void) {
    printf("wheel=%d edge=%d skip=%d navfail=%d below=%d lastnode=%d "
           "alt=%d t0=%.9g t1=%.9g dy=%.9g navfired=%d owfired=%d "
           "auth=%.9g sdrift=%d cbout=%.9g\n",
           W.ai_wheel, g_wheel_edge, W.skip_once, W.navfail_frames,
           W.below_frames, W.last_node, W.route_alt, W.alt_t[0], W.alt_t[1],
           W.road_dy, g_navfired, g_owfired, S.steer_authority, S.drift_state,
           g_cb_out);
    fflush(stdout);
}

static void wire_world(void) {
    int i;
    for (i = 0; i < AGG_NCARS; i++) {
        AC[i].lateral_to = AC_LAT[i];
        AC[i].last_hit = AC_HIT[i];
    }
    AW.cars = AC;
}

int main(void) {
    char line[8192];
    b3_ai_init();
    memset(&C, 0, sizeof C);
    b3_ai_state_init(&S);
    memset(&IN, 0, sizeof IN);
    while (fgets(line, sizeof line, stdin)) {
        char* tok = strtok(line, " \t\n\r");
        char op[64];
        if (!tok) continue;
        snprintf(op, sizeof op, "%s", tok);
        if (!strcmp(op, "reset")) {
            memset(&C, 0, sizeof C);
            b3_ai_state_init(&S);
            memset(&IN, 0, sizeof IN);
            g_max_speed = g_catchup = g_revdot = 0.0f;
            g_dt = 1.0f / 60.0f;
            memset(&W, 0, sizeof W);
            g_wheel_on = g_wheel_edge = g_walk_ok = g_navfired = 0;
            g_owfired = g_ow_node = g_cb_mode = g_cb_1fc = g_cb_bscale = 0;
            g_ow_dy = g_cb_cs = g_cb_d = g_cb_cap = g_cb_out = 0.0f;
            continue;
        }
        while ((tok = strtok(NULL, " \t\n\r")) != NULL) setkv(tok);
        if (!strcmp(op, "commit"))       b3_ai_commit_target(&S, &C, TP);
        else if (!strcmp(op, "snap"))    b3_ai_frame_snapshot(&S);
        else if (!strcmp(op, "angle"))   b3_ai_target_angle(&S, &C);
        else if (!strcmp(op, "corner"))
            S.corner_speed = b3_ai_corner_speed(&S, &C, g_max_speed);
        else if (!strcmp(op, "tspeed"))  b3_ai_target_speed(&S, &C, g_catchup);
        else if (!strcmp(op, "drive"))
            b3_ai_drive(&S, &C, &IN, g_dt, g_revdot);
        else if (!strcmp(op, "brake"))
            b3_ai_brake(&IN, &S, &C, 1.0f);
        else if (!strcmp(op, "update"))
            b3_ai_update(&S, &C, &IN, TP, g_max_speed, g_catchup, g_dt);
        else if (!strcmp(op, "gov"))     { /* emitted unconditionally */ }
        else if (!strcmp(op, "agginit")) {
            wire_world(); b3_aggro_init(&AG, AW.clock);
            b3_aggro_speed_init(&ASP); emit_agg(); continue;
        }
        else if (!strcmp(op, "aggupd")) {
            wire_world(); b3_aggro_update(&AG, &AW, g_self);
            emit_agg(); continue;
        }
        else if (!strcmp(op, "aggarb")) {
            int t = -1;
            wire_world();
            ASP.mode = b3_aggro_arbitrate(&AG, &AW, g_self, &t);
            ASP.target = t;
            emit_agg(); continue;
        }
        else if (!strcmp(op, "aggspd")) {
            wire_world();
            g_spd_out = b3_ai_aggro_speed(&ASP, &AW, g_self, g_aggression,
                                          g_spd_in);
            emit_agg(); continue;
        }
        else if (!strcmp(op, "boostlatch")) {
            b3_ai_boost_latch(&ASP, AW.clock); emit_agg(); continue;
        }
        else if (!strcmp(op, "winit")) {
            b3_ai_wheel_init(&W, g_ow_node); emit_nav(); continue;
        }
        else if (!strcmp(op, "ralt")) {
            b3_ai_route_alt(&W, g_dt); emit_nav(); continue;
        }
        else if (!strcmp(op, "wheel")) {
            g_wheel_edge = b3_ai_wheel_set(&W, &S, g_wheel_on);
            emit_nav(); continue;
        }
        else if (!strcmp(op, "offworld")) {
            g_owfired = b3_ai_offworld(&W, g_ow_node, g_ow_dy);
            emit_nav(); continue;
        }
        else if (!strcmp(op, "navfail")) {
            g_navfired = b3_ai_navfail(&W, g_walk_ok);
            emit_nav(); continue;
        }
        else if (!strcmp(op, "cbrake")) {
            g_cb_out = b3_ai_corner_brake(g_cb_cs, g_cb_d, g_cb_bscale,
                                          g_cb_cap, g_cb_mode, g_cb_1fc);
            emit_nav(); continue;
        }
        else if (!strcmp(op, "driftflags")) {
            b3_ai_drift_flags(g_denable, g_dmode, g_dang, g_daim, g_dpos,
                              g_dfwd, g_dspeed, &g_dl, &g_dr, &g_dc);
            emit_agg(); continue;
        }
        else { fprintf(stderr, "unknown op %s\n", op); exit(2); }
        emit();
    }
    return 0;
}
'''


class Probe(object):
    """Persistent process running the compiled src/burnout3_ai.c."""

    def __init__(self):
        os.makedirs(BUILD, exist_ok=True)
        with open(PROBE_C, "w") as fh:
            fh.write(PROBE_SRC)
        cc = subprocess.run(
            ["gcc", "-O1", "-std=c99", "-Wall", "-Wextra", "-Wno-unused-parameter",
             "-o", PROBE, PROBE_C, "-lm"],
            cwd=BUILD, capture_output=True, text=True)
        if cc.returncode:
            print(cc.stdout)
            print(cc.stderr)
            raise SystemExit("ai_probe failed to compile")
        self.warn = cc.stderr
        self.p = subprocess.Popen([PROBE], stdin=subprocess.PIPE,
                                  stdout=subprocess.PIPE, text=True,
                                  bufsize=1)

    def cmd(self, op, **kw):
        parts = [op]
        for k, v in kw.items():
            k = k.replace("__", ".")
            parts.append("%s=%s" % (k, ("%d" % v) if isinstance(v, int)
                                    else ("%.9g" % v)))
        self.p.stdin.write(" ".join(parts) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        out = {}
        for kv in line.split():
            k, v = kv.split("=", 1)
            out[k] = float(v)
        return out

    def cmd_kv(self, op, kv):
        """Same as cmd() but takes a dict, so keys may contain dots."""
        parts = [op]
        for k, v in kv.items():
            parts.append("%s=%s" % (k, ("%d" % v) if isinstance(v, int)
                                    else ("%.9g" % v)))
        self.p.stdin.write(" ".join(parts) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        out = {}
        for x in line.split():
            k, v = x.split("=", 1)
            out[k] = float(v)
        return out

    def reset(self):
        self.p.stdin.write("reset\n")
        self.p.stdin.flush()


PROBE_P = None


def probe():
    global PROBE_P
    if PROBE_P is None:
        PROBE_P = Probe()
    return PROBE_P


# ===========================================================================
# helpers
# ===========================================================================
def check(name, pairs, tol=TOL):
    """pairs: list of (label, real, mine).  Returns 0 on success."""
    bad = []
    for label, real, mine in pairs:
        if real != real or mine != mine:          # NaN
            bad.append("%s NaN (real %r mine %r)" % (label, real, mine))
        elif abs(real - mine) > tol * max(1.0, abs(real)):
            bad.append("%s %.7g != %.7g" % (label, mine, real))
    print("  %-42s %s" % (name, "OK" if not bad else "FAIL " + "; ".join(bad)))
    return 1 if bad else 0


def norm(v):
    n = math.sqrt(sum(x * x for x in v[:3]))
    return [x / n for x in v[:3]]


# ===========================================================================
# 1. FUN_0016AE20 -- desired direction + time-to-target
# ===========================================================================
COMMIT_CASES = [
    # name, car pos, target point, speed
    ("straight ahead",  (0.0, 0.0, 0.0),   (0.0, 0.0, 40.0),   40.0),
    ("offset target",   (12.0, 1.0, -5.0), (40.0, 3.0, 60.0),  33.0),
    ("crawl (speed<1)", (0.0, 0.0, 0.0),   (10.0, 0.0, 10.0),   0.5),
    ("behind",          (0.0, 0.0, 0.0),   (-5.0, 0.0, -30.0), 55.0),
]


def run_commit():
    fails = 0
    print("\nFUN_0016AE20  arbitrated target -> direction + time-to-target:")
    for name, pos, tp, speed in COMMIT_CASES:
        s = ea.Session()
        ea.seed_car(s, pos=pos, speed=speed)
        s.wb(AI + 0x190, 1)                    # the "have a target point" leg
        s.wv(AI + 0x180, list(tp) + [1.0])     # AI target point
        s.wb(AI + 0x212, 0)
        s.call(ea.F_COMMIT_TARGET, regs={UC_X86_REG_ESI: AI})
        real = [s.rf(AI + 0x770 + i * 4) for i in range(3)] + \
               [s.rf(AI + 0x784)]
        p = probe()
        p.reset()
        got = p.cmd("commit", pos__x=pos[0], pos__y=pos[1], pos__z=pos[2],
                    tp__x=tp[0], tp__y=tp[1], tp__z=tp[2], speed=speed)
        got = p.cmd("snap")
        mine = [got["ddn.x"], got["ddn.y"], got["ddn.z"], got["t2t"]]
        fails += check(name, [("dir.x", real[0], mine[0]),
                              ("dir.y", real[1], mine[1]),
                              ("dir.z", real[2], mine[2]),
                              ("t2t", real[3], mine[3])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 2. FUN_00171E30 -- target steering angle, racing path
# ===========================================================================
ANGLE_CASES = [
    # name, desired dir, car fwd, carAt, prev_angle
    ("aligned",              (0.0, 0.0, 1.0), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), 0.0),
    ("30 deg right, cold",   (0.5, 0.0, 0.8660254), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), 0.0),
    ("30 deg right, warm",   (0.5, 0.0, 0.8660254), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), 25.0),
    ("30 deg left, warm",    (-0.5, 0.0, 0.8660254), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), -25.0),
    ("unwind from +30",      (0.0, 0.0, 1.0), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), 30.0),
    ("unwind from -30",      (0.0, 0.0, 1.0), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), -30.0),
    ("carAt drifted right",  (0.0, 0.0, 1.0), (0.0, 0.0, 1.0),
     (0.34202, 0.0, 0.93969), 0.0),
    ("wide left, warm",      (-0.9063, 0.0, 0.42262), (0.0, 0.0, 1.0),
     (0.0, 0.0, 1.0), -2.0),
]


def run_angle():
    fails = 0
    print("\nFUN_00171E30  target steering angle (racing path):")
    for name, dd, fwd, carat, prev in ANGLE_CASES:
        right = (fwd[2], 0.0, -fwd[0])
        s = ea.Session()
        ea.seed_car(s, fwd=fwd, right=right, car_at=carat, speed=40.0)
        s.wv(AI + 0x7B0, list(norm(dd)) + [0.0])
        s.wf(AI + 0x9C8, 1.0)
        s.wf(AI + 0x9CC, prev)
        s.wb(VEH + 0x1550, 0)                 # LSDM off -> racing path
        s.call(ea.F_TARGET_ANGLE, regs={UC_X86_REG_ESI: AI})
        real_ang = s.rf(AI + 0x9C0)
        real_prev = s.rf(AI + 0x9CC)
        real_err = s.rf(AI + 0x9D4)
        n = norm(dd)
        p = probe()
        p.reset()
        got = p.cmd("angle",
                    ddn__x=n[0], ddn__y=n[1], ddn__z=n[2],
                    fwd__x=fwd[0], fwd__y=fwd[1], fwd__z=fwd[2],
                    right__x=right[0], right__y=right[1], right__z=right[2],
                    carat__x=carat[0], carat__y=carat[1], carat__z=carat[2],
                    speed=40.0, prevang=prev, lsdm=0, t2ts=1.0)
        fails += check(name, [("angle", real_ang, got["tang"]),
                              ("prev", real_prev, got["prevang"]),
                              ("err", real_err, got["serr"])], tol=2e-5)
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 2b. FUN_00171E30 -- the LSDM / drift yaw-rate path
# ===========================================================================
DRIFT_ANGLE_CASES = [
    # name, desired dir, carAt, yaw_rate, t2t, drift_state, speed
    ("lsdm below limit",     (0.5, 0.0, 0.86602540), (0.0, 0.0, 1.0),
     0.0, 1.0, 0, 5.0),
    ("drifting, yaw with",   (0.5, 0.0, 0.86602540), (0.0, 0.0, 1.0),
     0.4, 1.0, 2, 40.0),
    ("drifting, yaw against", (-0.5, 0.0, 0.86602540), (0.0, 0.0, 1.0),
     0.4, 1.0, 1, 40.0),
    ("drifting, short t2t",  (0.25882, 0.0, 0.96593), (0.0, 0.0, 1.0),
     -0.2, 0.4, 2, 30.0),
]


def run_drift_angle():
    fails = 0
    print("\nFUN_00171E30  target steering angle (LSDM/drift yaw-rate path):")
    for name, dd, carat, yaw, t2t, drift, speed in DRIFT_ANGLE_CASES:
        fwd = (0.0, 0.0, 1.0)
        right = (1.0, 0.0, 0.0)
        s = ea.Session()
        ea.seed_car(s, fwd=fwd, right=right, car_at=carat, speed=speed,
                    yaw_rate=yaw, drift_state=drift, lsdm_limit=25.0)
        s.wb(VEH + 0x1550, 1)                 # LSDM engaged
        s.wv(AI + 0x7B0, list(norm(dd)) + [0.0])
        s.wf(AI + 0x9C8, t2t)
        s.wf(AI + 0x9CC, 3.0)
        s.wi(AI + 0x1F8, 0)
        s.call(ea.F_TARGET_ANGLE, regs={UC_X86_REG_ESI: AI})
        real_ang = s.rf(AI + 0x9C0)
        real_err = s.rf(AI + 0x9D4)
        real_prev = s.rf(AI + 0x9CC)
        n = norm(dd)
        p = probe()
        p.reset()
        got = p.cmd("angle",
                    ddn__x=n[0], ddn__y=n[1], ddn__z=n[2],
                    fwd__x=fwd[0], fwd__y=fwd[1], fwd__z=fwd[2],
                    right__x=right[0], right__y=right[1], right__z=right[2],
                    vfwd__x=fwd[0], vfwd__y=fwd[1], vfwd__z=fwd[2],
                    vright__x=right[0], vright__y=right[1], vright__z=right[2],
                    carat__x=carat[0], carat__y=carat[1], carat__z=carat[2],
                    speed=speed, yaw=yaw, drift=drift, lsdm=1,
                    lsdmlim=25.0, tmode=0, t2ts=t2t, prevang=3.0)
        fails += check(name, [("angle", real_ang, got["tang"]),
                              ("err", real_err, got["serr"]),
                              ("prev", real_prev, got["prevang"])], tol=2e-5)
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 3. FUN_00172E80 -- the corner-speed law
# ===========================================================================
CORNER_CASES = [
    # name, target_angle, max_speed, cap, drift_state, boost_flag
    ("straight",             0.0,  88.0, 88.0, 0, 0),
    ("30 deg corner",       30.0,  88.0, 88.0, 0, 0),
    ("60 deg corner",       60.0,  88.0, 88.0, 0, 0),
    ("beyond min-spd angle",120.0, 88.0, 88.0, 0, 0),
    ("negative angle",     -45.0,  88.0, 88.0, 0, 0),
    ("drifting bypasses",   60.0,  88.0, 88.0, 2, 0),
    ("hard cap bites",      10.0,  88.0, 35.0, 0, 0),
    ("boost x1.45",         60.0,  88.0, 88.0, 0, 1),
    ("low ceiling",         20.0,  30.0, 88.0, 0, 0),
]


def run_corner():
    fails = 0
    print("\nFUN_00172E80  corner-speed law:")
    for name, ang, mx, cap, drift, bflag in CORNER_CASES:
        s = ea.Session()
        ea.seed_car(s, drift_state=drift)
        s.wf(AI + 0x9C0, ang)
        s.wf(AI + 0xA08, cap)
        s.wb(AI + 0x213, bflag)
        real = s.call(ea.F_CORNER_SPEED, regs={UC_X86_REG_EAX: AI},
                      stack_args=[ea.f2u(mx)])
        p = probe()
        p.reset()
        got = p.cmd("corner", tang=ang, argmax=mx, cap=cap, drift=drift,
                    bscale=bflag)
        fails += check(name, [("speed", real, got["cspd"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 4. FUN_001724F0 -- the target speed
# ===========================================================================
SPEED_CASES = [
    # name, angle, max_speed, cap, traffic, mode, freefloor, steer_err, drift
    ("racing straight",       0.0, 88.0, 88.0, 0, 1, 0,  0.0, 0),
    ("racing 45 deg",        45.0, 88.0, 88.0, 0, 1, 0,  0.0, 0),
    ("min-speed floor",     150.0, 88.0, 88.0, 0, 1, 0,  0.0, 0),
    ("free floor (no min)", 150.0,  0.0, 88.0, 0, 1, 1,  0.0, 0),
    ("traffic class cap",     0.0, 88.0, 88.0, 1, 1, 0,  0.0, 0),
    ("steer-err cut 4.0",     0.0, 88.0, 88.0, 0, 1, 0,  4.0, 0),
    ("steer-err cut 9.0",     0.0, 88.0, 88.0, 0, 1, 0,  9.0, 0),
    ("steer-err below 1",     0.0, 88.0, 88.0, 0, 1, 0,  0.5, 0),
    ("drift bypass + cut",   60.0, 60.0, 88.0, 0, 1, 0, -3.0, 2),
]


def run_target_speed():
    fails = 0
    print("\nFUN_001724F0  target speed:")
    for (name, ang, mx, cap, traf, mode, ff, serr, drift) in SPEED_CASES:
        s = ea.Session()
        ea.seed_car(s, drift_state=drift)
        s.wi(RC + 0x134C, 0 if traf else 1)
        s.wi(RC + 0x1920, mode)
        s.wi(RC + 0x2450, 1 if ff else 0)
        s.wf(AI + 0x9C0, ang)
        s.wf(AI + 0x780, mx)
        s.wf(AI + 0xA08, cap)
        s.wf(AI + 0x9D4, serr)
        s.wi(AI + 0x790, 0)                # aggression idle -> passthrough
        s.wb(AI + 0xA31, 1)                # catch-up branch off
        s.wf(G := ea.G_TRAFFIC_CAP, 22.352)
        s.call(ea.F_TARGET_SPEED, regs={UC_X86_REG_EAX: AI,
                                        UC_X86_REG_ESI: AI})
        real = s.rf(AI + 0x9C4)
        real_c = s.rf(AI + 0x9D0)
        p = probe()
        p.reset()
        got = p.cmd("tspeed", tang=ang, maxspd=mx, cap=cap, drift=drift,
                    traffic=traf, mode=mode, freefloor=ff, serr=serr,
                    catchup=0.0)
        fails += check(name, [("target", real, got["tspd"]),
                              ("corner", real_c, got["cspd"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
        _ = G
    return fails


# ===========================================================================
# 5. FUN_00105340 -- the driver
# ===========================================================================
DRIVE_DEFAULTS = dict(
    speed=40.0, tspd=40.0, tang=0.0, gear=3, rpm=3000.0, uprpm=6800.0,
    crasht=1.0, arm=-1.0, rev=-1.0, dith=-1.0, prevthr=1.0, bhold=-1.0,
    clock=10.0, traffic=0, boosting=0, rampdone=0, brakesup=0,
    atk=0, atkl=0, atkr=0, atkc=0, wantboost=0, oocw=0, oocm=2, oocc=0,
    sdrift=0, prevsteer=0.0, dt=1.0 / 60.0, revdot=0.0,
)

DRIVE_CASES = [
    ("throttle above band", dict(tspd=60.0)),
    ("coast in band",       dict(tspd=40.5, prevthr=0.0)),
    ("brake 30 mph over",   dict(tspd=10.0, prevthr=0.0)),
    ("brake suppressed",    dict(tspd=10.0, prevthr=0.0, brakesup=1)),
    ("rev-high forces gas", dict(tspd=40.5, prevthr=0.0, rpm=7000.0)),
    ("steer formula",       dict(tang=12.0)),
    ("steer clamp +",       dict(tang=-40.0)),
    ("steer clamp -",       dict(tang=40.0)),
    ("drift lock factor",   dict(tang=4.0, atk=1, atkl=1, atkc=0,
                                 tspd=60.0)),
    ("boost bit set",       dict(boosting=1, tspd=60.0)),
    ("boost commit latch",  dict(boosting=1, rampdone=0, tspd=60.0)),
    ("boost engage req",    dict(wantboost=1, tspd=60.0)),
    ("stuck arms timer",    dict(speed=1.0, tspd=40.0, arm=-1.0)),
    ("stuck arm ticks",     dict(speed=1.0, tspd=40.0, arm=0.5)),
    ("stuck fires reverse", dict(speed=1.0, tspd=40.0, arm=0.01)),
    ("reversing steer +",   dict(rev=1.5, revdot=0.8)),
    ("reversing steer -",   dict(rev=1.5, revdot=-0.8)),
    ("reversing steer 0",   dict(rev=1.5, revdot=0.0)),
    ("reverse ends slow",   dict(rev=0.01, speed=0.05)),
    ("reverse ends fast",   dict(rev=0.01, speed=6.0, gear=-1)),
    ("stop flag under 20mph", dict(tspd=5.0, speed=40.0, prevthr=0.0)),
    ("dither at launch",    dict(speed=4.0, tspd=40.0, prevthr=0.0,
                                 crasht=1.0)),
    ("dither mid-cycle",    dict(speed=4.0, tspd=40.0, prevthr=0.0,
                                 dith=10.5)),
    ("ooc mode 2 authority", dict(oocw=1, oocm=2, tang=20.0)),
    ("ooc mode 0 counter",   dict(oocw=1, oocm=0, oocc=1, tang=20.0)),
    ("ooc mode 1 holds",     dict(oocw=1, oocm=1, tang=20.0, prevsteer=0.3)),
    ("traffic class throttle", dict(traffic=1, tspd=60.0)),
    ("reverse gear brake routing", dict(tspd=10.0, gear=-1, prevthr=0.0)),
]


def _seed_driver(s, cs):
    """Seed the racecar/vehicle so FUN_00105340 sees exactly `cs`."""
    ea.seed_car(s, speed=cs["speed"], drift_state=cs["sdrift"],
                gear=cs["gear"])
    s.wf(ea.G_CLOCK, cs["clock"])
    s.wf(ea.G_DT, cs["dt"])
    s.wf(RC + 0x23C0, cs["tang"])
    s.wf(RC + 0x23C4, cs["tspd"])
    s.wf(RC + 0x190C, cs["crasht"])
    s.wi(RC + 0x134C, 0 if cs["traffic"] else 1)
    s.wf(VEH + 0x1578, cs["arm"])
    s.wf(VEH + 0x157C, cs["rev"])
    s.wf(VEH + 0x1574, cs["dith"])
    s.wf(VEH + 0x156C, cs["prevthr"])
    s.wf(VEH + 0x1570, cs["bhold"])
    s.wf(VEH + 0x1408, cs["prevsteer"])
    s.wf(VEH + 0x1534, 1.0)
    s.wf(VEH + 0x149C, cs["rpm"] / 9.549296)
    s.wf(VEH + 0x1470, cs["uprpm"])
    s.wi(VEH + 0x1524, cs["sdrift"])
    s.wb(RC + 0x2188, cs["atk"])
    s.wb(RC + 0x2413, cs["atkl"])
    s.wb(RC + 0x2414, cs["atkr"])
    s.wb(RC + 0x2415, cs["atkc"])
    s.wb(RC + 0x2419, cs["wantboost"])
    s.wb(RC + 0x11EE, cs["boosting"])
    s.wb(RC + 0x11F1, cs["rampdone"])
    s.wi(RC + 0x2190, 1 if cs["brakesup"] else 0)
    s.wb(RC + 0x2189, 1 if cs["brakesup"] else 0)
    # the OOC window: racecar+0x1198 slam clock + aggressor record
    s.wi(RC + 0x23F8, cs["oocm"])
    if cs["oocw"]:
        s.wf(RC + 0x1598, cs["clock"])           # slammed now
        s.wf(RC + 0x10DC, cs["clock"])
        s.wf(RC + 0x16C0, cs["clock"])           # aggressor contacted now
        s.wu(RC + 0x16BC, ea.OTHER)
        s.wi(ea.OTHER + 0x1920, 0)               # aggressor is a player car
        s.wf(VEH + 0x13E4, 1.0)                  # Total Out-Of-Control Time
    else:
        s.wf(RC + 0x1598, -1.0)
        s.wf(RC + 0x16C0, -1.0)
        s.wu(RC + 0x16BC, 0)
    # the reverse-steer probe FUN_000FF0E0(racecar+0x18E0, frame row0)
    rd = cs["revdot"]
    s.wv(RC + 0x18E0, [rd, 0.0, 0.0, 0.0])
    s.wv(FRAME + 0x00, [1.0, 0.0, 0.0, 0.0])


def run_drive():
    fails = 0
    print("\nFUN_00105340  the AI racer driver:")
    for name, over in DRIVE_CASES:
        cs = dict(DRIVE_DEFAULTS)
        cs.update(over)
        s = ea.Session(clock=cs["clock"], dt=cs["dt"])
        _seed_driver(s, cs)
        # stub the boost-engage gate so "did it request boost" is observable
        s.uc.mem_write(0x0017A5B0, b"\xC7\x05" +
                       struct.pack('<I', ea.OTHER + 0x8000) +
                       b"\x01\x00\x00\x00\xC3")
        s.wu(ea.OTHER + 0x8000, 0)
        # FUN_00198190 (the OOC counter-steer test) returns AL; it is
        # __usercall with one stack argument, so the stub must `ret 4`
        s.uc.mem_write(0x00198190,
                       b"\xB0" + bytes([0 if cs["oocc"] else 1]) +
                       b"\xC2\x04\x00")
        s.call(ea.F_DRIVER, regs={UC_X86_REG_EDI: VEH})
        real = dict(
            thr=s.rf(VEH + 0x1400), brk=s.rf(VEH + 0x1404),
            str=s.rf(VEH + 0x1408), raw=s.rf(VEH + 0x1414),
            bits=float(s.rb(VEH + 0x13FC)),
            stop=float(s.rb(VEH + 0x1552)),
            arm=s.rf(VEH + 0x1578), rev=s.rf(VEH + 0x157C),
            dith=s.rf(VEH + 0x1574), prevthr=s.rf(VEH + 0x156C),
            auth=s.rf(VEH + 0x1534), sdrift=float(s.ri(VEH + 0x1524)),
            gear=float(s.ri(VEH + 0x14C8)),
            eng=float(s.ru(ea.OTHER + 0x8000)),
            commit=float(s.rb(RC + 0x11EF)),
        )
        p = probe()
        p.reset()
        got = p.cmd("drive", **cs)
        # gear_request is a delta in the C contract (0 = leave alone)
        mine_gear = got["gear"] if got["gear"] != 0 else float(cs["gear"])
        pairs = [("thr", real["thr"], got["thr"]),
                 ("brk", real["brk"], got["brk"]),
                 ("steer", real["str"], got["str"]),
                 ("raw", real["raw"], got["raw"]),
                 ("bits", real["bits"], got["bits"]),
                 ("stop", real["stop"], got["stop"]),
                 ("arm", real["arm"], got["arm"]),
                 ("rev", real["rev"], got["rev"]),
                 ("dith", real["dith"], got["dith"]),
                 ("prevthr", real["prevthr"], got["prevthr"]),
                 ("auth", real["auth"], got["auth"]),
                 ("gear", real["gear"], mine_gear),
                 ("engage", real["eng"], got["eng"]),
                 ("commit", real["commit"], got["commit"])]
        fails += check(name, pairs)
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 6. 0x00171078 -- the out-of-range speed governor
# ===========================================================================
GOV_CASES = [
    ("way too fast",  60.0, 134.2, 40.0),
    ("just too fast", 51.0, 114.1, 40.0),
    ("inside band",   42.0,  94.0, 40.0),
    ("slightly slow", 39.9,  89.3, 40.0),
    ("far too slow",  10.0,  22.4, 40.0),
]


def run_governor():
    fails = 0
    print("\n0x00171078  out-of-range mover speed governor:")
    for name, speed, mph, tgt in GOV_CASES:
        s = ea.Session()
        ea.seed_car(s, speed=speed)
        s.wf(VEH + 0xBC, speed)
        s.wf(VEH + 0x13D4, mph)
        s.wf(RC + 0x23C4, tgt)
        s.wf(ea.P_OOR_DEC, ea.VDB[ea.P_OOR_DEC])
        # FUN_001204C0 (the hard speed write) -> capture its XMM0 argument
        s.uc.mem_write(0x001204C0, b"\xF3\x0F\x11\x05" +
                       struct.pack('<I', ea.OTHER + 0x9000) + b"\xC3")
        s.wf(ea.OTHER + 0x9000, -12345.0)
        s.call(ea.F_OOR_MOVER_GOV, regs={UC_X86_REG_EBX: RC,
                                         UC_X86_REG_EAX: VEH},
               frame_ebp=True)
        real = s.rf(ea.OTHER + 0x9000)
        p = probe()
        p.reset()
        got = p.cmd("gov", gspeed=speed, gmph=mph, gtgt=tgt,
                    p__oordec=ea.VDB[ea.P_OOR_DEC])
        fails += check(name, [("commanded", real, got["gov"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 7. FUN_00104CA0 -- the brake helper's gear routing
# ===========================================================================
BRAKE_CASES = [
    ("forward gear", 3, 1.0, 0.0),
    ("reverse gear", -1, 0.0, 1.0),
    ("neutral: no-op", 0, 0.0, 0.0),
]


def run_brake():
    fails = 0
    print("\nFUN_00104CA0  brake helper (reverse routes to throttle):")
    for name, gear, want_brake, want_thr in BRAKE_CASES:
        s = ea.Session()
        ea.seed_car(s, gear=gear)
        s.wf(VEH + 0x1400, 0.0)
        s.wf(VEH + 0x1404, 0.0)
        s.wf(VEH + 0x1414, 0.0)
        s.wf(VEH + 0x1570, -1.0)
        s.call(ea.F_BRAKE_HELPER, regs={UC_X86_REG_ECX: VEH},
               stack_args=[ea.f2u(1.0)])
        real_b = s.rf(VEH + 0x1404)
        real_t = s.rf(VEH + 0x1400)
        p = probe()
        p.reset()
        got = p.cmd("brake", gear=gear, bhold=-1.0, clock=10.0)
        fails += check(name, [("brake", real_b, got["brk"]),
                              ("throttle", real_t, got["thr"]),
                              ("expected brake", want_brake, got["brk"]),
                              ("expected throttle", want_thr, got["thr"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ===========================================================================
# 8. Multi-frame: the slew limiter integrated over a corner entry.
# ===========================================================================
def run_multiframe():
    """Drive the REAL FUN_00171E30 and the C for 60 consecutive frames over a
    swept aim direction, carrying the slew state on both sides."""
    print("\nmulti-frame trajectory (60 frames, swept aim direction):")
    s = ea.Session()
    ea.seed_car(s, speed=45.0)
    s.wb(VEH + 0x1550, 0)
    s.wf(AI + 0x9C8, 1.0)
    s.wf(AI + 0x9CC, 0.0)
    p = probe()
    p.reset()
    p.cmd("angle", speed=45.0, lsdm=0, t2ts=1.0, prevang=0.0,
          fwd__x=0.0, fwd__y=0.0, fwd__z=1.0,
          right__x=1.0, right__y=0.0, right__z=0.0,
          carat__x=0.0, carat__y=0.0, carat__z=1.0,
          ddn__x=0.0, ddn__y=0.0, ddn__z=1.0)
    p.cmd("angle", prevang=0.0)          # reset the limiter memory
    worst = 0.0
    worst_f = -1
    for f in range(60):
        # aim sweeps right then back left: a corner entry and exit
        th = math.radians(70.0 * math.sin(f * math.pi / 30.0))
        dd = [math.sin(th), 0.0, math.cos(th)]
        s.wv(AI + 0x7B0, dd + [0.0])
        s.call(ea.F_TARGET_ANGLE, regs={UC_X86_REG_ESI: AI})
        real = s.rf(AI + 0x9C0)
        got = p.cmd("angle", ddn__x=dd[0], ddn__y=dd[1], ddn__z=dd[2])
        d = abs(real - got["tang"])
        if d > worst:
            worst, worst_f = d, f
    ok = worst < 1e-4
    print("  %-42s %s" % ("60-frame swept aim, slew carried",
                          "OK  (worst |delta| %.3e @ frame %d)"
                          % (worst, worst_f) if ok else
                          "FAIL worst %.4g @ frame %d" % (worst, worst_f)))
    if s.fault:
        print("      (emulation fault: %s)" % s.fault)
        return 1
    return 0 if ok else 1


# ===========================================================================
# 9. Parameter provenance: the AI config values the module ships with are the
#    ones the registrar + Data/vdb.xml resolve to.
# ===========================================================================
def run_param_check():
    print("\nAI/Car parameter provenance (registrar FUN_0016AFD0 + vdb.xml):")
    want = {
        "Out of range speed decrease rate": (0x0047A140, 10.0),
        "Max desDir angle change OOR": (0x0047A144, 1.0),
        "Angle you want min spd at": (0x0047A148, 90.0),
        "Top speed mps": (0x0047A14C, 88.0),
        "Min speed mps": (0x0047A150, 20.0),
        "How much carAt affects steering": (0x0047A154, 0.9),
        "Max lock at 180 x degrees": (0x0047A15C, 10.0),
        "Drift Max lock at 180 x degrees": (0x0047A160, 50.0),
    }
    fails = 0
    p = probe()
    p.reset()
    got = p.cmd("gov")
    _ = got
    # read the module's compiled table back through the probe by asking it to
    # recompute a corner speed that isolates each parameter
    src = open(os.path.join(ROOT, "src", "burnout3_ai.c")).read()
    for name, (addr, val) in want.items():
        ok = ("%g" % val) in src or ("%gf" % val) in src
        print("  %-42s %s" % ("%s = %g (0x%08X)" % (name, val, addr),
                              "OK" if ok else "FAIL (not in module table)"))
        fails += not ok
    return fails




# ===========================================================================
# 10. THE AGGRESSION (ATTACK / SLAM) STATE MACHINE -- docs/RE_AI.md section 14
#
# Ground truth: tools/emulate_ai.AggroSession lays the racecars out at their
# REAL global addresses (DAT_0073A1D0 + i*0x27E0) with the vehicle pointer
# table at DAT_0064B38C, because the machine walks those arrays.  Each case
# seeds Unicorn and the compiled module from the same scenario and diffs.
# ===========================================================================
from unicorn.x86_const import UC_X86_REG_EDX                   # noqa: E402
import struct as _struct  # noqa: E402

CAR_DEFAULT = dict(
    pos=(0.0, 0.0, 0.0), fwd=(0.0, 0.0, 1.0), right=(1.0, 0.0, 0.0),
    speed=45.0, track=100.0, aggression=0.5, width=1.9, length=4.4,
    ooc=-1.0, slammed=-1.0, slammed_by=-1,
    race_time=20.0, boost_start=0.0, race_mode=1, car_class=1,
    mode2450=0, rival=-1, wrecked=0, in_takedown=0, boosting=0,
    progress_zero=0, progress_gate=1, no_slam_speed=0, drift_zone=0,
    node_open=1, steer_ok=1, player_slot=0,
)


def _car(**kw):
    c = dict(CAR_DEFAULT)
    c.update(kw)
    return c


def seed_pair(scn):
    """Build a matched (AggroSession, probe-key-dict) pair from a scenario."""
    cars = scn["cars"]
    clock = scn.get("clock", 20.0)
    dt = scn.get("dt", 1.0 / 60.0)
    s = ea.AggroSession(ncars=len(cars), clock=clock, dt=dt)
    s.wi(ea.G_TRACK_LOADED, scn.get("loaded", 1))
    kv = {"clk": clock, "wdt": dt, "ncars": len(cars),
          "loaded": scn.get("loaded", 1), "selfi": scn.get("self", 0)}
    for i, c in enumerate(cars):
        rc, veh = s.rc(i), s.veh(i)
        s.place(i, c["pos"], c["fwd"], c["right"], c["speed"], c["track"])
        s.wf(rc + 0x23E0, c["aggression"])
        s.wf(rc + 0x2444, c["width"])
        s.wf(rc + 0x2448, c["length"])
        s.wf(rc + 0x1598, c["ooc"])
        s.wf(rc + 0x16C0, c["slammed"])
        s.wu(rc + 0x16BC, s.rc(c["slammed_by"]) if c["slammed_by"] >= 0 else 0)
        s.wf(rc + 0x10DC, c["race_time"])
        s.wf(rc + 0x11C0, c["boost_start"])
        s.wi(rc + 0x1920, c["race_mode"])
        s.wi(rc + 0x134C, c["car_class"])
        s.wi(rc + 0x2450, c["mode2450"])
        s.wi(rc + 0x1650, c["rival"])
        s.wb(rc + 0x18FA, c["wrecked"])
        s.wb(rc + 0x27D8, c["in_takedown"])
        s.wb(rc + 0x11EE, c["boosting"])
        s.wb(rc + 0x2431, c["no_slam_speed"])
        s.wb(rc + 0x1C12, c["drift_zone"])
        s.wb(veh + 0x1550, c["steer_ok"])
        s.wb(veh + 0x1554, c["player_slot"])
        s.wb(ea.A_SECT + 0x100 + i * 10 + 2, 0xFF if c["node_open"] else 0x00)
        # FUN_00194430 (race progress): -1 in +0x135C makes it return 0
        s.wf(rc + 0x135C, -1.0 if c["progress_zero"] else 1.0)
        s.wi(rc + 0x1394, 1 if c["progress_gate"] else 0)
        for k, v in enumerate(c.get("lat", {}).items() if False else []):
            pass
        lat = c.get("lat", [100.0] * len(cars))
        hit = c.get("hit", [-100.0] * len(cars))
        for k in range(len(cars)):
            s.wf(rc + 0x18A4 + k * 4, lat[k])
            s.wf(rc + 0x15E0 + k * 4, hit[k])
            kv["c%d.lat%d" % (i, k)] = lat[k]
            kv["c%d.hit%d" % (i, k)] = hit[k]
        for nm, val in (("pos", c["pos"]), ("fwd", c["fwd"]),
                        ("right", c["right"]), ("rd", c["fwd"])):
            for ax, comp in zip("xyz", val):
                kv["c%d.%s.%s" % (i, nm, ax)] = comp
        kv["c%d.speed_ms" % i] = c["speed"]
        kv["c%d.track_dist" % i] = c["track"]
        kv["c%d.aggression" % i] = c["aggression"]
        kv["c%d.car_width" % i] = c["width"]
        kv["c%d.car_length" % i] = c["length"]
        kv["c%d.ooc_time" % i] = c["ooc"]
        kv["c%d.slammed_time" % i] = c["slammed"]
        kv["c%d.slammed_by" % i] = int(c["slammed_by"])
        kv["c%d.race_time" % i] = c["race_time"]
        kv["c%d.boost_start" % i] = c["boost_start"]
        for f in ("race_mode", "car_class", "mode2450", "rival", "wrecked",
                  "in_takedown", "boosting", "no_slam_speed", "drift_zone",
                  "node_open", "steer_ok", "player_slot", "progress_gate"):
            kv["c%d.%s" % (i, f)] = int(c[f])
        kv["c%d.race_progress_zero" % i] = int(c["progress_zero"])
    return s, kv


def set_agg(s, i, **kw):
    """Poke the retail aggression object directly (state seeding)."""
    a = s.agg(i)
    for k, v in kw.items():
        off = {"state": 0x00, "aim_valid": 0x20, "attacking": 0x21,
               "slam_speed": 0x22, "blocked": 0x23, "hit": 0x24,
               "timer": 0x2C, "entered": 0x30, "side": 0x34,
               "lateral": 0x38, "longitudinal": 0x3C, "can_slam": 0x40,
               "block_range": 0x41, "want_slam_speed": 0x42}[k]
        if k in ("state",):
            s.wi(a + off, v)
        elif k in ("aim_valid", "attacking", "slam_speed", "blocked", "hit",
                   "can_slam", "block_range", "want_slam_speed"):
            s.wb(a + off, v)
        else:
            s.wf(a + off, v)


AGG_KEYS = ("state", "aimv", "att", "ss", "blocked", "timer", "side",
            "lat", "lon", "cs", "br", "wss", "tgt",
            "aim.x", "aim.y", "aim.z")


def agg_real(s, i, kv_state):
    d = s.agg_dump(i)
    tgt = -1
    if d["target"]:
        tgt = (d["target"] - ea.G_RC_ARRAY) // ea.RC_STRIDE
    return {"state": d["state"], "aimv": d["aim_valid"], "att": d["attacking"],
            "ss": d["slam_speed"], "blocked": d["blocked"], "timer": d["timer"],
            "side": d["side"], "lat": d["lateral"], "lon": d["longit"],
            "cs": d["can_slam"], "br": d["block_range"],
            "wss": d["want_slam_speed"], "tgt": tgt,
            "aim.x": d["aim"][0], "aim.y": d["aim"][1], "aim.z": d["aim"][2]}


# --- the scenario table -----------------------------------------------------
def _pair(dx, dz, **kw):
    """attacker at the origin, victim offset (dx, dz)."""
    a = dict(kw.pop("a", {}))
    b = dict(kw.pop("b", {}))
    lat = [100.0, abs(dx)]
    return dict(cars=[_car(pos=(0.0, 0.0, 0.0), lat=lat, **a),
                      _car(pos=(dx, 0.0, dz), lat=[abs(dx), 100.0], **b)],
                **kw)


AGGRO_CASES = [
    # name, scenario, aggression-object seed, ops
    ("idle: acquire a target",
     _pair(3.0, 2.0), dict(state=0, timer=-1.0), None),
    ("idle: aggression below the threshold",
     _pair(3.0, 2.0, a=dict(aggression=0.0)), dict(state=0, timer=-1.0), None),
    ("idle: target too slow (< 75 mph)",
     _pair(3.0, 2.0, b=dict(speed=20.0)), dict(state=0, timer=-1.0), None),
    ("idle: target 200 m ahead (out of range)",
     _pair(3.0, 2.0, b=dict(track=300.0)), dict(state=0, timer=-1.0), None),
    ("idle: target 60 m behind (out of range)",
     _pair(3.0, 2.0, b=dict(track=40.0)), dict(state=0, timer=-1.0), None),
    ("idle: target wrecked",
     _pair(3.0, 2.0, b=dict(wrecked=1)), dict(state=0, timer=-1.0), None),
    ("approach -> slam (lateral 3 m)",
     _pair(3.0, 2.0), dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("approach -> steer out (lateral 1.5 m)",
     _pair(1.5, 2.0), dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("approach: victim 30 m ahead -> positioning aim",
     _pair(3.0, 30.0, b=dict(track=130.0)),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("steer-out aim (5 m clear, 0.15 s lead)",
     _pair(1.5, 2.0), dict(state=3, timer=50.0, side=-1.0, target=1), None),
    ("steer-out expiry -> slam",
     _pair(1.5, 2.0), dict(state=3, timer=1.0, side=-1.0, target=1), None),
    ("SLAM aim = victim + fwd x speed x 0.1",
     _pair(3.0, 2.0), dict(state=4, timer=50.0, side=-1.0, target=1), None),
    ("slam: wrong side -> abandon",
     _pair(3.0, 2.0), dict(state=4, timer=50.0, side=1.0, target=1), None),
    ("slam: cannot slam (lateral 12 m) -> cooldown",
     _pair(12.0, 2.0), dict(state=4, timer=50.0, side=-1.0, target=1), None),
    ("slam: contact -> recoil, side flips",
     _pair(3.0, 2.0), dict(state=4, timer=50.0, side=-1.0, hit=1, target=1),
     None),
    ("slam expiry -> cooldown",
     _pair(3.0, 2.0), dict(state=4, timer=1.0, side=-1.0, target=1), None),
    ("recoil aim (away from the victim)",
     _pair(3.0, 2.0), dict(state=6, timer=50.0, side=1.0, target=1), None),
    ("cooldown expiry -> idle",
     _pair(3.0, 2.0), dict(state=5, timer=1.0, side=-1.0, target=1), None),
    ("cooldown still running",
     _pair(3.0, 2.0), dict(state=5, timer=100.0, side=-1.0, target=1), None),
    ("block: aim in front of the victim",
     _pair(2.0, -6.0, b=dict(track=94.0)),
     dict(state=7, timer=50.0, side=-1.0, target=1), None),
    ("block out of range -> approach",
     _pair(2.0, -40.0, b=dict(track=60.0)),
     dict(state=7, timer=50.0, side=-1.0, target=1), None),
    ("retaliation: designated rival",
     _pair(3.0, 2.0, a=dict(rival=1)),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("immunity: hit something 1 s ago",
     _pair(3.0, 2.0, a=dict(hit=[-100.0, 19.5])),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("traffic class never attacks",
     _pair(3.0, 2.0, a=dict(car_class=0)), dict(state=0, timer=-1.0), None),
    ("player car never attacks",
     _pair(3.0, 2.0, a=dict(race_mode=0)), dict(state=0, timer=-1.0), None),
    ("can-slam: target 40 mph faster (inside the 50 mph window)",
     _pair(3.0, 2.0, b=dict(speed=63.0)),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("can-slam: target 60 mph faster (outside)",
     _pair(3.0, 2.0, b=dict(speed=72.0)),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("can-slam: victim 6 m ahead (outside the 3.5 m window)",
     _pair(3.0, 6.0), dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("can-slam: off the lane (cos 0.5 < 0.8)",
     _pair(3.0, 2.0, a=dict(fwd=(0.8660254, 0.0, 0.5))),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("slam-speed: victim boosting",
     _pair(1.5, 2.0, b=dict(boosting=1)),
     dict(state=1, timer=50.0, side=-1.0, target=1), None),
    ("aim gate closed (out of control 1 s ago)",
     _pair(3.0, 2.0, a=dict(ooc=19.5)),
     dict(state=4, timer=50.0, side=-1.0, target=1), None),
    ("aim gate: junction node + drift zone",
     _pair(3.0, 2.0, a=dict(node_open=0, drift_zone=1)),
     dict(state=4, timer=50.0, side=-1.0, target=1), None),
]


def run_aggro():
    print("\nAggression state machine (FUN_00169540 family):")
    fails = 0
    p = probe()
    for name, scn, seed, _ in AGGRO_CASES:
        s, kv = seed_pair(scn)
        s.agg_init(0)
        tgt = seed.pop("target", None)
        set_agg(s, 0, **seed)
        if tgt is not None:
            s.wu(s.agg(0) + 0x48, s.rc(tgt))
        s.call(ea.F_AGG_UPDATE, regs={UC_X86_REG_EAX: s.agg(0)})
        if s.fault:
            print("  %-42s FAIL unicorn %s" % (name, s.fault))
            fails += 1
            continue
        real = agg_real(s, 0, kv)
        p.reset()
        p.cmd_kv("agginit", kv)
        pk = dict(kv)
        for k, v in seed.items():
            pk["a." + {"state": "state", "aim_valid": "aimv",
                       "attacking": "att", "slam_speed": "ss",
                       "blocked": "blocked", "hit": "hit", "timer": "timer",
                       "entered": "entered", "side": "side",
                       "lateral": "lat", "longitudinal": "lon",
                       "can_slam": "cs", "block_range": "br",
                       "want_slam_speed": "wss"}[k]] = v
        if tgt is not None:
            pk["a.tgt"] = tgt
        got = p.cmd_kv("aggupd", pk)
        pairs = [(k, float(real[k]), got[k.replace(".", ".")]) for k in AGG_KEYS]
        fails += check(name, pairs, tol=1e-5)
    return fails


# ===========================================================================
# 11. The three channels the aggression machine drives:
#     FUN_0016AF10  aggro flags -> AI+0x790 mode / AI+0x794 target
#     FUN_00172FA0  the aggression speed demand (inside FUN_001724F0)
#     FUN_00171D90  AI+0xA17/+0xA18 -> AI+0xA19 (the driver's wants-boost)
#     FUN_00171BE0  the drift-lock flags racecar+0x2413/+0x2414/+0x2415
# ===========================================================================
ARB_CASES = [
    ("arbitrate: idle -> mode 0",
     _pair(3.0, 2.0), dict(attacking=0, slam_speed=0), 1),
    ("arbitrate: attacking, target at 100 mph -> mode 4",
     _pair(3.0, 2.0, b=dict(speed=45.0)), dict(attacking=1, slam_speed=0), 1),
    ("arbitrate: attacking + slam_speed -> mode 5",
     _pair(3.0, 2.0, b=dict(speed=45.0)), dict(attacking=1, slam_speed=1), 1),
    ("arbitrate: target below 100 mph, not a rival -> mode 0",
     _pair(3.0, 2.0, b=dict(speed=30.0)), dict(attacking=1, slam_speed=0), 1),
    ("arbitrate: target below 100 mph but it IS our rival -> mode 4",
     _pair(3.0, 2.0, a=dict(rival=1), b=dict(speed=30.0)),
     dict(attacking=1, slam_speed=0), 1),
    ("arbitrate: target boosting -> mode 0",
     _pair(3.0, 2.0, b=dict(speed=45.0, boosting=1)),
     dict(attacking=1, slam_speed=0), 1),
]


def run_aggro_consume():
    print("\nAggression -> driver channels (FUN_0016AF10 / 172FA0 / 171D90):")
    fails = 0
    p = probe()

    # --- FUN_0016AF10 -------------------------------------------------------
    for name, scn, seed, tgt in ARB_CASES:
        s, kv = seed_pair(scn)
        s.agg_init(0)
        set_agg(s, 0, **seed)
        s.wu(s.agg(0) + 0x48, s.rc(tgt))
        s.call(ea.F_AGG_SETSTATE, regs={UC_X86_REG_ECX: s.ai(0)})
        rmode = s.ri(s.ai(0) + 0x790)
        rtgt = s.ru(s.ai(0) + 0x794)
        rtgt = ((rtgt - ea.G_RC_ARRAY) // ea.RC_STRIDE) if rtgt else -1
        pk = dict(kv)
        pk["a.att"] = seed["attacking"]
        pk["a.ss"] = seed["slam_speed"]
        pk["a.tgt"] = tgt
        got = p.cmd_kv("aggarb", pk)
        if rmode == 0:
            rtgt = -1
        fails += check(name, [("mode", float(rmode), got["smode"]),
                              ("target", float(rtgt), got["stgt"])])

    # --- FUN_00172FA0 -------------------------------------------------------
    SPD_CASES = [
        ("speed: mode 0 passes the corner speed through",
         _pair(3.0, 20.0, b=dict(track=120.0)), 0, 60.0, {}),
        ("speed: mode 3 -> the target's speed",
         _pair(3.0, 20.0, b=dict(track=120.0, speed=33.0)), 3, 60.0, {}),
        ("speed: mode 1, target ahead -> the target's speed",
         _pair(3.0, 20.0, b=dict(track=120.0, speed=33.0)), 1, 60.0, {}),
        ("speed: mode 1, target behind -> pass through",
         _pair(3.0, -20.0, b=dict(track=80.0, speed=33.0)), 1, 60.0, {}),
        ("speed: mode 2, target behind -> the target's speed",
         _pair(3.0, -20.0, b=dict(track=80.0, speed=33.0)), 2, 60.0, {}),
        ("speed: mode 5 locks to own speed +-1",
         _pair(3.0, 4.0, b=dict(track=104.0, speed=33.0)), 5, 60.0, {}),
        ("speed: mode 5, victim boosting 2 s -> arms the boost",
         _pair(3.0, 4.0, b=dict(track=104.0, speed=33.0, boosting=1,
                                boost_start=18.0)), 5, 60.0, {}),
        ("speed: mode 4, new target -> pass through",
         _pair(3.0, 20.0, b=dict(track=120.0, speed=33.0)), 4, 60.0, {}),
        ("speed: mode 4, target ahead -> top speed + boost",
         _pair(3.0, 20.0, b=dict(track=120.0, speed=33.0)), 4, 60.0,
         dict(last=1)),
        ("speed: mode 4, target 4 m behind -> close-range match",
         _pair(3.0, -4.0, b=dict(track=96.0, speed=33.0)), 4, 60.0,
         dict(last=1)),
        ("speed: mode 4, target 30 m behind -> 0.9x slow-down",
         _pair(3.0, -30.0, b=dict(track=70.0, speed=33.0)), 4, 60.0,
         dict(last=1)),
        ("speed: mode 4, the PLAYER hit us 0.5 s ago -> no boost/top speed",
         _pair(3.0, 20.0, a=dict(slammed=19.5, slammed_by=1),
               b=dict(track=120.0, speed=33.0, race_mode=0)), 4, 60.0,
         dict(last=1)),
        ("speed: mode 4, an AI hit us 0.5 s ago -> unaffected",
         _pair(3.0, 20.0, a=dict(slammed=19.5, slammed_by=1),
               b=dict(track=120.0, speed=33.0)), 4, 60.0, dict(last=1)),
        ("speed: mode 4 chase-the-player variant (rc+0x2450 = 1)",
         _pair(3.0, 20.0, a=dict(mode2450=1), b=dict(track=120.0, speed=33.0)),
         4, 60.0, dict(last=1, ahead=1)),
    ]
    for name, scn, mode, spdin, extra in SPD_CASES:
        s, kv = seed_pair(scn)
        ai = s.ai(0)
        s.wi(ai + 0x790, mode)
        s.wu(ai + 0x794, s.rc(1))
        s.wi(ai + 0xA1C, s.rc(1) if extra.get("last") else 0)
        s.wb(ai + 0xA30, 1 if extra.get("ahead") else 0)
        s.wb(ai + 0xA17, 0)
        s.wb(ai + 0xA18, 0)
        s.wb(ai + 0xA19, 0)
        s.wf(ai + 0xA2C, -1.0)
        s.wf(ai + 0xA28, 0.0)
        s.wf(ai + 0x9E0, scn["cars"][0]["aggression"])
        real = s.call(ea.F_AGG_SPEED, regs={UC_X86_REG_ESI: ai},
                      stack_args=(struct.unpack('<I', struct.pack('<f', spdin))[0],))
        if s.fault:
            print("  %-42s FAIL unicorn %s" % (name, s.fault))
            fails += 1
            continue
        rwb = s.rb(ai + 0xA17)
        pk = dict(kv)
        pk["s.mode"] = mode
        pk["s.tgt"] = 1
        pk["s.last"] = 1 if extra.get("last") else -1
        pk["s.ahead"] = 1 if extra.get("ahead") else 0
        pk["s.wb"] = 0
        pk["s.bn"] = 0
        pk["s.wants"] = 0
        pk["s.buntil"] = -1.0
        pk["s.brearm"] = 0.0
        pk["spdin"] = spdin
        pk["aggro"] = scn["cars"][0]["aggression"]
        got = p.cmd_kv("aggspd", pk)
        fails += check(name, [("speed", real, got["spdout"]),
                              ("want_boost", float(rwb), got["swb"])])

    # --- FUN_00171D90 -------------------------------------------------------
    LATCH_CASES = [
        ("boost latch: nothing armed", 0, 0, -1.0),
        ("boost latch: want_boost this frame", 1, 0, -1.0),
        ("boost latch: inside the 2 s window", 0, 0, 25.0),
        ("boost latch: window just expired", 0, 0, 19.0),
    ]
    for name, wb, bn, until in LATCH_CASES:
        s, kv = seed_pair(_pair(3.0, 2.0))
        ai = s.ai(0)
        s.wb(ai + 0xA17, wb)
        s.wb(ai + 0xA18, bn)
        s.wb(ai + 0xA19, 0)
        s.wf(ai + 0xA2C, until)
        s.wu(s.rc(0) + 0x11D0, ea.A_SECT + 0x8000)
        s.call(ea.F_AGG_BOOST, regs={UC_X86_REG_EDI: ai})
        real = (s.rb(ai + 0xA19), s.rf(ai + 0xA2C))
        pk = dict(kv)
        pk["s.wb"] = wb
        pk["s.bn"] = bn
        pk["s.wants"] = 0
        pk["s.buntil"] = until
        got = p.cmd_kv("boostlatch", pk)
        fails += check(name, [("wants_boost", float(real[0]), got["swants"]),
                              ("window", real[1], got["sbuntil"])])

    # --- FUN_00171BE0 -------------------------------------------------------
    DRIFT_CASES = [
        ("drift flags: disabled", 0, 4, -30.0, (0.0, 0.0, 40.0)),
        ("drift flags: mode 4, angle -30 -> left + commit", 1, 4, -30.0,
         (-20.0, 0.0, 40.0)),
        ("drift flags: mode 4, angle -5 -> left, no commit", 1, 4, -5.0,
         (-20.0, 0.0, 400.0)),
        ("drift flags: mode 2, angle +30 -> right + commit", 1, 2, 30.0,
         (20.0, 0.0, 40.0)),
        ("drift flags: mode 2, angle -30 -> nothing", 1, 2, -30.0,
         (20.0, 0.0, 40.0)),
        ("drift flags: mode 0 -> nothing", 1, 0, -30.0, (-20.0, 0.0, 40.0)),
        ("drift flags: wrong side of the aim -> no commit", 1, 4, -30.0,
         (20.0, 0.0, 40.0)),
    ]
    for name, en, mode, ang, aim in DRIFT_CASES:
        s, kv = seed_pair(_pair(3.0, 2.0))
        ai = s.ai(0)
        s.wb(ai + 0x788, en)
        s.wi(ai + 0x1F4, mode)
        s.wf(ai + 0x9C0, ang)
        s.wv(ai + 0x200, list(aim) + [1.0])
        s.wb(ai + 0xA13, 0)
        s.wb(ai + 0xA14, 0)
        s.wb(ai + 0xA15, 0)
        s.call(ea.F_DRIFT_FLAGS, regs={UC_X86_REG_ESI: ai})
        if s.fault:
            print("  %-42s FAIL unicorn %s" % (name, s.fault))
            fails += 1
            continue
        real = (s.rb(ai + 0xA13), s.rb(ai + 0xA14), s.rb(ai + 0xA15))
        pk = dict(kv)
        pk["d.enable"] = en
        pk["d.mode"] = mode
        pk["d.ang"] = ang
        pk["d.speed"] = 45.0
        pk["d.aim.x"], pk["d.aim.y"], pk["d.aim.z"] = aim
        pk["d.pos.x"] = pk["d.pos.y"] = pk["d.pos.z"] = 0.0
        pk["d.fwd.x"], pk["d.fwd.y"], pk["d.fwd.z"] = 0.0, 0.0, 1.0
        pk["p.apex"] = 1.0
        pk["d.l"] = pk["d.r"] = pk["d.c"] = 0
        got = p.cmd_kv("driftflags", pk)
        fails += check(name, [("left", float(real[0]), got["dl"]),
                              ("right", float(real[1]), got["dr"]),
                              ("commit", float(real[2]), got["dc"])])
    return fails


AGGRO_CONSUME_N = 6 + 14 + 4 + 7


# ===========================================================================
# 12. A whole attack CYCLE, frame by frame, with the state carried on both
#     sides: idle -> approach -> steer out -> slam -> contact -> recoil ->
#     cooldown -> idle.  240 frames at 60 Hz.
# ===========================================================================
def run_aggro_cycle():
    print("\nAggression 240-frame cycle (state carried on both sides):")
    p = probe()
    clock0 = 20.0
    dt = 1.0 / 60.0
    scn = _pair(6.0, 2.0, b=dict(track=102.0, speed=44.0))
    s, kv = seed_pair(dict(scn, clock=clock0, dt=dt))
    s.agg_init(0)
    set_agg(s, 0, state=0, timer=-1.0)
    p.reset()
    p.cmd_kv("agginit", kv)
    pk = dict(kv)
    pk["a.state"] = 0
    pk["a.timer"] = -1.0
    worst = 0.0
    bad = []
    lat = 6.0
    for f in range(240):
        clk = clock0 + f * dt
        # close in laterally, then bump at frame 120
        if f > 20 and lat > 1.0:
            lat -= 0.05
        hit = 1 if f == 120 else 0
        for i in (0, 1):
            s.wf(s.rc(i) + 0x10DC, clk)
        s.wf(ea.G_CLOCK, clk)
        s.place(1, (lat, 0.0, 2.0), speed=44.0, track=102.0)
        s.wf(s.rc(0) + 0x18A4 + 1 * 4, lat)
        s.wb(s.agg(0) + 0x24, hit)
        s.call(ea.F_AGG_UPDATE, regs={UC_X86_REG_EAX: s.agg(0)})
        if s.fault:
            bad.append("frame %d unicorn %s" % (f, s.fault))
            break
        real = agg_real(s, 0, kv)
        pk = dict(kv)
        pk["clk"] = clk
        pk["c0.race_time"] = clk
        pk["c1.race_time"] = clk
        pk["c1.pos.x"] = lat
        pk["c0.lat1"] = lat
        pk["a.hit"] = hit
        if f == 0:                       # carry the same initial seed
            pk["a.state"] = 0
            pk["a.timer"] = -1.0
        got = p.cmd_kv("aggupd", pk)
        # the module keeps its own state; only the scenario is re-fed
        for k in AGG_KEYS:
            d = abs(float(real[k]) - got[k])
            if d > worst:
                worst = d
            if d > 1e-4:
                bad.append("frame %d %s %.7g != %.7g"
                           % (f, k, got[k], float(real[k])))
        if bad:
            break
    print("  %-42s %s" % ("240-frame attack cycle (worst |delta| %.3g)" % worst,
                          "OK" if not bad else "FAIL " + "; ".join(bad[:3])))
    return 1 if bad else 0


# ===========================================================================
# 13. Parameter provenance for the AI/Aggressive Driving block.
# ===========================================================================
AGGRO_PARAMS = [
    ("Min. aggression before we start attacking", 0x0047A204, 0.002,
     "min_aggression"),
    ("Max. time to wait between attacks (seconds)", 0x0047A20C, 3.0,
     "max_wait_s"),
    ("Max. distance apart to begin attacking when ahead", 0x0047A210, 40.0,
     "dist_ahead_m"),
    ("Max. distance apart to begin attacking when behind", 0x0047A214, 150.0,
     "dist_behind_m"),
    ("Min. target speed to consider attacking (mph)", 0x0047A218, 75.0,
     "min_target_mph"),
    ("How much slower than the player to drive", 0x0047A21C, 0.9,
     "slow_factor"),
    ("How far in front to boost when speed matching", 0x0047A220, 15.0,
     "boost_dist_m"),
    ("Extra distance in front to boost relative to aggression", 0x0047A224,
     -22.5, "boost_aggro_m"),
    ("How long to wait at the start of the race", 0x0047A228, 3.0,
     "start_delay_s"),
    ("How long after hitting something to disable immunity", 0x0047A22C, 3.0,
     "immunity_s"),
    ("Slam: Min time to try and block you for", 0x0047A230, 3.0, "block_min_s"),
    ("Slam: Max time to try and block you for", 0x0047A234, 15.0,
     "block_max_s"),
    ("Slam: Max distance ahead to start blocking you", 0x0047A238, 15.0,
     "block_dist_m"),
    ("Slam: Max. time to get into slamming position", 0x0047A240, 30.0,
     "position_time_s"),
    ("Slam: Max. distance between cars, when ahead", 0x0047A244, 3.5,
     "ahead_gap_m"),
    ("Slam: Max. difference in speeds (MPH)", 0x0047A248, 50.0,
     "speed_diff_mph"),
    ("Slam: Steer out distance (meters)", 0x0047A24C, 5.0, "steer_out_m"),
    ("Slam: Steer out time (seconds)", 0x0047A250, 0.5, "steer_out_s"),
    ("Slam: Slam time (seconds)", 0x0047A254, 0.75, "slam_s"),
    ("Slam: Max. cos angle off lane to stop attack", 0x0047A258, 0.8,
     "max_cos_off_lane"),
]


def run_aggro_params():
    print("\nAI/Aggressive Driving parameter provenance "
          "(registrar FUN_0016AFD0 + vdb.xml):")
    fails = 0
    src = open(os.path.join(ROOT, "src", "burnout3_ai.c")).read()
    blk = src[src.index("B3AiAggroParams b3_ai_aggro_params ="):]
    blk = blk[:blk.index("};")]
    for name, addr, val, field in AGGRO_PARAMS:
        want = "/* %s" % field
        ok = False
        for line in blk.splitlines():
            if line.strip().startswith("/* %s" % field):
                txt = line.split("*/", 1)[1].strip().rstrip(",")
                try:
                    ok = abs(float(txt.rstrip("f")) - val) < 1e-9
                except ValueError:
                    ok = False
        print("  %-42s %s" % ("%s = %g (0x%08X)" % (field, val, addr),
                              "OK" if ok else "FAIL (module has a different "
                                              "value for %s)" % field))
        _ = want
        fails += not ok
    return fails


# ===========================================================================
# ===========================================================================
# 15. section 16 -- the route driver's wheel + watchdogs
#     FUN_0018CB60 (handover), FUN_00170820's head (the route-alternation
#     square wave), FUN_00176150 (the corner-brake law).
# ===========================================================================
F_WHEEL_SET = 0x0018CB60         # the racecar+0x27D8 handover
F_ROUTE_ALT_HEAD = 0x00170820    # FUN_00170820's first block
F_ROUTE_ALT_END = 0x0017089C     # ... ends where FUN_0018D790 is called
F_CORNER_BRAKE = 0x00176150      # -> AI+0x1D0
F_APPROACH = 0x00174AF0          # the projection FUN_00176150 feeds in
F_NODE_SEEK = 0x00174A90         # its companion, no output we need
G_ALT_RELOAD = 0x003B16B8        # 50.0
G_CB_ZERO = 0x003B16E0           # 0.0   (the "corner speed <= 0" test)
G_CB_BOOST = 0x003A2C44          # 1.02  (AI+0x213 scale)
G_BRAKE_FACTOR = 0x0047A1CC      # AI/Target Dist to brake speed factor

# on / expected edge (0 none, 1 take, 2 give)
WHEEL_CASES = [
    ("take from idle",        0, 1, 1),
    ("take again (no edge)",  1, 1, 0),
    ("give back",             1, 0, 2),
    ("give again (no edge)",  0, 0, 0),
]


def _wheel_seed(s):
    """FUN_00179760 walks the aggression sub-object through aggro+0x1B4."""
    s.wu(RC + 0x1BB4, RC)                       # aggro+0x44 = own racecar
    s.wu(RC + 0x1BB8, 0)                        # aggro+0x48 = no target
    s.wf(ea.G_CLOCK, 10.0)


def run_wheel():
    """FUN_0018CB60: the +0x27D8 edge, the give-back authority restore, and
    (asserted on the real side only, because the harness caller does it) the
    take-side direction-block zero + navigator invalidate."""
    fails = 0
    print("\nFUN_0018CB60  AI-wheel handover:")
    for name, before, on, want_edge in WHEEL_CASES:
        s = ea.Session()
        ea.seed_car(s)
        _wheel_seed(s)
        s.wb(RC + 0x27D8, before)
        s.wf(VEH + 0x1534, 0.05)                # crushed OOC authority
        s.wi(VEH + 0x1524, 4)                   # drift state 4
        for k in range(4):
            s.wf(RC + 0x19D0 + k * 4, 7.0)
        s.wu(RC + 0x1BD8, 0x1234)               # navigator +0x1D8
        s.call(F_WHEEL_SET, regs={UC_X86_REG_EAX: RC,
                                  UC_X86_REG_ECX: on & 0xFF})
        real_flag = s.rb(RC + 0x27D8)
        real_auth = s.rf(VEH + 0x1534)
        real_drift = s.ri(VEH + 0x1524)
        real_dir = max(abs(s.rf(RC + 0x19D0 + k * 4)) for k in range(4))
        real_nav = s.ru(RC + 0x1BD8) & 0xFFFF

        p = probe()
        p.reset()
        p.cmd("winit", ownode=0)
        got = p.cmd_kv("wheel", {"w.wheel": before, "on": on,
                                 "auth": 0.05, "sdrift": 4})
        # the C carries the same state the real function does on the give side
        pairs = [("flag", float(real_flag), got["wheel"]),
                 ("edge", float(want_edge), got["edge"])]
        if want_edge == 2:
            pairs += [("authority", real_auth, got["auth"]),
                      ("drift state", float(real_drift), got["sdrift"])]
        if want_edge == 1:
            # the real function's take-side side effects, which the harness
            # caller (nav_replace_car / the td-wheel block) reproduces
            pairs += [("dir block zeroed", 0.0, real_dir),
                      ("navigator invalidated", 65535.0, float(real_nav))]
        fails += check(name, pairs)
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# flag, t0, t1, dt   -- the two 50 s countdowns and the AI+0x1F0 they drive
ALT_CASES = [
    ("flag 1, mid-count",     1, 50.0, 30.0, 1.0 / 60.0),
    ("flag 1, expiring",      1, 50.0, 0.008, 1.0 / 60.0),
    ("flag 0, mid-count",     0, 30.0, 50.0, 1.0 / 60.0),
    ("flag 0, expiring",      0, 0.008, 50.0, 1.0 / 60.0),
    ("flag 1, exact zero",    1, 50.0, 1.0 / 60.0, 1.0 / 60.0),
    ("flag 0, big dt",        0, 0.5, 50.0, 1.0),
]


def run_route_alt():
    """FUN_00170820 @0x00170827..0x0017089C -- the 50 s / 50 s square wave on
    AI+0x1F0 that gates FUN_00178310's type-1/type-3 selector span."""
    fails = 0
    print("\nFUN_00170820 head  route-alternation square wave:")
    for name, flag, t0, t1, dt in ALT_CASES:
        s = ea.Session(dt=dt)
        ea.seed_car(s)
        s.wf(G_ALT_RELOAD, 50.0)
        s.wb(RC + 0x1BF0, flag)
        s.wf(RC + 0x1BE4, t0)
        s.wf(RC + 0x1BE8, t1)
        s.uc.reg_write(UC_X86_REG_ECX, RC)
        s.uc.reg_write(UC_X86_REG_ESP, ea.STACK_BASE + ea.STACK_SIZE - 0x2000)
        try:
            s.uc.emu_start(F_ROUTE_ALT_HEAD, F_ROUTE_ALT_END, count=4000)
        except Exception as e:                                  # noqa: BLE001
            s.fault = str(e)
        real = (s.rb(RC + 0x1BF0), s.rf(RC + 0x1BE4), s.rf(RC + 0x1BE8))

        p = probe()
        p.reset()
        p.cmd("winit", ownode=0)
        got = p.cmd_kv("ralt", {"w.alt": flag, "w.t0": t0, "w.t1": t1,
                                "dt": dt})
        fails += check(name, [("flag", float(real[0]), got["alt"]),
                              ("t0", real[1], got["t0"]),
                              ("t1", real[2], got["t1"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# name, corner speed AI+0x298, AI+0x1FC, AI+0x1F8, AI+0x213, cap, injected D
CBRAKE_CASES = [
    ("mode 1FC set -> hard cap",   30.0, 1, 0, 0, 88.0,  0.0),
    ("corner speed 0 -> hard cap",  0.0, 0, 0, 0, 88.0,  0.0),
    ("target mode 2 -> cs direct", 30.0, 0, 2, 0, 88.0,  0.0),
    ("target mode 2 + boost x1.02",30.0, 0, 2, 1, 88.0,  0.0),
    ("mode 2, cs above the cap",   99.0, 0, 2, 0, 88.0,  0.0),
    ("mode 0, corner 40 m ahead",  30.0, 0, 0, 0, 88.0, -40.0),
    ("mode 0, on the node",        30.0, 0, 0, 0, 88.0,   0.0),
    ("mode 0, past the node",      30.0, 0, 0, 0, 88.0,   6.0),
    ("mode 0, capped",             30.0, 0, 0, 0, 45.0, -40.0),
    ("mode 0 + boost scale",       30.0, 0, 0, 1, 88.0, -40.0),
]

# a 12-byte stub for FUN_00174AF0: MOVSS XMM0,[imm32] ; RET 8
STUB_D = 0x005B0000


def _stub_approach(s, d):
    """FUN_00174AF0 needs the live .bgd graph; the arithmetic under test is
    FUN_00176150's, so inject its result.  MOVSS XMM0,[STUB_D]; RET 8 --
    the callee-cleanup count is the real function's own (`RET 0x8`)."""
    s.wf(STUB_D, d)
    code = b"\xF3\x0F\x10\x05" + struct.pack("<I", STUB_D) + b"\xC2\x08\x00"
    s.uc.mem_write(F_APPROACH, code)
    s.uc.mem_write(F_NODE_SEEK, b"\xC3")        # its companion: plain RET


def run_corner_brake():
    """FUN_00176150 -> AI+0x1D0, the corner-BRAKE law."""
    fails = 0
    print("\nFUN_00176150  corner-brake law:")
    for name, cs, m1fc, mode, bscale, cap, d in CBRAKE_CASES:
        s = ea.Session()
        ea.seed_car(s)
        s.wf(G_CB_ZERO, 0.0)
        s.wf(G_CB_BOOST, 1.02)
        s.wf(G_BRAKE_FACTOR, 0.6)
        s.wf(AI + 0x298, cs)
        s.wi(AI + 0x1FC, m1fc)
        s.wi(AI + 0x1F8, mode)
        s.wb(AI + 0x213, bscale)
        s.wf(RC + 0x2408, cap)
        s.wu(AI + 0x1D4, ea.OTHER)              # section pointer (stubbed use)
        s.wu(AI + 0x1D8, 0)
        _stub_approach(s, d)
        s.call(F_CORNER_BRAKE, regs={UC_X86_REG_EDI: AI})
        real = s.rf(AI + 0x1D0)

        p = probe()
        p.reset()
        got = p.cmd_kv("cbrake", {"cs": cs, "cbd": d, "cbcap": cap,
                                  "cbmode": mode, "cb1fc": m1fc,
                                  "cbbs": bscale})
        fails += check(name, [("AI+0x1D0", real, got["cbout"])])
        if s.fault:
            print("      (emulation fault: %s)" % s.fault)
            fails += 1
    return fails


# ---------------------------------------------------------------------------
# The two watchdog counters have no separate retail function to diff against
# (they are inline in FUN_001712E0 / FUN_0018D790 / FUN_00170820, mixed with
# the .bgd graph reads), so these assert the ported C against the CONSTANTS
# and the branch structure read out of those three call sites.
# ---------------------------------------------------------------------------
WATCHDOG_CASES = [
    # (name, [(dy, expect_fire, expect_below, expect_lastnode)], ...)
    ("above the road latches the node", [(0.5, 0, 0, 11)]),
    ("shallow dip clears the counter",  [(-3.0, 0, 0, 0)]),
    ("deep drop counts",                [(-6.0, 0, 1, 0)]),
]


def run_watchdogs():
    """FUN_001712E0's -1 m latch / -5 m 61-frame drop, and FUN_00170820's
    200-frame nav-walk-failure rescue."""
    fails = 0
    print("\nFUN_001712E0 / FUN_00170820  watchdogs:")
    p = probe()

    # 1. the -1 m latch
    p.reset()
    p.cmd("winit", ownode=0)
    got = p.cmd_kv("offworld", {"ownode": 11, "owdy": 0.5})
    fails += check("dy > -1 latches the last valid node",
                   [("fired", 0.0, got["owfired"]),
                    ("below", 0.0, got["below"]),
                    ("lastnode", 11.0, got["lastnode"])])

    # 2. the -1..-5 band clears the counter
    p.reset()
    p.cmd("winit", ownode=0)
    p.cmd_kv("offworld", {"ownode": 5, "owdy": -6.0})
    got = p.cmd_kv("offworld", {"ownode": 5, "owdy": -3.0})
    fails += check("dy in (-5,-1) clears the counter",
                   [("fired", 0.0, got["owfired"]),
                    ("below", 0.0, got["below"])])

    # 3. the 61-frame drop
    p.reset()
    p.cmd("winit", ownode=0)
    fired_at = -1
    for i in range(1, 200):
        got = p.cmd_kv("offworld", {"ownode": 5, "owdy": -6.0})
        if got["owfired"]:
            fired_at = i
            break
    fails += check("dy < -5 fires on frame 61 (0x3D)",
                   [("frame", 61.0, float(fired_at)),
                    ("counter cleared", 0.0, got["below"])])

    # 4. the 200-frame nav-walk-failure rescue
    p.reset()
    p.cmd("winit", ownode=0)
    fired_at = -1
    for i in range(1, 400):
        got = p.cmd_kv("navfail", {"walkok": 0})
        if got["navfired"]:
            fired_at = i
            break
    fails += check("nav-walk failure fires at 201 (> 0xC8)",
                   [("frame", 201.0, float(fired_at)),
                    ("counter cleared", 0.0, got["navfail"])])

    # 5. retail does NOT clear it on a good frame (only the rescue does)
    p.reset()
    p.cmd("winit", ownode=0)
    p.cmd_kv("navfail", {"walkok": 0})
    p.cmd_kv("navfail", {"walkok": 0})
    got = p.cmd_kv("navfail", {"walkok": 1})
    fails += check("a good walk does not reset the counter",
                   [("counter", 2.0, got["navfail"])])

    # 6. the skip-once latch (FUN_00171650 -> FUN_00170820 @0x001708C7)
    p.reset()
    got = p.cmd("winit", ownode=3)
    fails += check("the re-placer's skip latch starts clear",
                   [("skip", 0.0, got["skip"]),
                    ("route alt starts at 1", 1.0, got["alt"])])
    return fails


def main():
    if not os.path.exists(os.path.join(ROOT, "build", "burnout3.elf")):
        raise SystemExit("build/burnout3.elf missing -- run tools/xbe2elf.py")
    os.chdir(ROOT)
    total = 0
    counts = []
    for fn in (run_commit, run_angle, run_drift_angle, run_corner,
               run_target_speed, run_drive, run_governor, run_brake,
               run_multiframe, run_param_check, run_aggro,
               run_aggro_consume, run_aggro_cycle, run_aggro_params,
               run_wheel, run_route_alt, run_corner_brake, run_watchdogs):
        f = fn()
        total += f
        counts.append((fn.__name__, f))
    n_cases = (len(COMMIT_CASES) + len(ANGLE_CASES) + len(DRIFT_ANGLE_CASES) +
               len(CORNER_CASES) + len(SPEED_CASES) + len(DRIVE_CASES) +
               len(GOV_CASES) + len(BRAKE_CASES) + 1 + 8 +
               len(AGGRO_CASES) + AGGRO_CONSUME_N + 1 + len(AGGRO_PARAMS) +
               len(WHEEL_CASES) + len(ALT_CASES) + len(CBRAKE_CASES) + 6)
    print("\n%d/%d AI cases green (%d commit, %d angle, %d drift-angle, "
          "%d corner, %d target-speed, %d driver, %d governor, %d brake, "
          "1 multi-frame, 8 params, %d aggression states, %d aggression "
          "channels, 1 attack cycle, %d aggression params, %d wheel, "
          "%d route-alt, %d corner-brake, 6 watchdog)"
          % (n_cases - total, n_cases, len(COMMIT_CASES), len(ANGLE_CASES),
             len(DRIFT_ANGLE_CASES), len(CORNER_CASES), len(SPEED_CASES),
             len(DRIVE_CASES), len(GOV_CASES), len(BRAKE_CASES),
             len(AGGRO_CASES), AGGRO_CONSUME_N, len(AGGRO_PARAMS),
             len(WHEEL_CASES), len(ALT_CASES), len(CBRAKE_CASES)))
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
